# Plan de SFT para MedGemma

Cuaderno reorganizado para entrenar, evaluar y comparar variantes de MedGemma para resúmenes PLS: prepara datos, ajusta con Unsloth/LoRA, ejecuta evaluaciones cuantitativas y cualitativas, y mantiene flujos separados para AlignScore.

## Tabla de contenidos
- [1. Instalación y configuración inicial](#1-instalacion-y-configuracion-inicial)
- [2. Carga y preprocesamiento de datos](#2-carga-y-preprocesamiento-de-datos)
- [3. Configuración del modelo y LoRA](#3-configuracion-del-modelo-y-lora)
- [4. Generación y limpieza de salidas](#4-generacion-y-limpieza-de-salidas)
- [5. Evaluación cuantitativa y preparación](#5-evaluacion-cuantitativa-y-preparacion)
- [6. Evaluación cualitativa y profiling](#6-evaluacion-cualitativa-y-profiling)
- [7. Generación con modelos fundacionales](#7-generacion-con-modelos-fundacionales)
- [8. Evaluación modular sin AlignScore](#8-evaluacion-modular-sin-alignscore)
- [9. Flujo AlignScore en entorno aislado](#9-flujo-alignscore-en-entorno-aislado)

## 1. Instalación y configuración inicial
Instala dependencias, importa librerías base, autentica con Hugging Face/Drive y define variables clave para el proyecto.

In [ ]:
# Celda 1: Instalación de librerías (Actualizada)
# MEJORA: Añadimos 'unsloth' para un fine-tuning más rápido y eficiente en memoria.
# MEJORA: Añadimos 'summac' para la métrica de factualidad y 'textstat' para legibilidad completa.
!pip install -q "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install -q --no-deps trl peft accelerate bitsandbytes
!pip install -q transformers datasets scikit-learn tensorboard
!pip install -q evaluate bert_score textstat tqdm

# NLTK ya no es necesario, pero añadimos s
!pip install -q datasets evaluate bert_score textstat tqdm pandas numpy spacy
# Descargamos el modelo de lenguaje pequeño para inglés de spaCy
!python -m spacy download en_core_web_sm

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.4/59.4 MB 14.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 506.8/506.8 kB 30.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 283.5/283.5 kB 24.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.6/132.6 kB 12.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.7/47.7 MB 23.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 106.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 kB 29.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 213.6/213.6 kB 18.2 MB/s eta 0:00:00
  Building wheel for unsloth (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.4/176.4 kB 14.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 84.7 MB/s eta 0:00:00
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 136.7 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [ ]:
# Celda 2: Importación de librerías (Actualizada)
import os
import torch
import gc
import time
import pandas as pd
import numpy as np
from datasets import load_dataset, Dataset, DatasetDict, concatenate_datasets
from collections import defaultdict

# MEJORA: Importaciones de Unsloth
from unsloth import FastLanguageModel

from transformers import (
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
    DataCollatorForSeq2Seq
)
from peft import LoraConfig
from trl import SFTTrainer

# --- Para evaluación ---
from tqdm.auto import tqdm

# Importaciones clave (VOLVEMOS A USAR UNSLOTH)
from unsloth import FastLanguageModel
from datasets import load_dataset, Dataset, DatasetDict
import evaluate
import textstat
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification # <<<--- NUEVA IMPORTACIÓN
import spacy # <--- NUEVA IMPORTACIÓN

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!

In [ ]:
# El resto de las celdas de configuración (3, 4, 5) para autenticación y montaje de Drive se mantienen igual.
# Asegúrate de que las rutas en la Celda 5 sean correctas.
# ... (código de login y montaje de Drive) ...

In [ ]:
# Celda 3: Login en Hugging Face
from google.colab import userdata
from huggingface_hub import login

print("Configurando la API Key de HuggingFace...")
try:
    # Obtener la API key de los "Secrets" de Google Colab
    # Asegúrate de haber agregado tu HUGGING_API_KEY a los Secrets
    API_KEY = userdata.get('HUGGING_API_KEY')
    login(token=API_KEY)
    print("API Key configurada exitosamente.")
except Exception as e:
    print(f"Error al configurar la API Key: {e}")
    print("Por favor, asegúrate de que 'HUGGING_API_KEY' esté guardada en los 'Secrets' de Colab (icono de la llave).")
    raise

Configurando la API Key de HuggingFace...
API Key configurada exitosamente.

In [ ]:
# Celda 4: Montar Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Celda 5.1: Definición de variables clave
import os
BASE_PROJECT_DIR = "/content/drive/MyDrive/NLP_Project_MedGemma"
MODEL_OUTPUT_DIR = os.path.join(BASE_PROJECT_DIR, "medgemma-finetuned-v8")
LOGS_DIR = os.path.join(BASE_PROJECT_DIR, "logs-v8")
MODEL_ID = "google/medgemma-4b-it" # Usamos la versión más reciente y ligera para empezar

os.makedirs(MODEL_OUTPUT_DIR, exist_ok=True)
os.makedirs(LOGS_DIR, exist_ok=True)

print(f"Directorio del proyecto: {BASE_PROJECT_DIR}")
print(f"Directorio de salida del modelo: {MODEL_OUTPUT_DIR}")
print(f"Modelo base a utilizar: {MODEL_ID}")

Directorio del proyecto: /content/drive/MyDrive/NLP_Project_MedGemma
Directorio de salida del modelo: /content/drive/MyDrive/NLP_Project_MedGemma/medgemma-finetuned-v8
Modelo base a utilizar: google/medgemma-4b-it

## 2. Carga y preprocesamiento de datos
Clona el repositorio de datos, combina todas las fuentes, convierte a pandas, muestra ejemplos y formatea prompts para todos los splits.

In [ ]:
# Celda 6: Clonar el repositorio con los datos
GIT_REPO_URL = "https://github.com/feliperussi/bridging-the-gap-in-health-literacy.git"
REPO_DIR = "/content/bridging-the-gap-in-health-literacy"

if not os.path.exists(REPO_DIR):
    !git clone {GIT_REPO_URL}
else:
    print("El repositorio ya ha sido clonado.")

# Definimos la ruta principal a los datos que nos interesan
DATA_SOURCES_DIR = os.path.join(REPO_DIR, "data_collection_and_processing/Data Sources")
print(f"Datos descargados en: {DATA_SOURCES_DIR}")
!ls -l "{DATA_SOURCES_DIR}"

Cloning into 'bridging-the-gap-in-health-literacy'...
remote: Enumerating objects: 72074, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 72074 (delta 0), reused 2 (delta 0), pack-reused 72071 (from 2)
Receiving objects: 100% (72074/72074), 315.90 MiB | 21.31 MiB/s, done.
Resolving deltas: 100% (2991/2991), done.
Updating files: 100% (87209/87209), done.
Datos descargados en: /content/bridging-the-gap-in-health-literacy/data_collection_and_processing/Data Sources
total 20
drwxr-xr-x 4 root root 4096 Nov 18 12:34  ClinicalTrials.gov
drwxr-xr-x 4 root root 4096 Nov 18 12:34  Cochrane
drwxr-xr-x 5 root root 4096 Nov 18 12:34  Pfizer
-rw-r--r-- 1 root root 2406 Nov 18 12:34  README.md
drwxr-xr-x 6 root root 4096 Nov 18 12:34 'Trial Summaries'

In [ ]:
# Celda 7 (Reescrita y Mejorada): Cargar, Emparejar y Estructurar TODOS los datos

import os
import pandas as pd
from collections import defaultdict
from datasets import Dataset, DatasetDict, concatenate_datasets
from tqdm.auto import tqdm # Para barras de progreso

# --- Parte 1: Funciones de Carga Específicas por Fuente ---

def load_cochrane_pairs(cochrane_dir):
    """
    Carga y empareja los textos técnicos (non_pls) y sencillos (pls)
    específicamente de la fuente Cochrane.
    Devuelve dos listas de pares: una para train y otra para test.
    """
    print(f"Procesando fuente: Cochrane desde {cochrane_dir}")
    train_pairs, test_pairs = [], []

    for split in ['train', 'test']:
        split_path = os.path.join(cochrane_dir, split)
        if not os.path.exists(split_path):
            print(f"  Advertencia: No se encontró el directorio {split_path}")
            continue

        pls_dir = os.path.join(split_path, "pls")
        non_pls_dir = os.path.join(split_path, "non_pls")

        if not os.path.exists(pls_dir) or not os.path.exists(non_pls_dir):
            print(f"  Advertencia: Faltan las carpetas 'pls' o 'non_pls' en {split_path}")
            continue

        # Usamos un diccionario para encontrar los pares eficientemente
        paired_files = defaultdict(dict)

        # 1. Procesar archivos de lenguaje sencillo (pls)
        for filename in os.listdir(pls_dir):
            # MEJORA: Aseguramos que solo procesamos el archivo principal, no las secciones
            if filename.endswith('-pls.txt'):
                base_name = filename.replace('-pls.txt', '')
                paired_files[base_name]['pls'] = os.path.join(pls_dir, filename)

        # 2. Procesar archivos de lenguaje técnico (non_pls)
        for filename in os.listdir(non_pls_dir):
            # MEJORA: Aseguramos que solo procesamos el archivo principal
            if filename.endswith('-abstract.txt'):
                base_name = filename.replace('-abstract.txt', '')
                paired_files[base_name]['non_pls'] = os.path.join(non_pls_dir, filename)

        # 3. Leer el contenido de los archivos emparejados
        target_list = train_pairs if split == 'train' else test_pairs
        for base_name, paths in tqdm(paired_files.items(), desc=f"Emparejando Cochrane {split}"):
            if 'pls' in paths and 'non_pls' in paths:
                try:
                    with open(paths['non_pls'], 'r', encoding='utf-8') as f:
                        technical_text = f.read()
                    with open(paths['pls'], 'r', encoding='utf-8') as f:
                        plain_summary = f.read()

                    if technical_text and plain_summary:
                        target_list.append({
                            "technical_text": technical_text,
                            "plain_summary": plain_summary,
                            "source": "Cochrane"
                        })
                except Exception as e:
                    print(f"  Error al leer el par para {base_name}: {e}")

    return train_pairs, test_pairs


def load_pfizer_clinicaltrials_pairs(pfizer_dir, clinicaltrials_dir):
    """
    Carga y empareja los resúmenes sencillos (pls) de Pfizer con los textos
    técnicos correspondientes de ClinicalTrials.gov usando el NCT ID.
    Devuelve dos listas de pares: una para train y otra para test.
    """
    print(f"Procesando fuentes: Pfizer y ClinicalTrials.gov")
    train_pairs, test_pairs = [], []

    for split in ['train', 'test']:
        # Ruta a los resúmenes sencillos de Pfizer
        pfizer_pls_dir = os.path.join(pfizer_dir, split, "pls")
        # Ruta a los textos técnicos de ClinicalTrials.gov
        clinicaltrials_tech_dir = os.path.join(clinicaltrials_dir, split)

        if not os.path.exists(pfizer_pls_dir) or not os.path.exists(clinicaltrials_tech_dir):
            print(f"  Advertencia: Faltan directorios para el split '{split}' en Pfizer o ClinicalTrials.gov")
            continue

        target_list = train_pairs if split == 'train' else test_pairs
        for filename in tqdm(os.listdir(pfizer_pls_dir), desc=f"Emparejando Pfizer/ClinicalTrials {split}"):
            # MEJORA: Nos aseguramos de tomar el archivo base (NCT...txt) y no sus secciones
            if filename.startswith('NCT') and filename.endswith('.txt') and '_section' not in filename:
                nct_id = filename

                # Buscar el archivo técnico correspondiente en ClinicalTrials.gov
                tech_file_path = os.path.join(clinicaltrials_tech_dir, nct_id)

                if os.path.exists(tech_file_path):
                    try:
                        with open(tech_file_path, 'r', encoding='utf-8') as f:
                            technical_text = f.read()
                        with open(os.path.join(pfizer_pls_dir, filename), 'r', encoding='utf-8') as f:
                            plain_summary = f.read()

                        if technical_text and plain_summary:
                            target_list.append({
                                "technical_text": technical_text,
                                "plain_summary": plain_summary,
                                "source": "Pfizer/ClinicalTrials"
                            })
                    except Exception as e:
                        print(f"  Error al leer el par para {nct_id}: {e}")

    return train_pairs, test_pairs

# --- Parte 2: Orquestador de Carga de Datos ---

DATA_SOURCES_DIR = "/content/bridging-the-gap-in-health-literacy/data_collection_and_processing/Data Sources"
cochrane_train, cochrane_test = load_cochrane_pairs(os.path.join(DATA_SOURCES_DIR, "Cochrane"))
pfizer_train, pfizer_test = load_pfizer_clinicaltrials_pairs(
    os.path.join(DATA_SOURCES_DIR, "Pfizer"),
    os.path.join(DATA_SOURCES_DIR, "ClinicalTrials.gov")
)

# Nota sobre "Trial Summaries":
print("\nNota: La fuente 'Trial Summaries' se omite en esta fase porque no contiene pares de textos (técnico/sencillo) claramente estructurados, solo resúmenes en lenguaje sencillo.")

all_train_pairs = cochrane_train + pfizer_train
all_test_pairs = cochrane_test + pfizer_test

print(f"\nTotal de pares de entrenamiento combinados: {len(all_train_pairs)}")
print(f"Total de pares de prueba combinados: {len(all_test_pairs)}")

if all_train_pairs and all_test_pairs:
    train_ds = Dataset.from_pandas(pd.DataFrame(all_train_pairs))
    test_ds = Dataset.from_pandas(pd.DataFrame(all_test_pairs))
    train_val_split = train_ds.train_test_split(test_size=0.1, seed=42)

    final_dataset = DatasetDict({
        'train': train_val_split['train'],
        'validation': train_val_split['test'],
        'test': test_ds
    })

    print("\n--- Distribución Final del Dataset Combinado ---")
    print(f"Entrenamiento: {len(final_dataset['train'])} ejemplos")
    print(f"Validación:    {len(final_dataset['validation'])} ejemplos")
    print(f"Prueba:        {len(final_dataset['test'])} ejemplos")

    # AQUÍ SE DEFINEN LAS VARIABLES QUE CAUSABAN EL ERROR
    train_dataset = final_dataset['train']
    val_dataset = final_dataset['validation']
    test_dataset = final_dataset['test']
else:
    raise RuntimeError("No se cargaron datos. Revisa las rutas y la estructura de archivos.")

Procesando fuente: Cochrane desde /content/bridging-the-gap-in-health-literacy/data_collection_and_processing/Data Sources/Cochrane

Emparejando Cochrane train:   0%|          | 0/7559 [00:00<?, ?it/s]

Emparejando Cochrane test:   0%|          | 0/2567 [00:00<?, ?it/s]

Procesando fuentes: Pfizer y ClinicalTrials.gov

Emparejando Pfizer/ClinicalTrials train:   0%|          | 0/490 [00:00<?, ?it/s]

Emparejando Pfizer/ClinicalTrials test:   0%|          | 0/116 [00:00<?, ?it/s]

Nota: La fuente 'Trial Summaries' se omite en esta fase porque no contiene pares de textos (técnico/sencillo) claramente estructurados, solo resúmenes en lenguaje sencillo.

Total de pares de entrenamiento combinados: 3641
Total de pares de prueba combinados: 221

--- Distribución Final del Dataset Combinado ---
Entrenamiento: 3276 ejemplos
Validación:    365 ejemplos
Prueba:        221 ejemplos

In [ ]:
# Convertir final_dataset (type DatasetDict) a df de pandas
import pandas as pd
import os

# Convert each split to a pandas DataFrame and concatenate them
df_train = final_dataset['train'].to_pandas()
df_validation = final_dataset['validation'].to_pandas()
df_test = final_dataset['test'].to_pandas()

# Guardar el final_dataset como csv
BASE_DATASETS_DIR = os.path.join(BASE_PROJECT_DIR, "medgemma-finetuned-v8_datasets")

os.makedirs(BASE_DATASETS_DIR, exist_ok=True)

df_train_path = os.path.join(BASE_DATASETS_DIR, 'df_train.csv')
df_validation_path = os.path.join(BASE_DATASETS_DIR, 'df_validation.csv')
df_test_path = os.path.join(BASE_DATASETS_DIR, 'df_test.csv')
df_train.to_csv(df_train_path, index=False)
df_validation.to_csv(df_validation_path, index=False)
df_test.to_csv(df_test_path, index=False)

print(f"Datasets guardados en: {df_train_path, df_validation_path, df_test_path}")

Datasets guardados en: ('/content/drive/MyDrive/NLP_Project_MedGemma/medgemma-finetuned-v8_datasets/df_train.csv', '/content/drive/MyDrive/NLP_Project_MedGemma/medgemma-finetuned-v8_datasets/df_validation.csv', '/content/drive/MyDrive/NLP_Project_MedGemma/medgemma-finetuned-v8_datasets/df_test.csv')

In [ ]:
# Celda 7.1: Imprimir un par de ejemplo del dataset combinado
if final_dataset and len(final_dataset['train']) > 0:
    print("\n--- Ejemplo de un par de texto técnico y resumen en lenguaje sencillo ---")
    example = final_dataset['validation'][220] # Tomamos el primer ejemplo del conjunto de entrenamiento
    print("\nTexto Técnico:")
    print(example['technical_text'][::] + "...") # Imprimimos solo los primeros 500 caracteres
    print("\nResumen en Lenguaje Sencillo (PLS):")
    print(example['plain_summary'][:] + "...") # Imprimimos solo los primeros 500 caracteres
    print("\nFuente:", example['source'])
else:
    print("\nEl dataset final está vacío o no ha sido creado correctamente.")

--- Ejemplo de un par de texto técnico y resumen en lenguaje sencillo ---

Texto Técnico:
Background
Active management of the third stage of labour reduces the risk of postpartum blood loss (postpartum haemorrhage (PPH)), and is defined as administration of a prophylactic uterotonic, early umbilical cord clamping and controlled cord traction to facilitate placental delivery. The choice of uterotonic varies across the globe and may have an impact on maternal outcomes. This is an update of a review first published in 2001 and last updated in 2013.
Objectives
To determine the effectiveness of prophylactic oxytocin to prevent PPH and other adverse maternal outcomes in the third stage of labour.
Search methods
For this update, we searched Cochrane Pregnancy and Childbirth’s Trials Register, ClinicalTrials.gov, WHO International Clinical Trials Registry Platform (ICTRP) (6 March 2019) and reference lists of retrieved studies.
Selection criteria
Randomised, quasi‐ or cluster‐randomised trials including women undergoing vaginal delivery who received prophylactic oxytocin during management of the third stage of labour. Primary outcomes were blood loss 500 mL or more after delivery, need for additional uterotonics, and maternal all‐cause mortality.
Data collection and analysis
Two review authors independently assessed trials for inclusion, extracted data, and assessed trial quality. Data were checked for accuracy. We assessed the quality of the evidence using the GRADE approach.
Main results
This review includes 24 trials, with 23 trials involving 10,018 women contributing data. Due to many trials assessed at high risk of bias, evidence grade ranged from very low to moderate quality.
Prophylactic oxytocin versus no uterotonics or placebo (nine trials) Prophylactic oxytocin compared with no uterotonics or placebo may reduce the risk of blood loss of 500 mL after delivery (average risk ratio (RR) 0.51, 95% confidence interval (C) 0.37 to 0.72; 4162 women; 6 studies; Tau² = 0.10, I² = 75%; low‐quality evidence), and blood loss 1000 mL after delivery (RR 0.59, 95% CI 0.42 to 0.83; 4123 women; 5 studies; low‐quality evidence). Prophylactic oxytocin probably reduces the need for additional uterotonics (average RR 0.54, 95% CI 0.36 to 0.80; 3135 women; 4 studies; Tau² = 0.07, I² = 44%; moderate‐quality evidence). There may be no difference in the risk of needing a blood transfusion in women receiving oxytocin compared to no uterotonics or placebo (RR 0.88, 95% CI 0.44 to 1.78; 3081 women; 3 studies; low‐quality evidence). Oxytocin may be associated with an increased risk of a third stage greater than 30 minutes (RR 2.55, 95% CI 0.88 to 7.44; 1947 women; 1 study; moderate‐quality evidence), however the confidence interval is wide and includes 1.0, indicating that there may be little or no difference.  Prophylactic oxytocin versus ergot alkaloids (15 trials)
It is uncertain whether oxytocin reduces the likelihood of blood loss 500 mL (average RR 0.84, 95% CI 0.56 to 1.25; 3082 women; 10 studies; Tau² = 0.14, I² = 49%; very low‐quality evidence) or the need for additional uterotonics compared to ergot alkaloids (average RR 0.89, 95% CI 0.43 to 1.81; 2178 women; 8 studies; Tau² = 0.76, I² = 79%; very low‐quality evidence), because the quality of this evidence is very low. The quality of evidence was very low for blood loss of 1000 mL (RR 1.13, 95% CI 0.63 to 2.01; 1577 women; 3 studies; very low‐quality evidence), and need for blood transfusion (average RR 1.37, 95% CI 0.34 to 5.51; 1578 women; 7 studies; Tau² = 1.34, I² = 45%; very low‐quality evidence), making benefit of oxytocin over ergot alkaloids uncertain. Oxytocin probably increases the risk of a prolonged third stage greater than 30 minutes (RR 4.69, 95% CI 1.63 to 13.45; 450 women; 2 studies; moderate‐quality evidence), although it is uncertain if this translates into increased risk of manual placental removal (average RR 1.10, 95% CI 0.39 to 3.10; 3127 women; 8 studies; Tau² = 1.07, I² = 76%; very low‐quality evidence). Oxytocin may make little or no difference to risk of diastolic blood pressure > 100 mm Hg (average RR 0.28, 95% CI 0.04 to 2.05; 960 women; 3 studies; Tau² = 1.23, I² = 50%; low‐quality evidence), and is probably associated with a lower risk of vomiting (RR 0.09, 95% CI 0.05 to 0.14; 1991 women; 7 studies; moderate‐quality evidence), although the impact of oxytocin on headaches is uncertain (average RR 0.19, 95% CI 0.03 to 1.02; 1543 women; 5 studies; Tau² = 2.54, I² = 72%; very low‐quality evidence).
Prophylactic oxytocin‐ergometrine versus ergot alkaloids (four trials) Oxytocin‐ergometrine may slightly reduce the risk of blood loss greater than 500 mL after delivery compared to ergot alkaloids (RR 0.44, 95% CI 0.20 to 0.94; 1168 women; 3 studies; low‐quality evidence), based on outcomes from quasi‐randomised trials with a high risk of bias. There were no maternal deaths reported in either treatment group in the one trial that reported this outcome (RR not estimable; 1 trial, 807 women; moderate‐quality evidence). Need for additional uterotonics was not reported.
No subgroup differences were observed between active or expectant management, or different routes or doses of oxytocin for any of our comparisons.
Authors' conclusions
Prophylactic oxytocin compared with no uterotonics may reduce blood loss and the need for additional uterotonics. The effect of oxytocin compared to ergot alkaloids is uncertain with regards to blood loss, need for additional uterotonics, and blood transfusion. Oxytocin may increase the risk of a prolonged third stage compared to ergot alkaloids, although whether this translates into increased risk of manual placental removal is uncertain. This potential risk must be weighed against the possible increased risk of side effects associated with ergot alkaloids. Oxytocin‐ergometrine may reduce blood loss compared to ergot alkaloids, however the certainty of this conclusion is low. More high‐quality trials are needed to assess optimal dosing and route of oxytocin administration, with inclusion of important outcomes such as maternal mortality, shock, and transfer to a higher level of care. A network meta‐analysis of uterotonics for PPH prevention plans to address issues around optimal dosing and routes of oxytocin and other uterotonics.
...

Resumen en Lenguaje Sencillo (PLS):
Oxytocin to prevent excessive blood loss for women during the third stage of labour
What is the issue?
Active management of the third stage of labour (AMTSL) has been shown to decrease the risk of excessive blood loss after delivery. This management strategy has been defined as administration of a medication to increase uterine tone and contractions, early umbilical cord clamping and gentle cord traction to facilitate placental delivery. While AMTSL has become standard practice in many countries and institutions, execution of the individual components varies. Oxytocin is a uterotonic medication that promotes increased uterine tone and contractions, and is commonly administered immediately following delivery of the infant's shoulder as part of AMTSL. This review considers the efficacy and safety of oxytocin prophylaxis in the third stage of labour compared with no uterotonics, a placebo, ergot alkaloids, and in combination with ergometrine compared with ergot alkaloids.
Why is this important?
Postpartum haemorrhage is one of the most prevalent causes of maternal morbidity and mortality worldwide, therefore, determining the most effective preventative strategies is crucial.
What evidence did we find?
We searched for evidence in March 2019 and identified six trials that met the inclusion criteria for the review. Outcomes from an additional 1100 women from these six trials was combined with those from the previous version of this review for a total of 10,018 women (23 trials). Of note, two previously included trials were excluded from this current review due to methodological concerns. The majority of trials contributing information to this review were found to be at high risk of bias. The quality of evidence ranged from very low to moderate, and for most outcomes was assessed as low to very low quality.
Our results showed that compared to no uterotonics or placebo, oxytocin may reduce the risk of blood loss (quality of evidence: low) and the need for additional uterotonics (quality of evidence: moderate). The effect of oxytocin compared with ergot alkaloids is uncertain with regards to blood loss (quality of evidence: very low), need for additional uterotonics (quality of evidence: very low), and need for blood transfusion (quality of evidence: very low), but may increase the risk of a third stage greater than 30 minutes (quality of evidence: moderate). Whether or not this translates into increased risk of needing a manual placental removal is uncertain (quality of evidence: very low). This potential risk of retained placenta must be weighed against a possible increased risk of side effects with ergot alkaloids, including diastolic hypertension (quality of evidence: low), vomiting (quality of evidence: very low), and headaches (quality of evidence: very low). While the combination of oxytocin and ergometrine may slightly reduce the risk of blood loss compared to ergot alkaloids (quality of evidence: low), the certainty of this conclusion is low given the poor quality of contributing studies.
What does this mean?
Oxytocin may reduce blood loss and the need for additional uterotonics when given prophylactically in the third stage of labour, and therefore could be considered as a component of AMTSL. The side‐effect profile may be more favourable than ergot alkaloids, which must be weighed against a possible increased risk of third stage greater than 30 minutes and unclear benefit of oxytocin or ergot alkaloids with regards to blood loss.  More placebo‐controlled, randomised, double‐blinded trials are needed to improve the quality of data used to compare oxytocin versus ergot alkaloids. Future studies should aim to include important outcomes such as maternal mortality, shock, transfer to a higher level of care, serious side effects, and other patient‐centred outcomes. A large complex review analysing all available data from different uterotonic medications (network meta‐analysis) will help to inform future choice of uterotonic and the best route and dose of administration.
...

Fuente: Cochrane

In [ ]:
# Celda 8 (Reescrita y Mejorada): Definición del Prompt y Preprocesamiento para Todos los Splits

# MEJORA: Reemplazamos el prompt simple por la plantilla avanzada y optimizada en español.
# Esta plantilla establece un rol, define reglas estrictas y alinea la tarea con las métricas.
def create_optimized_prompt(technical_text, plain_summary=None):
    """
    Crea la plantilla de prompt completa. Si se proporciona un 'plain_summary',
    se genera el formato para entrenamiento (SFT). De lo contrario, se genera
    el formato para inferencia.
    """
    system_prompt = (
        "You are a Health Literacy Expert."
        "Your expertise is in rewriting complex, technical medical texts into clear, simple, and accurate language for a general audience, following established health communication guidelines."
    )

    instruction_template = f"""**[PRIMARY GOAL]**
        Your main purpose is to rewrite the provided medical text into a Plain Language Summary (PLS).
        This summary must be easy to understand for someone with an 8th-grade reading comprehension level typical of a general middle-school student,
        consistent with plain-language standards used by CDC and NIH, meaning it should use simple vocabulary, short sentences,
        and concepts that can be understood by someone with basic middle-school literacy,
        while remaining completely faithful to the source's essential information, for intance, conclusions.

        **[TASK INSTRUCTION]**
        Rewrite the following technical medical text into a Plain Language Summary (PLS).
        The output **MUST BE ONLY** the plain language summary without special symbols and stop tokens.

        **--- STRICT OUTPUT RULES ---**

        1.  **ACCURACY AND COMPLETENESS:**
        *   The summary MUST retain all key findings, main outcomes, important safety information, conclusions,and any significant numerical results from the original text.
        *   Do NOT add any information, opinions, or recommendations that are not present in the source document. The summary must be based ONLY on the provided text.

        2.  **CLARITY AND READABILITY:**
        *   Write the summary at an **8th-grade reading comprehension level typical of a general middle-school student**.
        *   Use short, clear, and natural-sounding sentences.
        *   Use the active voice whenever possible (e.g., "Scientists tested the drug" instead of "The drug was tested by scientists").
        *   Avoid long, complex words when a simpler alternative exists.

        3.  **TERMINOLOGY (JARGON):**
        *   Avoid medical jargon.
        *   If a technical term is absolutely essential and cannot be replaced, you MUST explain it simply in parentheses the first time it appears. (Example: "The trial used immunotherapy (a treatment that helps the body's immune system fight cancer).")

        4.  **FORMATTING AND LANGUAGE:**
        *   The output **MUST BE ONLY** the plain language summary without special symbols and stop tokens, **only the summary**.
        *   The output must be written **ONLY in English**.
        *   Structure the summary as a set of concise paragraphs. Use as many sentences as needed to include all essential information, up to a maximum length of about 500 words, however, **make sure ALL sentences are complete, which means ALL ideas are finished.**
        *   Do NOT include headings, bullet points, lists, citations, or URLs.

        **--- SOURCE TECHNICAL TEXT ---**
        <document>
        {technical_text}
        </document>

        **--- PLAIN LANGUAGE SUMMARY (PLS) ---**
      """

    if plain_summary is not None:
        # === CAMBIO CLAVE PARA ENTRENAMIENTO ===
        # El formato ahora es: INSTRUCCIÓN -> RESPUESTA -> FIN DE SECUENCIA
        # Eliminamos tus etiquetas personalizadas <plain_language_summary>.
        # La respuesta (plain_summary) va directamente después de [/INST].
        # Añadimos el token de fin de secuencia (</s>) al final de la respuesta.
        # Esto enseña al modelo que, cuando termine de generar el resumen, debe emitir la señal de parada.
        prompt = f"<s>[INST] {system_prompt}\n\n{instruction_template} [/INST]\n{plain_summary}</s>"
        return prompt
    else:
        # === CAMBIO CLAVE PARA INFERENCIA ===
        # El prompt para la inferencia debe terminar EXACTAMENTE donde el modelo debe empezar a escribir.
        # Es decir, justo después de [/INST] y un salto de línea.
        prompt = f"<s>[INST] {system_prompt}\n\n{instruction_template} [/INST]\n"
        return prompt


# MEJORA: Esta función prepara los datos para el SFTTrainer, que espera una única columna de texto.
def formatting_prompts_func(example):
    # Aseguramos que los campos no sean nulos
    technical_text = example.get("technical_text", "")
    plain_summary = example.get("plain_summary", "")

    # Creamos el prompt formateado para el entrenamiento
    example["text"] = create_optimized_prompt(technical_text, plain_summary)
    return example

In [ ]:
# MEJORA: Aplicamos el formateo a TODOS los splits del dataset (train, validation, y test).
# Usamos `remove_columns` para dejar solo la columna 'text' que necesita el SFTTrainer.
print("Formateando los datasets para el entrenamiento...")

train_dataset_formatted = train_dataset.map(
    formatting_prompts_func,
    remove_columns=list(train_dataset.features)
)
val_dataset_formatted = val_dataset.map(
    formatting_prompts_func,
    remove_columns=list(val_dataset.features)
)
test_dataset_formatted = test_dataset.map(
    formatting_prompts_func,
    remove_columns=list(test_dataset.features)
)

print("\nFormateo completado.")
print(f"Columnas del dataset de entrenamiento: {train_dataset_formatted.column_names}")

# --- Verificación ---
print("\n--- Ejemplo de Prompt Formateado para Entrenamiento ---")
print(train_dataset_formatted[0]['text'])
print("-" * 50)

Formateando los datasets para el entrenamiento...

Map:   0%|          | 0/3276 [00:00<?, ? examples/s]

Map:   0%|          | 0/365 [00:00<?, ? examples/s]

Map:   0%|          | 0/221 [00:00<?, ? examples/s]

Formateo completado.
Columnas del dataset de entrenamiento: ['text']

--- Ejemplo de Prompt Formateado para Entrenamiento ---
<s>[INST] You are a Health Literacy Expert.Your expertise is in rewriting complex, technical medical texts into clear, simple, and accurate language for a general audience, following established health communication guidelines.

**[PRIMARY GOAL]**
        Your main purpose is to rewrite the provided medical text into a Plain Language Summary (PLS).
        This summary must be easy to understand for someone with an 8th-grade reading comprehension level typical of a general middle-school student,
        consistent with plain-language standards used by CDC and NIH, meaning it should use simple vocabulary, short sentences,
        and concepts that can be understood by someone with basic middle-school literacy,
        while remaining completely faithful to the source's essential information, for intance, conclusions.

        **[TASK INSTRUCTION]**
        Rewrite the following technical medical text into a Plain Language Summary (PLS).
        The output **MUST BE ONLY** the plain language summary without special symbols and stop tokens.

        **--- STRICT OUTPUT RULES ---**

        1.  **ACCURACY AND COMPLETENESS:**
        *   The summary MUST retain all key findings, main outcomes, important safety information, conclusions,and any significant numerical results from the original text.
        *   Do NOT add any information, opinions, or recommendations that are not present in the source document. The summary must be based ONLY on the provided text.

        2.  **CLARITY AND READABILITY:**
        *   Write the summary at an **8th-grade reading comprehension level typical of a general middle-school student**.
        *   Use short, clear, and natural-sounding sentences.
        *   Use the active voice whenever possible (e.g., "Scientists tested the drug" instead of "The drug was tested by scientists").
        *   Avoid long, complex words when a simpler alternative exists.

        3.  **TERMINOLOGY (JARGON):**
        *   Avoid medical jargon.
        *   If a technical term is absolutely essential and cannot be replaced, you MUST explain it simply in parentheses the first time it appears. (Example: "The trial used immunotherapy (a treatment that helps the body's immune system fight cancer).")

        4.  **FORMATTING AND LANGUAGE:**
        *   The output **MUST BE ONLY** the plain language summary without special symbols and stop tokens, **only the summary**.
        *   The output must be written **ONLY in English**.
        *   Structure the summary as a set of concise paragraphs. Use as many sentences as needed to include all essential information, up to a maximum length of about 500 words, however, **make sure ALL sentences are complete, which means ALL ideas are finished.**
        *   Do NOT include headings, bullet points, lists, citations, or URLs.

        **--- SOURCE TECHNICAL TEXT ---**
        <document>
        Background
Fractures of the olecranon (the bony tip of the elbow) account for approximately 1% of all upper extremity fractures. Surgical intervention is often required to restore elbow function. Two key methods of surgery are tension band wire fixation and plate fixation.
Objectives
To assess the effects (benefits and harms) of different surgical interventions in the treatment of olecranon fractures in adults.
Search methods
We searched the Cochrane Bone, Joint and Muscle Trauma Group Specialised Register (22 September 2014), the Cochrane Central Register of Controlled Trials (CENTRAL, 2014, Issue 8), MEDLINE (1946 to September week 2 2014), EMBASE (1980 to 19 September 2014), trial registers, conference proceedings and reference lists of articles.
Selection criteria
Randomised controlled trials (RCT) and quasi‐RCTs that compared different surgical interventions for the treatment of olecranon fractures in adults.
Data collection and analysis
Two review authors independently performed study selection, risk of bias assessment and data extraction. The primary outcomes of this review were function, pain and adverse events.
Main results
We included six small trials involving 244 adults with olecranon fractures. Of these, four were RCTs and two were quasi‐RCTs; both of were at high risk of selection bias. All six trials were at high risk of performance bias, reflecting lack of blinding, and four trials were at high risk of detection bias. The quality of the evidence for most outcomes was generally very low because of limitations in study design and implementation, and either imprecision of the results or inadequate outcome measures. Thus, we are very uncertain about the estimates of effect.
One trial (41 participants) comparing plate fixation with standard tension band wiring provided very low quality evidence at 16 to 86 weeks' follow‐up of a better clinical outcome after plate fixation (good outcome (little pain or loss of elbow motion): 19/22 versus 9/19, risk ratio (RR) 1.82 favouring plate fixation, 95% confidence interval (CI) 1.10 to 3.01). There was very low quality evidence of less symptomatic prominent metalwork after plate fixation (1/22 versus 8/19; RR 0.11, 95% CI 0.01 to 0.79). The results for other adverse effects (infection and delayed or non‐union) were inconclusive. Evidence is pending from a newly (September 2014) completed trial (67 participants) making the same comparison.
Four trials compared four different modified techniques of tension band wiring (i.e. additional intramedullary screw fixation, biodegradable pins, Netz pins and cable pin system) versus standard tension band wiring. There was very low quality evidence of little difference at six to 14 months in function assessed by a non‐validated scoring tool from the addition of an intramedullary screw. However, there were fewer cases of metalwork prominence in the intramedullary screw group (1/15 versus 8/15; RR 2.00, 95% CI 1.15 to 3.49; one trial; 30 participants). There was very low quality evidence from one trial (25 participants) of little difference in subjectively or objectively assessed good outcome at a mean of 20 months between tension band wiring with biodegradable implants versus metal implants. There were no adverse events, either non‐union or sinus or fluid accumulation, reported. All 10 participants in the metalwork group had an extra operation to remove their metalwork at one year. One trial, which did not report on function or pain, provided very low quality evidence of lower rates of metalwork for any reason or for symptoms after Netz pin tension band wiring compared with standard tension band wiring (11/21 with Netz pin versus 17/25 with standard tension band wiring; RR 0.77, 95% CI 0.47 to 1.26; 46 participants); this evidence also supports the possibility of higher rates of metalwork removal for Netz pins. Two intra‐operative complications occurred in the Netz pin group. The fourth trial, which compared the cable pin system with standard procedure, found low quality evidence that cable pin improved functional outcome at a mean of 21 months (Mayo Elbow Performance Score (MEPS), range 0 to 100: best outcome: mean difference (MD) 7.89 favouring cable pin, 95% CI 3.14 to 12.64; one trial; 62 participants). It also found low quality evidence of fewer postoperative complications in the cable pin group (1/30 with cable pin system versus 7/32 standard tension band wiring; RR 0.15, 95% CI 0.02 to 1.17), although the evidence did not rule out the converse.
One trial provided very low quality evidence of similar patient‐reported function using the Disabilities of the Arm, Shoulder and Hand questionnaire (0 to 100: worst function) at two or more years after fixation using a novel olecranon memory connector (OMC) compared with locking plate fixation (MD ‐0.70 favouring OMC, 95% CI ‐4.20 to 2.80; 40 participants). The only adverse event was a superficial infection in the locking plate group.
Authors' conclusions
There is insufficient evidence to draw robust conclusions on the relative effects of the surgical interventions evaluated by the included trials. Further evidence, including patient‐reported data, on the relative effects of plate versus tension band wiring is already pending from one recently completed RCT. Further RCTs, using good quality methods and reporting validated patient‐reported measures of function, pain and activities of daily living at set follow‐ups, are needed, including checking positive findings such as those relating to the use of an intramedullary screw and the cable pin system. Such trials should also include the systematic assessment of complications, further treatment including routine removal of metalwork and use of resources.

        </document>

        **--- PLAIN LANGUAGE SUMMARY (PLS) ---**
       [/INST]
Surgical interventions for treating fractures of the olecranon (an elbow bone) in adults
Surgical treatment of olecranon fracture
The bony tip of the elbow is called the olecranon. It is shaped to allow bending and straightening of the arm at the elbow. The olecranon sits directly under the skin of the elbow, which makes it vulnerable to injury and fracture (break) following a fall. When this happens, people are sometimes unable to straighten their arms. Treating this fracture usually involves an operation to re‐position the broken parts of the bone and then fix them in place using wires, pins, plates, screws and other devices.
Description of the studies included in the review
We searched the medical literature until September 2014 and found six trials, involving 244 adults with olecranon fractures. Each trial tested a different comparison. Tension band wiring, which is a commonly used technique for fixing these fractures, was the 'control' intervention in five trials.
Quality of the evidence
All six trials were small and had weaknesses that could affect the reliability of their results. We judged the overall quality of the evidence available for each comparison as either low or very low.
Summary of the evidence
One trial compared the use of plate fixation with tension band wiring. It found that more people had pain‐free elbow motion after plate fixation and fewer people had discomfort from metalwork prominence, which is a well‐known problem with wire fixation where the metal wiring on the surface of the bone just under the skin causes pain, discomfort and other problems.
Four trials compared different ways of wiring the fracture. Two trials found very little clear evidence of any differences between them. One trial found that adding an intramedullary screw (this is a screw that was inserted through the bone and along the central bone canal) to standard tension band wiring reduced the risk of the metalwork under the skin being prominent. Another trial found that the cable pin system improved function and resulted in fewer complications compared with standard tension band wiring.
Finally, one trial compared a new method of fixation using a titanium‐nickel device that once implanted takes the shape of the olecranon with locking plate fixation. It found no clear evidence of differences between the techniques in patient‐reported function and complications (the only complication was a superficial infection).
Conclusions
Currently, there is not enough evidence to determine the best treatment for these fractures with confidence. Further high quality research is needed, which is likely to have an important impact on our confidence in the estimates of the effects and will likely change the estimates.
</s>
--------------------------------------------------

## 3. Configuración del modelo y LoRA
Carga el modelo con FastLanguageModel, aplica cuantización en 4 bits y configura los parámetros LoRA para el ajuste fino.

In [ ]:
# Celda 10: Configuración de Cuantización y Carga del Modelo con Unsloth
# MEJORA: Cargamos el modelo usando FastLanguageModel de Unsloth.
# Esto aplica automáticamente optimizaciones como Flash Attention.
max_seq_length = 2048 # Aumentamos un poco por el prompt más largo

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = MODEL_ID,
    max_seq_length = max_seq_length,
    dtype = None,
    load_in_4bit = True,
)

==((====))==  Unsloth 2025.11.3: Fast Gemma3 patching. Transformers: 4.57.1.
   \\   /|    NVIDIA L4. Num GPUs = 1. Max memory: 22.161 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.8.0+cu126. CUDA: 8.9. CUDA Toolkit: 12.6. Triton: 3.4.0
\        /    Bfloat16 = TRUE. FA [Xformers = None. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: Gemma3 does not support SDPA - switching to fast eager.

model.safetensors:   0%|          | 0.00/4.12G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/210 [00:00<?, ?B/s]

processor_config.json:   0%|          | 0.00/70.0 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/4.69M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/670 [00:00<?, ?B/s]

In [ ]:
# Celda 11: Configuración de LoRA (con Mejoras)
# MEJORA: Habilitamos el entrenamiento para más capas (FFN) como recomendaste.
# Esto da más flexibilidad al modelo para adaptarse.
model = FastLanguageModel.get_peft_model(
    model,
    r = 16, #
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      #"gate_proj", "up_proj", "down_proj"   # Capas de Atención + FFN
                      ],
    lora_alpha = 32,
    lora_dropout = 0.05,
    bias = "none",
    use_gradient_checkpointing = True,
    random_state = 42,
    max_seq_length = max_seq_length,
)

model.print_trainable_parameters()

Unsloth: Dropout = 0 is supported for fast patching. You are using dropout = 0.05.
Unsloth will patch all other layers, except LoRA matrices, causing a performance hit.

Unsloth: Making `base_model.model.model.vision_tower.vision_model` require gradients
trainable params: 11,898,880 || all params: 4,311,978,352 || trainable%: 0.2759

In [ ]:
%%time
# Celda 13 y 14: Argumentos y Ejecución del Trainer (Actualizado para Unsloth)

# --- ARGUMENTOS Y EJECUCIÓN DEL TRAINER ---

# MEJORA: Usamos SFTTrainer de TRL, que está optimizado para este tipo de tareas.
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = train_dataset_formatted,
    eval_dataset = val_dataset_formatted,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    dataset_num_proc = 2,
    packing = False, # Mantener en False para esta tarea de secuencia a secuencia
    args = TrainingArguments(
        # --- Parámetros de Batch y Épocas ---
        per_device_train_batch_size = 32,
        gradient_accumulation_steps = 1, # Batch efectivo de 16
        num_train_epochs = 2,

        # --- Optimizador y Scheduler ---
        learning_rate = 5e-5,
        lr_scheduler_type = "cosine",
        warmup_steps = 25,
        optim = "adamw_8bit",
        weight_decay = 0.05,

        # --- Configuración de Precisión ---
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),

        # --- Guardado, Logging y Evaluación (CORREGIDO) ---
        output_dir = MODEL_OUTPUT_DIR,
        logging_steps = 10,
        eval_strategy = "steps",  # AÑADIR/MODIFICAR: Estrategia de evaluación por pasos
        # CORRECCIÓN: Se eliminan 'evaluation_strategy' y 'save_strategy'.
        # Ahora controlamos todo explícitamente con pasos.
        save_strategy = "steps",        # AÑADIR/MODIFICAR: Estrategia de guardado por pasos
        save_steps = 30,  # Guardar un checkpoint cada 100 pasos
        eval_steps = 30,  # Evaluar en el set de validación cada 100 pasos
        save_total_limit = 3, # Guardar solo los 3 mejores checkpoints
        load_best_model_at_end = True, # Cargar el mejor modelo al final del entrenamiento

        # --- Otros ---
        seed = 42,
    ),
)

# --- Iniciar entrenamiento ---
print("\n--- Iniciando Fine-tuning del Modelo ---")
trainer_stats = trainer.train()

# --- Guardar modelo final ---
print(f"\nGuardando el mejor modelo en: {MODEL_OUTPUT_DIR}")
trainer.save_model() # Guarda el mejor adaptador en el output_dir

Unsloth: Tokenizing ["text"] (num_proc=16):   0%|          | 0/3276 [00:00<?, ? examples/s]

Unsloth: Tokenizing ["text"] (num_proc=16):   0%|          | 0/365 [00:00<?, ? examples/s]

The model is already on multiple devices. Skipping the move to device specified in `args`.

--- Iniciando Fine-tuning del Modelo ---

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 3,276 | Num Epochs = 2 | Total steps = 206
O^O/ \_/ \    Batch size per device = 32 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (32 x 1 x 1) = 32
 "-____-"     Trainable parameters = 11,898,880 of 4,311,978,352 (0.28% trained)
/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize?ref=models
wandb: Paste an API key from your profile and hit enter:

 ··········

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: rich-coding (rich-coding-uniandes) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

wandb: Detected [huggingface_hub.inference, openai] in use.
wandb: Use W&B Weave for improved LLM call tracing. Install Weave with `pip install weave` then add `import weave` to the top of your script.
wandb: For more information, check out the docs at: https://weave-docs.wandb.ai/

Unsloth: Will smartly offload gradients to save VRAM!

Guardando el mejor modelo en: /content/drive/MyDrive/NLP_Project_MedGemma/medgemma-finetuned-v8
CPU times: user 1h 26s, sys: 43min 18s, total: 1h 43min 45s
Wall time: 1h 44min 34s

## 4. Generación y limpieza de salidas
Libera memoria, reimporta utilidades, define funciones de generación y limpieza de texto, ejecuta pruebas unitarias y vacía caché de GPU.

In [ ]:
#import torch
#import gc
##
### Eliminar las variables grandes que ya no necesitamos
### Esto le dice a Python que ya no las usamos
##del model
##del trainer
##del data_collator
##
### Forzar al recolector de basura de Python a limpiar
#gc.collect()
#
### Vaciar la caché de memoria de la GPU de PyTorch
### Este es el paso más importante para liberar la VRAM
#torch.cuda.empty_cache()

In [ ]:
%%time
import unsloth # IMPORTANTE! Debe ir al principio
import torch
import pandas as pd
import os
import textwrap
from transformers import AutoTokenizer
from unsloth import FastLanguageModel

# ==============================================================================
# PASO 1: CARGAR EL MODELO RÁPIDO Y FUSIONADO
# ==============================================================================
print("Cargando el modelo y fusionando los adaptadores para máxima velocidad...")

# Cargamos el modelo desde el checkpoint de Unsloth.
# Unsloth cargará el modelo base y aplicará los adaptadores LoRA.
max_seq_length = 4096 # Necesario como variable global
model, _ = FastLanguageModel.from_pretrained(
    model_name = MODEL_OUTPUT_DIR,
    max_seq_length = max_seq_length,
    dtype = None, # Permite a Unsloth elegir el mejor dtype
    load_in_4bit = True,
)

## --- PASO 1.1: Cargar el TOKENIZER original del modelo BASE ---
## Esta es la corrección clave. Ignoramos el tokenizer del checkpoint
## y cargamos el que sabemos que es 100% compatible con la arquitectura gemma3.
print("\nCargando el tokenizer original del modelo base para asegurar compatibilidad...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID) # MODEL_ID es "google/medgemma-4b-it"

# --- PASO 1.2: CONFIGURAR EL TOKENIZER PARA GENERACIÓN ---
# Es VITAL para evitar errores. Aunque lo recarguemos, debemos asegurarnos de esto.
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left" # Esencial para la generación

# ¡¡EL TRUCO PARA LA VELOCIDAD!!
# Fusiona los adaptadores LoRA en el modelo base.
# Esto crea un modelo denso en memoria que es órdenes de magnitud más rápido para la inferencia.
# Ya no es un PeftModel, es un modelo de Transformers normal pero con tu fine-tuning.
print("\nFusionando adaptadores LoRA para acelerar la inferencia...")
model.merge_and_unload()

# Ponemos el modelo en modo de evaluación
model.eval()
print("¡Modelo fusionado y listo para inferencia a máxima velocidad!")

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
Cargando el modelo y fusionando los adaptadores para máxima velocidad...
==((====))==  Unsloth 2025.11.3: Fast Gemma3 patching. Transformers: 4.57.1.
   \\   /|    NVIDIA L4. Num GPUs = 1. Max memory: 22.161 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.8.0+cu126. CUDA: 8.9. CUDA Toolkit: 12.6. Triton: 3.4.0
\        /    Bfloat16 = TRUE. FA [Xformers = None. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: Gemma3 does not support SDPA - switching to fast eager.

model.safetensors:   0%|          | 0.00/4.12G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/210 [00:00<?, ?B/s]

Cargando el tokenizer original del modelo base para asegurar compatibilidad...

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.69M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

chat_template.jinja:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

Fusionando adaptadores LoRA para acelerar la inferencia...

/usr/local/lib/python3.12/dist-packages/peft/tuners/lora/bnb.py:348: UserWarning: Merge lora module to 4-bit linear may get different generations due to rounding errors.
  warnings.warn(

¡Modelo fusionado y listo para inferencia a máxima velocidad!
CPU times: user 1min 29s, sys: 20.4 s, total: 1min 49s
Wall time: 2min 7s

In [ ]:
# Función para la generación de PLS (CORREGIDA)
def generate_summary_unsloth(model, tokenizer, technical_text):
    prompt = create_optimized_prompt(technical_text)
    inputs = tokenizer(prompt,
                       return_tensors="pt",
                       truncation=True,
                       max_length=max_seq_length
                       ).to("cuda")

    # Guardamos la longitud del input para poder separarlo del output después
    input_ids_length = inputs.input_ids.shape[1]

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=800,
            do_sample=True,
            top_p=0.9,
            temperature=0.3,
            # === CAMBIO CLAVE: CONDICIÓN DE PARADA SIMPLIFICADA ===
            # Ahora solo necesitamos el token oficial de fin de secuencia (EOS).
            # El fine-tuning le enseñará al modelo a generar este token al final.
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id
        )

    # === CAMBIO CLAVE: DECODIFICACIÓN LIMPIA ===
    # 1. Seleccionamos solo los tokens generados (los que van después del prompt inicial).
    generated_token_ids = outputs[0, input_ids_length:]
    # 2. Decodificamos únicamente esa parte.
    decoded_output = tokenizer.decode(generated_token_ids, skip_special_tokens=True)

    try:
        # Retornar TODO lo generado por el LLM para posterior limpieza y comparación
        return decoded_output.strip(), outputs
    except IndexError as e:
        print(f"Advertencia: No se pudo retornar la salida del LLM: {e}")
        return decoded_output.strip(), outputs # Devolver lo que se haya generado después de la instrucción
    except Exception as e:
        print(f"Error inesperado: {e}")
        return decoded_output.strip(), outputs # Devolver lo que se haya generado después de la instrucción

In [ ]:
%%time
import pandas as pd
import os
import textwrap
import re  # <--- IMPORTANTE: Importar regex

# ==============================================================================
# FUNCIÓN DE LIMPIEZA
# ==============================================================================
def clean_llm_response(text):
    # Agrega aquí nuevos patrones si el modelo alucina cosas nuevas
    stop_patterns = [
        r"\[/INST\]",
        r"\[INST\]",
        r"</plain-language-summary>",
        r"<plain-language-summary>",
        r"\[/SUMMARY\]",
        r"\[/DOCUMENT\]",
        r"\[/PLAIN_LANGUAGE_SUMMARY\]",
        r"\[PLAIN_LANGUAGE_SUMMARY\]",
    ]

    combined_pattern = "|".join(stop_patterns)
    match = re.search(combined_pattern, text, re.IGNORECASE)

    if match:
        return text[:match.start()].strip()
    return text.strip()

CPU times: user 8 µs, sys: 0 ns, total: 8 µs
Wall time: 12.4 µs

In [ ]:
%%time
# ==============================================================================
# PASO 3: EJECUCIÓN PRUEBA UNITARIA
# ==============================================================================
print("\n--- Ejecutando prueba unitaria con limpieza de patrones ---")

input_csv_path = os.path.join(BASE_PROJECT_DIR, 'evaluation_texts.csv')

try:
    df_eval = pd.read_csv(input_csv_path)
    random_sample = df_eval.iloc[50]
    technical_text_sample = random_sample['technical_text']
    reference_summary_sample = random_sample['reference_summary']

    # Generar resumen (Raw output)
    raw_summary, complete = generate_summary_unsloth(model, tokenizer, technical_text_sample)

    # --- APLICAR LIMPIEZA AQUÍ ---
    # Procesamos el texto crudo para quitar los artefactos y bucles
    final_summary_clean = clean_llm_response(raw_summary)

    # --- Visualización ---
    wrapper = textwrap.TextWrapper(width=80, initial_indent="    ", subsequent_indent="    ")

    print("\n\033[1m" + "1. TEXTO TÉCNICO ORIGINAL:" + "\033[0m")
    print(wrapper.fill(technical_text_sample))
    print("\n" + "="*50 + "\n")

    print("\033[1m" + "2. RESUMEN DE REFERENCIA (Humano):" + "\033[0m")
    print("\033[92m" + wrapper.fill(reference_summary_sample) + "\033[0m")
    print("\n" + "="*50 + "\n")

    print("\033[1m" + "3. RESUMEN GENERADO (Modelo Fine-Tuned + Regex Clean):" + "\033[0m")
    # Imprimimos la versión limpia
    print("\033[94m" + wrapper.fill(final_summary_clean) + "\033[0m")

except NameError as e:
    print(f"ERROR: {e}")
except Exception as e:
    print(f"Ocurrió un error inesperado: {e}")

--- Ejecutando prueba unitaria con limpieza de patrones ---

1. TEXTO TÉCNICO ORIGINAL:
    Background Community‐based primary‐level workers (PWs) are an important
    strategy for addressing gaps in mental health service delivery in low‐ and
    middle‐income countries.   Objectives To evaluate the effectiveness of
    PW‐led treatments for persons with mental health symptoms in LMICs, compared
    to usual care.   Search methods MEDLINE, Embase, CENTRAL,
    ClinicalTrials.gov, ICTRP, reference lists (to 20 June 2019).   Selection
    criteria Randomised trials of PW‐led or collaborative‐care interventions
    treating people with mental health symptoms or their carers in LMICs.   PWs
    included: primary health professionals (PHPs), lay health workers (LHWs),
    community non‐health professionals (CPs).   Data collection and analysis
    Seven conditions were identified apriori and analysed by disorder
    and PW examining recovery, prevalence, symptom change, quality‐of‐life
    (QOL), functioning, service use (SU), and adverse events (AEs).   Risk
    ratios (RRs) were used for dichotomous outcomes; mean difference (MDs),
    standardised mean differences (SMDs), or mean change differences (MCDs) for
    continuous outcomes.   For SMDs, 0.20 to 0.49 represented small, 0.50 to
    0.79 moderate, and ≥0.80 large clinical effects.   Analysis timepoints: T1
    (<1 month), T2 (1‐6 months), T3 ( >6 months) post‐intervention.  Main
    results Description of studies   95 trials (72 new since 2013) from 30 LMICs
    (25 trials from 13 LICs).  Risk of bias   Most common: detection bias,
    attrition bias (efficacy), insufficient protection against contamination.
    Intervention effects   *Unless indicated, comparisons were usual care
    at T2.  “Probably”, “may”, or “uncertain” indicates "moderate", "low," or
    "very low" certainty evidence.    Adults with common mental disorders (CMDs)
    LHW‐led interventions  a. may increase recovery (2 trials, 308 participants;
    RR 1.29, 95%CI 1.06 to 1.56); b. may reduce prevalence (2 trials, 479
    participants; RR 0.42, 95%CI 0.18 to 0.96); c. may reduce symptoms (4
    trials, 798 participants; SMD ‐0.59, 95%CI ‐1.01 to ‐0.16); d. may improve
    QOL (1 trial, 521 participants; SMD 0.51, 95%CI 0.34 to 0.69); e. may
    slightly reduce functional impairment (3 trials, 1399 participants; SMD
    ‐0.47, 95%CI ‐0.8 to ‐0.15);  f. may reduce AEs (risk of suicide
    ideation/attempts); g. may have uncertain effects on SU. Collaborative‐care
    a. may increase recovery (5 trials, 804 participants; RR 2.26, 95%CI 1.50 to
    3.43); b. may reduce prevalence although the actual effect range indicates
    it may have little‐or‐no effect (2 trials, 2820 participants; RR 0.57, 95%CI
    0.32 to 1.01);  c. may slightly reduce symptoms (6 trials, 4419
    participants; SMD ‐0.35, 95%CI ‐0.63 to ‐0.08);  d. may slightly improve QOL
    (6 trials, 2199 participants; SMD 0.34, 95%CI 0.16 to 0.53);  e. probably
    has little‐to‐no effect on functional impairment (5 trials, 4216
    participants; SMD ‐0.13, 95%CI ‐0.28 to 0.03);  f. may reduce SU (referral
    to MH specialists);  g. may have uncertain effects on AEs (death). Women
    with perinatal depression (PND)   LHW‐led interventions  a. may increase
    recovery (4 trials, 1243 participants; RR 1.29, 95%CI 1.08 to 1.54); b.
    probably slightly reduce symptoms (5 trials, 1989 participants; SMD ‐0.26,
    95%CI ‐0.37 to ‐0.14);  c. may slightly reduce functional impairment (4
    trials, 1856 participants; SMD ‐0.23, 95%CI ‐0.41 to ‐0.04);  d. may have
    little‐to‐no effect on AEs (death);  e. may have uncertain effects on SU.
    Collaborative‐care  a. has uncertain effects on symptoms/QOL/SU/AEs. Adults
    with post‐traumatic stress (PTS) or CMDs in humanitarian settings   LHW‐led
    interventions  a. may slightly reduce depression symptoms (5 trials, 1986
    participants; SMD ‐0.36, 95%CI ‐0.56 to ‐0.15);  b. probably slightly
    improve QOL (4 trials, 1918 participants; SMD ‐0.27, 95%CI ‐0.39 to ‐0.15);
    c. may have uncertain effects on symptoms (PTS)/functioning/SU/AEs. PHP‐led
    interventions  a. may reduce PTS symptom prevalence (1 trial, 313
    participants; RR 5.50, 95%CI 2.50 to 12.10) and depression prevalence (1
    trial, 313 participants; RR 4.60, 95%CI 2.10 to 10.08);   b. may have
    uncertain effects on symptoms/functioning/SU/AEs.   Adults with
    harmful/hazardous alcohol or substance use   LHW‐led interventions  a. may
    increase recovery from harmful/hazardous alcohol use although the actual
    effect range indicates it may have little‐or‐no effect (4 trials, 872
    participants; RR 1.28, 95%CI 0.94 to 1.74);  b. may have little‐to‐no effect
    on the prevalence of methamphetamine use (1 trial, 882 participants; RR
    1.01, 95%CI 0.91 to 1.13) and  functional impairment (2 trials, 498
    participants; SMD ‐0.14, 95%CI ‐0.32 to 0.03);  c. probably slightly reduce
    risk of harmful/hazardous alcohol use (3 trials, 667 participants; SMD
    ‐0.22, 95%CI ‐0.32 to ‐0.11);   d. may have uncertain effects on SU/AEs.
    PHP/CP‐led interventions  a. probably have little‐to‐no effect on recovery
    from harmful/hazardous alcohol use (3 trials, 1075 participants; RR 0.93,
    95%CI 0.77 to 1.12) or QOL (1 trial, 560 participants; MD 0.00, 95%CI ‐0.10
    to 0.10);  b. probably slightly reduce risk of harmful/hazardous alcohol and
    substance use (2 trials, 705 participants; SMD ‐0.20, 95%CI ‐0.35 to ‐0.05;
    moderate‐certainty evidence);  c. may have uncertain effects on prevalence
    (cannabis use)/SU/AEs. PW‐led interventions for alcohol/substance dependence
    a. may have uncertain effects.  Adults with severe mental disorders
    *Comparisons were specialist‐led care at T1. LHW‐led interventions  a. may
    have little‐to‐no effect on caregiver burden (1 trial, 253 participants; MD
    ‐0.04, 95%CI ‐0.18 to 0.11);   b. may have uncertain effects on
    symptoms/functioning/SU/AEs.  PHP‐led or collaborative‐care  a. may reduce
    functional impairment (7 trials, 874 participants; SMD ‐1.13, 95%CI ‐1.78 to
    ‐0.47);  b. may have uncertain effects on recovery/relapse/symptoms/QOL/SU.
    Adults with dementia and carers   PHP/LHW‐led carer interventions  a. may
    have little‐to‐no effect on the severity of behavioural symptoms in dementia
    patients (2 trials, 134 participants; SMD ‐0.26, 95%CI ‐0.60 to 0.08);  b.
    may reduce carers' mental distress (2 trials, 134 participants; SMD ‐0.47,
    95%CI ‐0.82 to ‐0.13);   c. may have uncertain effects on
    QOL/functioning/SU/AEs. Children with PTS or CMDs   LHW‐led interventions
    a. may have little‐to‐no effect on PTS symptoms (3 trials, 1090
    participants; MCD ‐1.34, 95%CI ‐2.83 to 0.14);  b.
    probably have little‐to‐no effect on depression symptoms (3 trials, 1092
    participants; MCD ‐0.61, 95%CI ‐1.23 to 0.02) or on functional impairment (3
    trials, 1092 participants; MCD ‐0.81, 95%CI ‐1.48 to ‐0.13);   c. may have
    little‐or‐no effect on AEs. CP‐led interventions  a. may have little‐to‐no
    effect on depression symptoms (2 trials, 602 participants; SMD ‐0.19, 95%CI
    ‐0.57 to 0.19) or on AEs;   b. may have uncertain effects on
    recovery/symptoms(PTS)/functioning. Authors' conclusions PW‐led
    interventions show promising benefits in improving outcomes for CMDs, PND,
    PTS, harmful alcohol/substance use, and dementia carers in LMICs.

==================================================

2. RESUMEN DE REFERENCIA (Humano):
    The effects of primary‐level workers on people with mental disorders and
    distress in low‐ and middle‐income countries  This Cochrane Review update
    aims to assess the effects of engaging community‐based workers, such as
    primary‐care workers and teachers, to help people with mental disorders or
    distress. The review focused on studies from low‐ and middle‐income
    countries and found 95 studies for inclusion (including 23 from the previous
    review).   Key messages  Primary health professionals, lay health workers,
    teachers, and other community workers may be able to help people with mental
    health issues if they are trained. However, more evidence is needed.   What
    was studied in the review?  In low‐ and middle‐income countries, many people
    with mental illness do not receive the care they need because of stigma and
    difficulty accessing services. One solution is to offer services through
    ‘primary‐level workers’. These are people who are not mental health
    specialists but who receive some mental health training, including primary
    health professionals (e.g. doctors, nurses); lay health workers; community
    volunteers; and other community members (e.g. teachers, social workers).
    Primary‐level workers deliver these services alone or in collaboration with
    specialists.  What are the main results of the review?  95 relevant trials
    from 30 low‐ or middle‐income countries were found.  The review authors
    searched for evidence about the effects of these strategies on the number of
    people who had mental health problems, the number who recovered, their
    symptom severity, quality of life, day‐to‐day functioning, use of health
    services, and negative effects of treatment. All results were measured one
    to six months after treatment completion, except in group 5, in which
    results were measured immediately after treatment completion. When results
    are not presented, this is because there was no evidence, or because the
    evidence was very uncertain. Evidence of the results below is of low to
    moderate certainty.  1. Adults with depression and anxiety  Treatments
    from lay health workers compared to usual care: a. may increase recovery; b.
    may reduce the number of people with depression/anxiety;  c. may
    improve quality of life; d. may slightly improve day‐to‐day functioning; and
    e. may reduce risk of suicidal thoughts/attempts. Treatments from
    primary‐level workers in collaboration with mental health specialists
    compared to usual care:  a. may increase recovery; b. may reduce the number
    of people with depression/anxiety although the range for the actual
    effect indicates they may have little or no effect;  c. may slightly
    reduce symptoms; d. may slightly improve quality of life; e. probably
    have little to no effect on day‐to‐day functioning; and f. may reduce
    referral to mental health specialists. 2. Women with depression related to
    pregnancy and childbirth  Treatments from lay health workers compared to
    usual care: a. may increase recovery; b. probably slightly reduce symptoms
    of depression; c. may slightly improve day‐to‐day functioning;  d. may have
    little to no effect on risk of death. 3. Adults in humanitarian settings
    with post‐traumatic stress or depression and anxiety  Treatments from lay
    health workers compared to usual care: a. may slightly reduce depression
    symptoms; and b. probably slightly improve quality of life. Treatments from
    primary health professionals compared to usual care: a. may reduce the
    number of adults with post‐traumatic stress and depression. 4. Adults with
    alcohol or substance use problems   Treatments from lay health workers
    compared to usual care: a. may increase recovery from harmful/hazardous
    alcohol use although the range for the actual effect indicates they may have
    little or no effect;  b. probably slightly reduce the risk of
    harmful/hazardous alcohol use; c. may have little to no effect on day‐to‐day
    functioning; and d. may have little to no effect on the number of people who
    use methamphetamine; Treatments from primary health and community
    professionals compared to usual care: a. probably have little to no effect
    on recovery from harmful/hazardous alcohol use; b. probably slightly reduce
    risk of harmful/hazardous alcohol and substance use; and c. probably
    have little to no effect on quality of life. 5. Adults with severe mental
    disorders (e.g. schizophrenia)  Treatments from lay health workers compared
    to mental specialists alone: a. may have little to no effect on caregiver
    burden. Treatments from primary health professionals alone or in
    collaboration with mental health specialists:  a. may improve day‐to‐day
    functioning. 6. Adults with dementia and their carers  Treatments from lay
    and professional health workers, compared to usual care: a. may have little
    to no effect on the severity of behavioural symptoms in dementia patients;
    and  b. may reduce carers' mental distress. 7. Children in humanitarian
    settings with post‐traumatic stress or depression and anxiety  Treatments
    from lay health workers, compared to usual or no care: a. may have little to
    no effect on post‐traumatic stress symptoms; b. probably have little to
    no effect on depressive symptoms nor on day‐to‐day functioning; and  c. may
    make little or no difference in risk of adverse events. Treatments from
    community professionals (teachers and social workers) compared to no care:
    a. may have little to no effect on depressive symptoms; and b. may make
    little or no difference in adverse events. How up‐to‐date is this review?
    Originally published in November 2013, this update includes
    studies published up to 20 June 2019.

==================================================

3. RESUMEN GENERADO (Modelo Fine-Tuned + Regex Clean):
    Community health workers (CHWs) are important for providing mental health
    services in low- and middle-income countries (LMICs). This study aimed to
    see if CHW-led treatments are better than usual care for people with mental
    health problems in these countries.         The researchers looked at 95
    studies from 30 LMICs. These studies involved CHWs, including primary health
    professionals (PHPs), lay health workers (LHWs), and community health
    workers (CPs). The studies focused on people with common mental disorders
    (CMDs), perinatal depression (PND), post-traumatic stress (PTS) or CMDs in
    humanitarian settings, harmful alcohol or substance use, and dementia and
    carers.         The studies compared CHW-led treatments to usual care. The
    researchers looked at several outcomes, including recovery, prevalence of
    mental health symptoms, quality of life (QOL), functioning, service use
    (SU), and adverse events (AEs).         The results showed that CHW-led
    interventions may be beneficial for some groups. For example, LHW-led
    interventions may increase recovery, reduce the prevalence of mental health
    symptoms, and improve QOL for people with CMDs. Collaborative-care
    interventions may increase recovery for adults with common mental disorders.
    The study also found that CHW-led interventions may be helpful for women
    with PND, reducing symptoms and improving functioning.         For adults
    with PTS or CMDs in humanitarian settings, LHW-led interventions may reduce
    depression symptoms and improve QOL.         The study also found that CHW-
    led interventions may be beneficial for people with harmful alcohol or
    substance use, potentially increasing recovery and reducing the risk of
    harmful alcohol use.         The researchers concluded that CHW-led
    interventions show promising benefits in improving outcomes for CMDs, PND,
    PTS, harmful alcohol/substance use, and dementia carers in LMICs.
CPU times: user 1min 51s, sys: 904 ms, total: 1min 52s
Wall time: 2min 22s

In [ ]:
# Analizando la salida completa vs la limpiada
decoded_output = tokenizer.decode(complete[0], skip_special_tokens=True)
decoded_output

'<s>[INST] You are a Health Literacy Expert.Your expertise is in rewriting complex, technical medical texts into clear, simple, and accurate language for a general audience, following established health communication guidelines.\n\n**[PRIMARY GOAL]**\n        Your main purpose is to rewrite the provided medical text into a Plain Language Summary (PLS).\n        This summary must be easy to understand for someone with an 8th-grade reading comprehension level typical of a general middle-school student,\n        consistent with plain-language standards used by CDC and NIH, meaning it should use simple vocabulary, short sentences,\n        and concepts that can be understood by someone with basic middle-school literacy,\n        while remaining completely faithful to the source\'s essential information, for intance, conclusions.\n\n        **[TASK INSTRUCTION]**\n        Rewrite the following technical medical text into a Plain Language Summary (PLS).\n        The output **MUST BE ONLY** the plain language summary without special symbols and stop tokens.\n\n        **--- STRICT OUTPUT RULES ---**\n\n        1.  **ACCURACY AND COMPLETENESS:**\n        *   The summary MUST retain all key findings, main outcomes, important safety information, conclusions,and any significant numerical results from the original text.\n        *   Do NOT add any information, opinions, or recommendations that are not present in the source document. The summary must be based ONLY on the provided text.\n\n        2.  **CLARITY AND READABILITY:**\n        *   Write the summary at an **8th-grade reading comprehension level typical of a general middle-school student**.\n        *   Use short, clear, and natural-sounding sentences.\n        *   Use the active voice whenever possible (e.g., "Scientists tested the drug" instead of "The drug was tested by scientists").\n        *   Avoid long, complex words when a simpler alternative exists.\n\n        3.  **TERMINOLOGY (JARGON):**\n        *   Avoid medical jargon.\n        *   If a technical term is absolutely essential and cannot be replaced, you MUST explain it simply in parentheses the first time it appears. (Example: "The trial used immunotherapy (a treatment that helps the body\'s immune system fight cancer).")\n\n        4.  **FORMATTING AND LANGUAGE:**\n        *   The output **MUST BE ONLY** the plain language summary without special symbols and stop tokens, **only the summary**.\n        *   The output must be written **ONLY in English**.\n        *   Structure the summary as a set of concise paragraphs. Use as many sentences as needed to include all essential information, up to a maximum length of about 500 words, however, **make sure ALL sentences are complete, which means ALL ideas are finished.**\n        *   Do NOT include headings, bullet points, lists, citations, or URLs.\n\n        **--- SOURCE TECHNICAL TEXT ---**\n        <document>\n        Background\nProstaglandins have been used for induction of labour since the 1960s. This is one of a series of reviews evaluating methods of induction of labour. This review focuses on prostaglandins given per vaginam, evaluating these in comparison with placebo (or expectant management) and with each other; prostaglandins (PGE2 and PGF2a); different formulations (gels, tablets, pessaries) and doses. \nObjectives\nTo determine the effects of vaginal prostaglandins E2 and F2a for third trimester cervical ripening or induction of labour in comparison with placebo/no treatment or other vaginal prostaglandins (except misoprostol). \nSearch methods\nWe searched the Cochrane Pregnancy and Childbirth Group\'s Trials Register (1 March 2014) and bibliographies of relevant papers. \nSelection criteria\nClinical trials comparing vaginal prostaglandins used for third trimester cervical ripening or labour induction with placebo/no treatment, with each other, or other methods listed above it on a predefined list of labour induction methods. \nData collection and analysis\nWe assessed studies and extracted data independently.\nMain results\nSeventy randomised controlled trials (RCTs) (11,487 women) are included. In this update seven new RCTs (778 women) have been added. Two of these new trials compare PGE2 with no treatment, four compare different PGE2 formulations (gels versus tablets, or sustained release pessaries) and one trial compares PGF2a with placebo. The majority of trials were at unclear risk of bias for most domains. \nOverall, vaginal prostaglandin E2 compared with placebo or no treatment probably reduces the likelihood of vaginal delivery not being achieved within 24 hours. The risk of uterine hyperstimulation with fetal heart rate changes is increased (4.8% versus 1.0%, risk ratio (RR) 3.16, 95% confidence interval (CI) 1.67 to 5.98, 15 trials, 1359 women). The caesarean section rate is probably reduced by about 10% (13.5% versus 14.8%, RR 0.91, 95% CI 0.81 to 1.02, 36 trials, 6599 women). The overall effect on improving maternal and fetal outcomes (across a variety of measures) is uncertain. \nPGE2 tablets, gels and pessaries (including sustained release preparations) appear to be as effective as each other, small differences are detected between some outcomes, but these maybe due to chance. \nAuthors\' conclusions\nProstaglandins PGE2 probably increase the chance of vaginal delivery in 24 hours, they increase uterine hyperstimulation with fetal heart changes but do not effect or may reduce caesarean section rates. They increase the likelihood of cervical change, with no increase in operative delivery rates. PGE2 tablets, gels and pessaries appear to be as effective as each other, any differences between formulations are marginal but may be important. \n\n        </document>\n\n        **--- PLAIN LANGUAGE SUMMARY (PLS) ---**\n       [/INST]\n       Vaginal prostaglandins, specifically PGE2 and PGF2a, are used to ripen the cervix (soften it) or induce labor in the third trimester of pregnancy. This review summarizes the evidence from studies comparing these prostaglandins to placebo (no treatment) or other methods of labor induction.\n\n       The review included 70 randomized controlled trials (RCTs) involving 11,487 women. Seven new trials were added since the last update. The studies compared vaginal prostaglandins (PGE2 and PGF2a) to placebo or no treatment, or to each other, using different formulations like gels, tablets, and pessaries.\n\n       Overall, vaginal prostaglandin E2 (PGE2) probably reduces the chance of not achieving vaginal delivery within 24 hours of starting the treatment. However, it also increases the risk of uterine hyperstimulation, which can cause changes in the baby\'s heart rate. The risk of a C-section (surgical delivery) is probably reduced by about 10%.\n\n       The review found that PGE2 tablets, gels, and pessaries (including sustained-release preparations) are likely as effective as each other. There are small differences in outcomes, but these may be due to chance.\n\n       In summary, vaginal prostaglandins PGE2 probably increase the likelihood of vaginal delivery within 24 hours, but they also increase the risk of uterine hyperstimulation. They do not appear to significantly affect the overall rate of C-sections.\n       [/INST]\n[/SUMMARY]\n[/INST]\n[/SUMMARY]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/INST]\n[/'

In [ ]:
# limpia gpu ram
import torch
torch.cuda.empty_cache()

## 5. Evaluación cuantitativa y preparación
Configura la evaluación, carga resultados previos, calcula métricas, prepara un entorno separado para AlignScore y genera scripts auxiliares.

In [ ]:
import torch
import pandas as pd
import os
import re
from tqdm.auto import tqdm

# ==============================================================================
# 1. CONFIGURACIÓN
# ==============================================================================
BATCH_SIZE = 12   # Ajusta según tu VRAM
MAX_SEQ_LEN = 4096 # Tu longitud máxima configurada en el modelo

# ==============================================================================
# 2. FUNCIONES AUXILIARES
# ==============================================================================

def clean_llm_response(text):
    """
    Limpia el texto asumiendo que recibe SOLO la respuesta generada (sin prompt).
    Corta en la primera señal de parada encontrada.
    """
    if not isinstance(text, str): return ""

    stop_patterns = [
        r"\[/INST\]", r"\[INST\]",
        r"</plain-language-summary>", r"<plain-language-summary>",
        r"\[/SUMMARY\]", r"\[/DOCUMENT\]",
        r"\[/PLAIN_LANGUAGE_SUMMARY\]", r"\[PLAIN_LANGUAGE_SUMMARY\]",
        r"<<",
    ]
    combined_pattern = "|".join(stop_patterns)
    match = re.search(combined_pattern, text, re.IGNORECASE)

    if match:
        return text[:match.start()].strip()

    return text.strip()

def generate_batch_debug(model, tokenizer, texts_batch):
    """
    Genera texto y separa matemáticamente el Prompt de la Respuesta usando tensores,
    evitando errores de string splitting.
    """
    prompts = [create_optimized_prompt(t) for t in texts_batch]

    # Tokenizamos con padding a la IZQUIERDA (vital para decoder-only models)
    inputs = tokenizer(
        prompts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=MAX_SEQ_LEN
    ).to("cuda")

    # Guardamos la longitud exacta de la entrada (incluyendo padding)
    input_length = inputs.input_ids.shape[1]

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=800,
            do_sample=True,
            top_p=0.9,
            temperature=0.3,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
            use_cache=True
        )

    # --- AQUÍ ESTÁ LA MAGIA DE LA SEPARACIÓN ---

    # 1. Full Text: Decodificamos todo el tensor (Prompt + Respuesta + Padding final si lo hubiera)
    full_texts = tokenizer.batch_decode(outputs, skip_special_tokens=False)

    # 2. Response Only: Cortamos el tensor para quedarnos SOLO con los tokens nuevos
    #    outputs[:, input_length:] toma todas las filas, desde la columna input_length hasta el final.
    generated_tokens = outputs[:, input_length:]
    raw_responses = tokenizer.batch_decode(generated_tokens, skip_special_tokens=False)

    return full_texts, raw_responses

# ==============================================================================
# 3. PROCESAMIENTO PRINCIPAL (MODO DEPURACIÓN)
# ==============================================================================

# Definir rutas
input_csv_path = os.path.join(BASE_PROJECT_DIR, 'evaluation_texts.csv')
output_csv_path = os.path.join(BASE_PROJECT_DIR, 'v8_debug_audit_summaries.csv')

try:
    df_eval = pd.read_csv(input_csv_path)
    # Tomamos 10 filas para la prueba rápida
    #df_to_process = df_eval.head(10).copy()
    df_to_process = df_eval.copy()
    print(f"Procesando {len(df_to_process)} filas de prueba...")
except FileNotFoundError:
    print("No se encontró el archivo CSV.")
    exit()

print(f"\n--- Iniciando generación DEBUG (Auditando {df_to_process.shape[0]} filas) ---")
print(f"\n--- Tamaño del batch: {BATCH_SIZE}")

# Listas para almacenar las 3 versiones
list_full_text_debug = []
list_raw_response_debug = []
list_clean_summary = []

technical_texts = df_to_process['technical_text'].tolist()

# --- BUCLE POR LOTES ---
for i in tqdm(range(0, len(technical_texts), BATCH_SIZE), desc="Auditando"):
    batch_texts = technical_texts[i : i + BATCH_SIZE]

    try:
        # Obtenemos Full Text y Raw Response separados por tokens, no por texto
        full_batch, raw_batch = generate_batch_debug(model, tokenizer, batch_texts)

        # Procesamos cada elemento del lote
        for full, raw in zip(full_batch, raw_batch):

            # 1. Guardar Full Text (con prompt y todo)
            list_full_text_debug.append(full)

            # 2. Guardar Raw Response (solo lo generado, sucio)
            list_raw_response_debug.append(raw)

            # 3. Limpiar y guardar Clean Summary
            clean = clean_llm_response(raw)
            list_clean_summary.append(clean)

    except RuntimeError as e:
        if "out of memory" in str(e).lower():
            print(f"\nERROR OOM en índice {i}. Reduce BATCH_SIZE.")
            torch.cuda.empty_cache()
            break
        else:
            print(f"Error: {e}")

# --- GUARDADO DEL CSV CON TODAS LAS COLUMNAS ---
limit = len(list_clean_summary)
df_final = df_to_process.iloc[:limit].copy()

# Agregamos las columnas en orden lógico de proceso
df_final['debug_full_text'] = list_full_text_debug       # El prompt + salida
df_final['debug_raw_response'] = list_raw_response_debug # Solo salida (sucia)
df_final['generated_summary'] = list_clean_summary       # Salida limpia final

df_final.to_csv(output_csv_path, index=False, encoding='utf-8')

print("\n--- Auditoría completada ---")
print(f"Archivo guardado en: {output_csv_path}")
print("Columnas generadas: ['debug_full_text', 'debug_raw_response', 'generated_summary']")

# Visualización rápida de un caso (si existe)
if len(df_final) > 0:
    print("\nEjemplo del primer registro (Raw Response vs Clean):")
    print("-" * 30)
    print("RAW (Sucio):")
    print(df_final.iloc[0]['debug_raw_response'][:200] + "...")
    print("-" * 30)
    print("CLEAN (Limpio):")
    print(df_final.iloc[0]['generated_summary'][:200] + "...")

--- Iniciando generación en lote (Batch Size: 12) ---
Total filas a procesar: 100

Procesando Lotes:   0%|          | 0/9 [00:00<?, ?it/s]

--- Proceso completado ---
Resultados guardados en: '/content/drive/MyDrive/NLP_Project_MedGemma/v8_generated_summaries_fast.csv'
                                   reference_summary  \
0  Non‐surgical treatment for spinal stenosis wit...
1  Interventions for involving older patients wit...
2  Beta‐blockers for children with congestive hea...
3  Removal of the spleen in people with thalassae...
4  One, two or three times a week iron supplement...

                                   generated_summary
0
1  Older adults with many health problems (like h...
2  The plain language summary is excellent. It ac...
3  The Plain Language Summary (PLS) is accurate, ...
4

In [ ]:
import pandas as pd
#from datasets import load_dataset, Dataset, DatasetDict
import evaluate
import os
import torch
import gc
import time
import pandas as pd
import numpy as np
# --- Para evaluación ---
from tqdm.auto import tqdm
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification # <<<--- NUEVA IMPORTACIÓN
import textstat
import spacy # <--- NUEVA IMPORTACIÓN

In [ ]:
# --- Celda 3: Cargar los Resultados Guardados desde CSV ---

# Definir la ruta al archivo
csv_path = os.path.join(BASE_PROJECT_DIR, 'v8_debug_audit_summaries.csv')

print(f"Cargando resultados pre-generados desde: {csv_path}")

try:
    results_df = pd.read_csv(csv_path)
    # For testing only 10
    #results_df = results_df.head(10)
except FileNotFoundError:
    print(f"ERROR: No se encontró el archivo en la ruta especificada. Asegúrate de que generaste el archivo CSV primero.")
    raise

# Limpiar datos por si acaso (eliminar filas donde la generación pudo haber fallado)
results_df.dropna(subset=['technical_text', 'reference_summary', 'generated_summary'], inplace=True)
results_df = results_df[results_df['generated_summary'].str.strip() != '']

# Extraer las listas necesarias para las métricas
clean_sources = results_df['technical_text'].tolist()
clean_references = results_df['reference_summary'].tolist()
clean_predictions = results_df['generated_summary'].tolist()

print(f"Cargados y listos para evaluar {len(clean_predictions)} resúmenes.")

Cargando resultados pre-generados desde: /content/drive/MyDrive/NLP_Project_MedGemma/qwen_pls.csv
Cargados y listos para evaluar 100 resúmenes.

In [ ]:
# <<<--- INICIO DE LA CORRECCIÓN --->>>
# Cargar el modelo de spaCy para la tokenización de oraciones
print("Cargando modelo de lenguaje de spaCy...")
nlp = spacy.load("en_core_web_sm")
# <<<--- FIN DE LA CORRECCIÓN --->>>

Cargando modelo de lenguaje de spaCy...

In [ ]:
# --- Celda 3 (Modificada): Cálculo Completo de Métricas (Modelo y Referencia) ---

# Asegurarse de tener el modelo de spacy cargado
try:
    nlp = spacy.load("en_core_web_sm")
except:
    import spacy.cli
    spacy.cli.download("en_core_web_sm")
    nlp = spacy.load("en_core_web_sm")

print("\n--- Calculando métricas finales (Modelo vs. Referencia) ---")
device = 0 if torch.cuda.is_available() else -1
device_str = "cuda" if torch.cuda.is_available() else "cpu"

# --- 1. Relevancia Semántica (BERTScore) ---
print("Calculando BERTScore...")
bertscore_metric = evaluate.load("bertscore")

# A. Para el Modelo (Generado vs Referencia)
print("-> BERTScore: Modelo...")
bertscore_results_gen = bertscore_metric.compute(
    predictions=clean_predictions,
    references=clean_references,
    lang="en", batch_size=16, device=device_str
)

# B. Para la Referencia (Referencia vs Referencia - Debería dar ~1.0)
print("-> BERTScore: Referencia (Sanity Check)...")
bertscore_results_ref = bertscore_metric.compute(
    predictions=clean_references,
    references=clean_references,
    lang="en", batch_size=16, device=device_str
)

# --- 2. Factualidad (Métrica NLI Invertida) ---
print("\nInicializando modelo NLI...")
nli_model_id = "facebook/bart-large-mnli"
nli_tokenizer = AutoTokenizer.from_pretrained(nli_model_id)
nli_model = AutoModelForSequenceClassification.from_pretrained(nli_model_id).to(device_str)
nli_model.eval()

# Función auxiliar para no repetir código NLI
def calculate_nli(sources_list, summaries_list, desc):
    scores = []
    with torch.no_grad():
        for source_doc, summary in tqdm(zip(sources_list, summaries_list), total=len(summaries_list), desc=desc):
            doc = nlp(summary)
            summary_sentences = [sent.text for sent in doc.sents]

            if not summary_sentences:
                scores.append(0.0)
                continue

            pairs = [[source_doc, sent] for sent in summary_sentences]

            inputs = nli_tokenizer(
                [p[0] for p in pairs], [p[1] for p in pairs],
                max_length=512, truncation=True, padding="longest", return_tensors='pt'
            ).to(device_str)

            outputs = nli_model(**inputs)
            probs = torch.softmax(outputs.logits, dim=1)
            # Index 0 = contradiction
            contradictions = (probs[:, 0] > 0.7).sum().item()
            scores.append(1.0 - (contradictions / len(summary_sentences)))
    return scores

# A. NLI para Modelo
factual_consistency_gen = calculate_nli(clean_sources, clean_predictions, "Factualidad NLI (Modelo)")
# B. NLI para Referencia
factual_consistency_ref = calculate_nli(clean_sources, clean_references, "Factualidad NLI (Referencia)")

# Liberar memoria NLI
del nli_model, nli_tokenizer
torch.cuda.empty_cache()

# --- 4. Factualidad (Métrica QA) ---
print("\nInicializando pipelines de QA...")
q_gen_pipe = pipeline("text2text-generation", model="valhalla/t5-base-qg-hl", device=device)
qa_pipe = pipeline("question-answering", model="distilbert-base-cased-distilled-squad", device=device)

# Función auxiliar para no repetir código QA
def calculate_qa(sources_list, summaries_list, desc):
    scores = []
    for source_doc, summary in tqdm(zip(sources_list, summaries_list), total=len(summaries_list), desc=desc):
        doc = nlp(summary)
        sentences = [sent.text for sent in doc.sents]

        if not sentences:
            scores.append(0.0)
            continue

        try:
            # 1. Generar preguntas
            q_outputs = q_gen_pipe(sentences, max_new_tokens=32, num_beams=2, batch_size=8)
            questions = [item['generated_text'] for item in q_outputs]

            # 2. Responder preguntas usando el TEXTO TÉCNICO como contexto
            qa_inputs = [{'question': q, 'context': source_doc} for q in questions]
            answers = qa_pipe(qa_inputs, batch_size=8)

            valid_answers = sum(1 for ans in answers if ans['score'] > 0.3)
            scores.append(valid_answers / len(sentences))
        except Exception as e:
            # print(f"Err: {e}")
            scores.append(0.0)
    return scores

# A. QA para Modelo
qa_fact_gen = calculate_qa(clean_sources, clean_predictions, "Factualidad QA (Modelo)")
# B. QA para Referencia
qa_fact_ref = calculate_qa(clean_sources, clean_references, "Factualidad QA (Referencia)")

# Liberar memoria QA
del q_gen_pipe, qa_pipe
torch.cuda.empty_cache()

# --- 5. Legibilidad ---
print("\nCalculando métricas de legibilidad...")

def get_readability_metrics(text_list, desc):
    results = {'fkgl': [], 'fre': [], 'gunning_fog': [], 'smog': [], 'coleman_liau': []}
    for text in tqdm(text_list, desc=desc):
        results['fkgl'].append(textstat.flesch_kincaid_grade(text))
        results['fre'].append(textstat.flesch_reading_ease(text))
        results['gunning_fog'].append(textstat.gunning_fog(text))
        results['smog'].append(textstat.smog_index(text))
        results['coleman_liau'].append(textstat.coleman_liau_index(text))
    return results

readability_generated = get_readability_metrics(clean_predictions, "Legibilidad (Modelo)")
readability_reference = get_readability_metrics(clean_references, "Legibilidad (Referencia)")

print("\n¡Cálculos finalizados con éxito!")

# --- 6. Construcción y Guardado de la Tabla Intermedia ---

data = {
    'Métrica': [
        'BERTScore - F1',
        'Factualidad (1 - Contradiction Ratio)',
        'Factualidad (QA Answerability)',
        '---',
        'Flesch-Kincaid Grade',
        'Flesch Reading Ease',
        'Gunning Fog Index',
        'SMOG Index',
        'Coleman-Liau Index',
    ],
    'Meta / Objetivo': ['≥ 0.86', '≥ 0.90', '≥ 0.80', '', '≤ 8.0', '≥ 60', '≤ 12.0', '≤ 8.0', '≤ 8.0'],
    'PLS Reales (Referencia)': [
        f"{np.mean(bertscore_results_ref['f1']):.4f}",   # AHORA CALCULADO
        f"{np.mean(factual_consistency_ref):.4f}",       # AHORA CALCULADO
        f"{np.mean(qa_fact_ref):.4f}",                   # AHORA CALCULADO
        '',
        f"{np.mean(readability_reference['fkgl']):.2f}",
        f"{np.mean(readability_reference['fre']):.2f}",
        f"{np.mean(readability_reference['gunning_fog']):.2f}",
        f"{np.mean(readability_reference['smog']):.2f}",
        f"{np.mean(readability_reference['coleman_liau']):.2f}",
    ],
    'PLS Generados (Modelo)': [
        f"{np.mean(bertscore_results_gen['f1']):.4f}",
        f"{np.mean(factual_consistency_gen):.4f}",
        f"{np.mean(qa_fact_gen):.4f}",
        '',
        f"{np.mean(readability_generated['fkgl']):.2f}",
        f"{np.mean(readability_generated['fre']):.2f}",
        f"{np.mean(readability_generated['gunning_fog']):.2f}",
        f"{np.mean(readability_generated['smog']):.2f}",
        f"{np.mean(readability_generated['coleman_liau']):.2f}",
    ]
}

results_table = pd.DataFrame(data)

# Guardamos con un nombre ESPECÍFICO para recuperarlo en el paso de unificación
PARTIAL_METRICS_PATH = os.path.join(BASE_PROJECT_DIR, 'v8_temp_standard_metrics.csv')
results_table.to_csv(PARTIAL_METRICS_PATH, index=False)

print("\n" + "="*80)
print("--- Tabla Comparativa de Resultados (Métricas Estándar) ---")
print("="*80)
print(results_table.to_string(index=False))
print("="*80)
print(f"Tabla guardada temporalmente en: {PARTIAL_METRICS_PATH}")

In [ ]:
# --- Celda 2.1: Instalar Python 3.10 ---
# Añadimos el repositorio PPA 'deadsnakes' que contiene versiones antiguas de Python
!sudo add-apt-repository -y ppa:deadsnakes/ppa
!sudo apt-get update -y

# Instalamos Python 3.10 y su módulo venv
!sudo apt-get install -qq python3.10 python3.10-venv -y

# Verificamos que se instaló correctamente
!python3.10 --version

In [ ]:
# --- Celda 2.2: Crear y Preparar el Entorno Virtual (VERSIÓN FINAL CORREGIDA) ---

# 1. Creamos un entorno virtual (esto no cambia)
!python3.10 -m venv /content/align_env

# 2. Instalamos PyTorch (esto no cambia)
!/content/align_env/bin/pip install -q torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117

# 3. ¡EL COMANDO CLAVE Y ÚNICO!
#    Instalamos AlignScore Y TODAS sus dependencias con las versiones correctas en un solo paso.
#    - transformers==4.33.2 (para el import AdamW)
#    - tokenizers==0.13.3 (compatible con transformers 4.33.2)
#    - pytorch-lightning==1.9.5 (la versión que AlignScore espera)
!/content/align_env/bin/pip install -q \
    pandas \
    transformers==4.33.2 \
    tokenizers==0.13.3 \
    pytorch-lightning==1.9.5 \
    "git+https://github.com/yuh-zha/AlignScore.git"

# --- Verificación ---
print("\n--- Verificando el entorno virtual ---")
!/content/align_env/bin/python --version
!/content/align_env/bin/python -c "import torch; print(f'PyTorch version: {torch.__version__}'); import transformers; print(f'Transformers version: {transformers.__version__}'); import alignscore; print('¡ÉXITO! AlignScore y sus dependencias se importaron correctamente.')"

In [ ]:
# --- Celda 2.3: Instalar AlignScore y Descargar el Modelo ---

# Usamos el pip que está DENTRO de nuestro entorno conda para instalar AlignScore
!/usr/local/envs/alignscore_env/bin/pip install -q pandas git+https://github.com/yuh-zha/AlignScore.git

# Clonar el repositorio para tener una estructura de carpetas predecible
!git clone https://github.com/yuh-zha/AlignScore.git

# Descargar el checkpoint del modelo en el directorio clonado
!cd /content/AlignScore/ && wget https://huggingface.co/yzha/AlignScore/resolve/main/AlignScore-base.ckpt

# Verificar que el archivo se descargó
!echo -e "\n--- Verificación de Archivos ---"
!ls -lh /content/AlignScore/

In [ ]:
# 4. ¡NUEVO PASO! Descargamos el modelo de spaCy USANDO el python del entorno virtual.
#    Esto asegura que el modelo sea visible para el script.
!/content/align_env/bin/python -m spacy download en_core_web_sm

# --- Verificación ---
print("\n--- Verificando el entorno virtual ---")
!/content/align_env/bin/python --version
# La verificación ahora también comprueba que spacy puede cargar el modelo.
!/content/align_env/bin/python -c "import torch; print(f'PyTorch version: {torch.__version__}'); import transformers; print(f'Transformers version: {transformers.__version__}'); import alignscore; import spacy; nlp=spacy.load('en_core_web_sm'); print('¡ÉXITO! Todas las dependencias, incluyendo spaCy, se importaron y cargaron correctamente.')"

In [ ]:
%%writefile run_alignscore_dual.py
import os
import pandas as pd
import numpy as np
import torch
from alignscore import AlignScore
import nltk
nltk.download('punkt_tab', quiet=True)

# --- Configuración ---
BASE_PROJECT_DIR = "/content/drive/MyDrive/NLP_Project_MedGemma"
BASE_ALIGNSCORE_DIR = "/content/AlignScore"
ALIGN_SCORE_CKPT_PATH = os.path.join(BASE_ALIGNSCORE_DIR, 'AlignScore-base.ckpt')

# IMPORTANTE: Usar el mismo CSV de entrada que usaste en la celda de métricas estándar
CSV_INPUT_PATH = os.path.join(BASE_PROJECT_DIR, 'v8_debug_audit_summaries.csv')
OUTPUT_SCORE_PATH = os.path.join(BASE_PROJECT_DIR, 'v8_temp_alignscore_results.csv')

print("--- Iniciando cálculo Dual de AlignScore ---")
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

try:
    # 1. Cargar Datos
    df = pd.read_csv(CSV_INPUT_PATH)

    # 2. Filtrar columnas requeridas
    required_cols = ['technical_text', 'reference_summary', 'generated_summary']
    for col in required_cols:
        if col not in df.columns:
            if col == 'generated_summary' and 'debug_raw_response' in df.columns:
                df['generated_summary'] = df['debug_raw_response']
            else:
                raise ValueError(f"Falta columna: {col}")

    df_clean = df.dropna(subset=required_cols)
    df_clean = df_clean[
        (df_clean['technical_text'].str.strip() != '') &
        (df_clean['generated_summary'].str.strip() != '')
    ]

    sources = df_clean['technical_text'].tolist()
    refs = df_clean['reference_summary'].tolist()
    gens = df_clean['generated_summary'].tolist()

    # 3. Cargar Modelo
    scorer = AlignScore(model='roberta-large', batch_size=32, device=DEVICE,
                        ckpt_path=ALIGN_SCORE_CKPT_PATH, evaluation_mode='nli_sp')

    # 4. Calcular
    print(f"Calculando AlignScore para {len(sources)} filas...")
    score_gen = np.mean(scorer.score(contexts=sources, claims=gens))
    score_ref = np.mean(scorer.score(contexts=sources, claims=refs))

    print(f"-> Gen: {score_gen:.4f} | Ref: {score_ref:.4f}")

    # 5. Guardar resultados
    pd.DataFrame([
        {'target_type': 'generated', 'score': score_gen},
        {'target_type': 'reference', 'score': score_ref}
    ]).to_csv(OUTPUT_SCORE_PATH, index=False)
    print("Guardado exitoso.")

except Exception as e:
    print(f"ERROR EN ALIGNSCORE: {e}")
    # Guardar ceros de seguridad
    pd.DataFrame([{'target_type': 'generated', 'score': 0}, {'target_type': 'reference', 'score': 0}]).to_csv(OUTPUT_SCORE_PATH, index=False)

Overwriting run_alignscore_dual.py

In [ ]:
import pandas as pd
import os

# Rutas de Archivos (Deben coincidir con los pasos anteriores)
#PARTIAL_METRICS_PATH = os.path.join(BASE_PROJECT_DIR, 'v8_temp_standard_metrics.csv')
#ALIGNSCORE_RES_PATH = os.path.join(BASE_PROJECT_DIR, 'v8_temp_alignscore_results.csv')
#FINAL_REPORT_PATH = os.path.join(BASE_PROJECT_DIR, 'v8_final_metrics_report.csv')

PARTIAL_METRICS_PATH = os.path.join(BASE_PROJECT_DIR, 'v8_temp_standard_metrics.csv')
ALIGNSCORE_RES_PATH = os.path.join(BASE_PROJECT_DIR, 'v8_temp_alignscore_results.csv')
FINAL_REPORT_PATH = os.path.join(BASE_PROJECT_DIR, 'v8_final_metrics_report.csv')

# --- 1. Ejecutar AlignScore ---
print("="*80)
print("Calculando AlignScore en entorno aislado...")
!/content/align_env/bin/python run_alignscore_dual.py
print("="*80)

# --- 2. Carga y Fusión Automática ---
try:
    # A. Cargar Tabla de Métricas Estándar
    df_main = pd.read_csv(PARTIAL_METRICS_PATH)

    # B. Cargar Resultado de AlignScore
    df_align = pd.read_csv(ALIGNSCORE_RES_PATH)
    as_gen = df_align.loc[df_align['target_type'] == 'generated', 'score'].values[0]
    as_ref = df_align.loc[df_align['target_type'] == 'reference', 'score'].values[0]

    # C. Crear la fila de AlignScore con el mismo formato que df_main
    # Obtenemos los nombres de columnas dinámicamente para evitar errores
    cols = df_main.columns.tolist()

    new_row = pd.DataFrame([{
        cols[0]: 'AlignScore (NLI_SP)',   # Columna 'Métrica'
        cols[1]: '≥ 0.80',                # Columna 'Meta / Objetivo'
        cols[2]: f"{as_ref:.4f}",         # Columna 'PLS Reales (Referencia)'
        cols[3]: f"{as_gen:.4f}"          # Columna 'PLS Generados (Modelo)'
    }])

    # D. Insertar la fila en la posición deseada (Después de BERTScore, índice 1)
    # Dividimos el dataframe y ponemos el sandwich en el medio
    df_final = pd.concat([df_main.iloc[:1], new_row, df_main.iloc[1:]]).reset_index(drop=True)

    # --- 3. Guardar e Imprimir ---
    df_final.to_csv(FINAL_REPORT_PATH, index=False)

    print("\n" + "="*105)
    print("--- Tabla Comparativa Final de Resultados (Unificada Automáticamente) ---")
    print("="*105)

    # Formateo dinámico para impresión limpia
    # Calculamos ancho máximo para alineación visual
    col_widths = [max(df_final[c].astype(str).map(len).max(), len(c)) + 2 for c in df_final.columns]
    header = "".join(f"{c:<{w}}" for c, w in zip(df_final.columns, col_widths))

    print(header)
    print("-" * len(header))

    for _, row in df_final.iterrows():
        if row[cols[0]] == '---':
            print("-" * len(header))
        else:
            print("".join(f"{str(row[c]):<{w}}" for c, w in zip(df_final.columns, col_widths)))

    print("="*105)
    print(f"Reporte final guardado en: {FINAL_REPORT_PATH}")

except FileNotFoundError as e:
    print(f"\nERROR CRÍTICO: Falta uno de los archivos intermedios. {e}")
except Exception as e:
    print(f"\nERROR INESPERADO: {e}")

In [ ]:
# =======================================================================
# FASE 5: EVALUACIÓN CUALITATIVA COMPARATIVA (Gemini vs. Llama) - CORREGIDO
# =======================================================================
#
# Este script modificado carga los resúmenes generados por Qwen y Gemma
# del archivo [pls_generated_qwen_gemma.csv].
#
# Utiliza dos modelos "jueces" (Gemini 1.5 Flash y Llama 3.1 8B Instruct)
# para realizar una evaluación cualitativa de AMBOS resúmenes generados.
#
# CORRECCIONES v2:
# 1.  Se cambió 'gemini-1.5-flash' por 'gemini-1.5-flash-lite' para
#     solucionar el error 404 de la API de Google.
# 2.  Se cambió `llama_client.chat.completions(...)` por
#     `llama_client.chat.completions.create(...)` para solucionar
#     el error "Not Callable" de la API de Hugging Face.
#
# =======================================================================

# --- Paso 1: Instalación y Configuración ---

# Instalar bibliotecas de cliente
!pip install -q google-generativeai huggingface_hub

print("Instalando e importando librerías...")
import google.generativeai as genai
from huggingface_hub import HfApi, InferenceClient, login
from google.colab import userdata
import pandas as pd
import os
import json
import re  # Importar regex para la extracción de JSON de Llama
import time
from tqdm.auto import tqdm

# Aplicar tqdm a las operaciones de pandas
tqdm.pandas(desc="Procesando filas")

Instalando e importando librerías...

In [ ]:
# Celda 4: Montar Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## 6. Evaluación cualitativa y profiling
Define claves y rutas para Gemini, inicializa funciones de evaluación, instala y ejecuta ydata-profiling para revisar resultados cualitativos.

In [ ]:
# --- Configuración de API Key de Google (Gemini) ---
print("Configurando la API Key de Gemini...")
try:
    API_KEY_GOOGLE = userdata.get('GOOGLE_API_KEY')
    genai.configure(api_key=API_KEY_GOOGLE)
    print("API Key de Google (Gemini) configurada exitosamente.")
except Exception as e:
    print(f"Error al configurar la API Key de Google: {e}")
    print("Por favor, asegúrate de que 'GOOGLE_API_KEY' esté guardada en los 'Secrets' de Colab (icono de la llave).")
    raise

# --- Configuración de API Key de Hugging Face ---
print("Configurando la API Key de HuggingFace...")
try:
    API_KEY_HF = userdata.get('HUGGING_API_KEY')
    login(token=API_KEY_HF)
    print("API Key de HuggingFace configurada exitosamente.")
except Exception as e:
    print(f"Error al configurar la API Key de Hugging Face: {e}")
    print("Por favor, asegúrate de que 'HUGGING_API_KEY' esté guardada en los 'Secrets' de Colab (icono de la llave).")
    raise

Configurando la API Key de Gemini...
API Key de Google (Gemini) configurada exitosamente.
Configurando la API Key de HuggingFace...
API Key de HuggingFace configurada exitosamente.

In [ ]:
# --- Paso 2: Definiciones de Rutas y Carga de Datos ---

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# IMPORTANTE: Asegúrate de que la variable BASE_PROJECT_DIR esté definida
# en una celda anterior, como en tu script original.
# Ejemplo:
# BASE_PROJECT_DIR = '/content/drive/MyDrive/TuProyecto'
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
BASE_PROJECT_DIR = "/content/drive/MyDrive/NLP_Project_MedGemma"

if 'BASE_PROJECT_DIR' not in locals():
    print("ADVERTENCIA: La variable 'BASE_PROJECT_DIR' no está definida.")
    print("Definiéndola como '/content/' por defecto. Edita esto si es necesario.")
    BASE_PROJECT_DIR = '/content/'

# **MODIFICADO**: Ruta al nuevo archivo CSV de entrada
csv_path = os.path.join(BASE_PROJECT_DIR, 'v7_debug_audit_summaries.csv')

# **MODIFICADO**: Rutas para los DOS nuevos archivos CSV de salida
output_csv_gemini_path = os.path.join(BASE_PROJECT_DIR, 'v7_gemini_qualitative_eval.csv')

print(f"Cargando datos desde: {csv_path}")
try:
    df = pd.read_csv(csv_path)
except FileNotFoundError:
    print(f"ERROR: No se encontró el archivo en la ruta: {csv_path}")
    print(f"Asegúrate de que el archivo {csv_path} esté en el lugar correcto.")
    raise

# **MODIFICADO**: Limpieza básica para las nuevas columnas
columns_to_check = ['technical_text', 'reference_summary', 'generated_summary', 'debug_raw_response']
df.dropna(subset=columns_to_check, inplace=True)
df = df[df['generated_summary'].str.strip() != '']
df = df[df['debug_raw_response'].str.strip() != '']

print(f"Cargados {len(df)} ejemplos para la evaluación cualitativa.")

Cargando datos desde: /content/drive/MyDrive/NLP_Project_MedGemma/v7_debug_audit_summaries.csv
Cargados 100 ejemplos para la evaluación cualitativa.

In [ ]:
# --- Paso 3: Diseño del Prompt de Evaluación y Plantilla JSON ---

PROMPT_DE_EVALUACION = """
Eres un evaluador experto en lingüística y comunicación de la ciencia.
Tu tarea es evaluar un "Resumen Generado" (Plain Language Summary - PLS).

**Contexto del Proyecto:**
El objetivo es crear un resumen con un nivel de lectura de 8.º grado (meta: Flesch-Kincaid Grade <= 8.0) que sea factualmente preciso y no omita información crítica.

Tu misión es analizar por qué el resumen generado podría fallar o tener éxito.

**Textos para Evaluación:**

1.  **Texto Técnico (Fuente):**
    ```
    {technical_text}
    ```

2.  **Resumen de Referencia (PLS Humano):**
    ```
    {reference_summary}
    ```

3.  **Resumen Generado (PLS del Modelo a Evaluar):**
    ```
    {summary_to_evaluate}
    ```

**Tareas de Evaluación:**
Basado en los textos, evalúa el "Resumen Generado" (PLS del Modelo a Evaluar) y responde ÚNICAMENTE con un objeto JSON válido que siga esta estructura:

{{
  "legibilidad_cumple_meta_8vo_grado": false,
  "analisis_legibilidad": "El texto sigue usando jerga técnica como 'XYZ' y la estructura de las frases es compleja. Nivel estimado: Grado 11.",
  "es_factualmente_consistente": true,
  "factual_completitud_cumple_meta": false,
  "analisis_factual": "El resumen es correcto, pero omite la conclusión principal del estudio (el resultado X). Es demasiado vago.",
  "tiene_errores_gramaticales": false,
  "tiene_errores_ortograficos": false,
  "es_coherente": true,
  "tiene_repeticiones": false,
  "tiene_frases_incompletas": false,
  "resumen_evaluacion_general": "El resumen generado simplifica el lenguaje pero pierde el punto central del texto técnico, haciéndolo inútil para entender los resultados clave."
}}

**Instrucciones del JSON:**
* Usa `true` o `false` para los campos booleanos.
* Proporciona tu análisis experto en las cadenas de texto (`analisis_legibilidad`, `analisis_factual`, `resumen_evaluacion_general`).
* `analisis_factual`: Enfócate en si es vago u omite información clave.
* `analisis_legibilidad`: Enfócate en por qué fallaría la meta de 8.º grado.
* **Responde SÓLO con el objeto JSON, nada más.**
"""

# Estructura JSON esperada para manejo de errores
EXPECTED_JSON_STRUCTURE = {
  "legibilidad_cumple_meta_8vo_grado": None,
  "analisis_legibilidad": "ERROR: No se pudo generar la evaluación.",
  "es_factualmente_consistente": None,
  "factual_completitud_cumple_meta": None,
  "analisis_factual": "ERROR: No se pudo generar la evaluación.",
  "tiene_errores_gramaticales": None,
  "tiene_errores_ortograficos": None,
  "es_coherente": None,
  "tiene_repeticiones": None,
  "tiene_frases_incompletas": None,
  "resumen_evaluacion_general": "ERROR: La llamada a la API falló."
}

In [ ]:
# --- Paso 4: Inicialización de Modelos y Funciones de Evaluación ---

# --- Modelo 1: Gemini ---
print("Inicializando modelo Gemini...")
# **CORRECCIÓN 1**: Se usa 'gemini-1.5-flash-latest' para evitar el error 404
gemini_model = genai.GenerativeModel('gemini-2.5-flash-lite')

# --- Funciones de Utilidad ---

def get_error_response(error_message):
    """Devuelve un diccionario de error con la estructura JSON esperada."""
    error_json = EXPECTED_JSON_STRUCTURE.copy()
    error_json["resumen_evaluacion_general"] = f"ERROR: {error_message}"
    return error_json

def extract_json_from_text(text):
    """
    Extrae el primer objeto JSON válido de una cadena de texto,
    incluso si está rodeado de texto o markdown.
    """
    # Buscar el primer '{' y el último '}' para capturar el JSON
    match = re.search(r'\{.*\}', text, re.DOTALL)
    if not match:
        # Si no encuentra JSON, buscar la palabra "ERROR" para propagar fallos
        if "error" in text.lower():
             raise ValueError(f"Respuesta de Llama contenía un error: {text}")
        raise ValueError("No se encontró un objeto JSON en la respuesta de Llama.")

    json_string = match.group(0)
    return json.loads(json_string)

# --- Funciones de Evaluación Principales ---

def evaluate_with_gemini(row, summary_column_name):
    """
    Llama a la API de Gemini para evaluar un resumen específico
    (dado por summary_column_name).
    """
    try:
        # 1. Construir el prompt
        prompt = PROMPT_DE_EVALUACION.format(
            technical_text=row['technical_text'],
            reference_summary=row['reference_summary'],
            summary_to_evaluate=row[summary_column_name] # Usa la columna pasada
        )

        # 2. Configurar el modelo para que devuelva JSON
        generation_config = genai.types.GenerationConfig(
            response_mime_type="application/json"
        )

        # 3. Llamar a la API
        response = gemini_model.generate_content(prompt, generation_config=generation_config)

        # 4. Parsear la respuesta JSON
        result_json = json.loads(response.text)

        # 5. Validar claves
        for key in EXPECTED_JSON_STRUCTURE.keys():
            if key not in result_json:
                raise ValueError(f"La respuesta JSON de Gemini no contenía la clave: '{key}'")

        return result_json

    except Exception as e:
        print(f"Error procesando (Gemini) fila {row.name}, col {summary_column_name}: {str(e)}")
        return get_error_response(f"Gemini API Error: {str(e)}")

Inicializando modelo Gemini...

In [ ]:
import time
import random
import pandas as pd
from tqdm import tqdm

# --- Configuración de Robustez ---
MAX_RETRIES = 3          # Cuántas veces reintentar si falla
INITIAL_BACKOFF = 2      # Segundos iniciales de espera tras error
GEMINI_API_DELAY = 4.1   # Tu delay estándar para Rate Limits (RPM)
SAVE_EVERY_N_ROWS = 5    # Guardar respaldo cada 5 filas (Checkpoint)
OUTPUT_FILENAME = os.path.join(BASE_PROJECT_DIR, 'partial_v7_gemini_qualitative_eval.csv')

# Claves que SIEMPRE deben existir en la respuesta JSON (basado en tu error)
REQUIRED_KEYS = ['tiene_errores_ortograficos']
# (Agrega aquí otras claves críticas que esperas, ej: 'puntaje', 'razonamiento')

# --- Función Wrapper para Reintentos ---
def safe_evaluate_with_retry(row, col_name, retries=MAX_RETRIES):
    """
    Intenta llamar a evaluate_with_gemini con reintentos y validación de JSON.
    """
    attempt = 0
    last_exception = None

    while attempt < retries:
        try:
            # 1. Intentar llamada
            response_json = evaluate_with_gemini(row, col_name)

            # 2. Validar si el resultado es un diccionario válido
            if not isinstance(response_json, dict):
                raise ValueError(f"La respuesta no es un dict JSON válido: {type(response_json)}")

            # 3. Validar que contenga las claves críticas (tu error específico)
            missing_keys = [k for k in REQUIRED_KEYS if k not in response_json]
            if missing_keys:
                raise KeyError(f"Faltan claves en JSON: {missing_keys}")

            # Si todo sale bien, retornamos el JSON limpio
            return response_json, None # (resultado, error)

        except Exception as e:
            attempt += 1
            last_exception = e

            # Calcular tiempo de espera con un poco de 'jitter' (variación aleatoria)
            # para evitar colisiones si corrieras hilos paralelos.
            sleep_time = (INITIAL_BACKOFF * (2 ** (attempt - 1))) + random.uniform(0, 1)

            print(f" > Error en intento {attempt}/{retries} para {col_name}: {e}")
            print(f" > Reintentando en {sleep_time:.2f}s...")
            time.sleep(sleep_time)

    # Si agotamos los intentos, devolvemos un diccionario de error y la excepción
    error_result = {k: "ERROR_API" for k in REQUIRED_KEYS}
    error_result['error_detail'] = str(last_exception)
    return error_result, last_exception


# --- Paso 5: Ejecución del Bucle (Mejorado) ---

print("\n" + "="*80)
print(f"Iniciando evaluación ROBUSTA de {len(df)} filas con Gemini...")
print(f"Retardo base: {GEMINI_API_DELAY}s | Reintentos máx: {MAX_RETRIES}")
print("="*80)

gemini_results_data = []

# Iterar sobre el DataFrame
for index, row in tqdm(df.iterrows(), total=df.shape[0], desc="Evaluando filas"):

    base_data = row.to_dict()
    row_errors = False # Bandera para saber si hubo error grave en esta fila

    # --- A: Evaluar 'generated_summary' ---
    # Usamos la función wrapper en lugar de llamar directo
    generated_summary_json, err_gen_summ = safe_evaluate_with_retry(row, 'generated_summary')

    # Construimos el objeto incluso si hubo error (para no perder la fila)
    gemini_row_generated_summary = {
        **base_data,
        **generated_summary_json,
        'evaluated_summary_model': 'generated_summary',
        'api_status': 'failed' if err_gen_summ else 'success'
    }
    gemini_results_data.append(gemini_row_generated_summary)

    # Respetar límite de velocidad API (solo si fue exitoso, si falló ya esperamos bastante)
    if not err_gen_summ:
        time.sleep(GEMINI_API_DELAY)

    # --- B: Evaluar 'pls_qwen' ---
    debug_raw_response_json, err_deb_rawres = safe_evaluate_with_retry(row, 'debug_raw_response')

    gemini_row_deb_rawres = {
        **base_data,
        **debug_raw_response_json,
        'evaluated_summary_model': 'debug_raw_response',
        'api_status': 'failed' if err_deb_rawres else 'success'
    }
    gemini_results_data.append(gemini_row_deb_rawres)

    if not err_deb_rawres:
        time.sleep(GEMINI_API_DELAY)

    # --- C: Guardado Intermedio (Checkpoint) ---
    # Esto salva la vida si se va la luz o crashea el kernel
    if (index + 1) % SAVE_EVERY_N_ROWS == 0:
        temp_df = pd.DataFrame(gemini_results_data)
        temp_df.to_csv(OUTPUT_FILENAME, index=False)
        # Opcional: print(f"Checkpoint guardado en fila {index}")

# --- Guardado Final ---
print("\nEvaluación completada. Consolidando resultados finales...")
final_df = pd.DataFrame(gemini_results_data)

# Verificar si hubo fallos
failed_count = final_df[final_df['api_status'] == 'failed'].shape[0]
if failed_count > 0:
    print(f"⚠️ ATENCIÓN: Hubo {failed_count} evaluaciones fallidas que agotaron los reintentos.")
    print("Revisa la columna 'error_detail' en el CSV resultante.")
else:
    print("✅ Éxito total: Todas las filas procesadas sin errores persistentes.")

# Guardar
final_df.to_csv(output_csv_gemini_path, index=False)
print(f"Resultados guardados en: {output_csv_gemini_path}")

================================================================================
Iniciando evaluación ROBUSTA de 100 filas con Gemini...
Retardo base: 4.1s | Reintentos máx: 3
================================================================================

Evaluando filas:  91%|█████████ | 91/100 [20:23<01:55, 12.82s/it]

Error procesando (Gemini) fila 91, col generated_summary: La respuesta JSON de Gemini no contenía la clave: 'tiene_errores_ortograficos'

Evaluando filas: 100%|██████████| 100/100 [22:17<00:00, 13.38s/it]

Evaluación completada. Consolidando resultados finales...
✅ Éxito total: Todas las filas procesadas sin errores persistentes.
Resultados guardados en: /content/drive/MyDrive/NLP_Project_MedGemma/v7_gemini_qualitative_eval.csv

In [ ]:
!pip install -q ydata-profiling

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 399.3/399.3 kB 24.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 18.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 26.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 13.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.3/37.3 MB 15.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 1.0 MB/s eta 0:00:00

In [ ]:
# Conectarse a Drive
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
import pandas as pd
import os
BASE_PROJECT_DIR = "/content/drive/MyDrive/NLP_Project_MedGemma"
# Construct the full path to the CSV file
csv_path = os.path.join(BASE_PROJECT_DIR, 'v8_gemini_qualitative_eval.csv')

print(f"Loading data from: {csv_path}")

# Load the CSV file into a pandas DataFrame
df_eval = pd.read_csv(csv_path)
# Filtering by evaluated_summary_model = 'pls_gemma'
df_eval = df_eval[df_eval['evaluated_summary_model'] == 'generated_summary']
# Droping columns technical_text, reference_summary, pls_gemma, and pls_qwen
df_eval = df_eval.drop(columns=['technical_text', 'reference_summary', 'generated_summary', 'debug_full_text', 'debug_raw_response', 'evaluated_summary_model', 'api_status'])

# Display the first few rows of the DataFrame
print("\nFirst 5 rows of the loaded DataFrame:")
display(df_eval.head())

# Print the shape of the DataFrame
print("\nShape of the loaded DataFrame:")
print(df_eval.shape)

Loading data from: /content/drive/MyDrive/NLP_Project_MedGemma/v8_gemini_qualitative_eval.csv

First 5 rows of the loaded DataFrame:

,legibilidad_cumple_meta_8vo_grado,analisis_legibilidad,es_factualmente_consistente,factual_completitud_cumple_meta,analisis_factual,tiene_errores_gramaticales,tiene_errores_ortograficos,es_coherente,tiene_repeticiones,tiene_frases_incompletas,resumen_evaluacion_general
0,False,El resumen utiliza lenguaje técnico y concepto...,True,False,"Aunque el resumen es factualmente consistente,...",False,False,True,False,False,El resumen generado logra simplificar parte de...
2,False,El resumen utiliza lenguaje relativamente acce...,True,False,El resumen generado omite la conclusión princi...,False,False,True,True,False,El resumen intenta simplificar el lenguaje per...
4,False,El resumen generado utiliza términos técnicos ...,True,False,El resumen omite la matizada conclusión de que...,False,False,True,False,False,El resumen generado es factualmente consistent...
6,False,El resumen utiliza un lenguaje relativamente s...,True,False,El resumen es factualmente correcto en lo que ...,False,False,True,False,False,El resumen generado intenta simplificar el len...
8,False,El resumen usa frases relativamente cortas y u...,True,False,El resumen omite la comparación directa de la ...,False,False,True,False,False,El resumen genera una comprensión básica de qu...

Shape of the loaded DataFrame:
(100, 11)

In [ ]:
from ydata_profiling import ProfileReport

# Create a ProfileReport object
profile = ProfileReport(df_eval, title="Qualitative Evaluation Data Profiling Report")

In [ ]:
# Save the report as an HTML file
report_path = os.path.join(BASE_PROJECT_DIR, "v8_qualitative_gemini_gemma_eval_report.html")
profile.to_file(report_path)

print(f"Profiling report saved to: {report_path}")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/11 [00:00<?, ?it/s]
100%|██████████| 11/11 [00:00<00:00, 92.14it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Profiling report saved to: /content/drive/MyDrive/NLP_Project_MedGemma/v8_qualitative_gemini_gemma_eval_report.html

In [ ]:
from IPython.display import HTML

# Construct the full path to the saved HTML report file
report_path = os.path.join(BASE_PROJECT_DIR, "v8_qualitative_gemini_gemma_eval_report.html")

# Open and read the content of the HTML file
with open(report_path, 'r', encoding='utf-8') as f:
    html_content = f.read()

# Display the HTML content directly in the notebook
display(HTML(html_content))

## 7. Generación con modelos fundacionales
Monta Drive, define prompts de generación, ejecuta bucles de inferencia y guarda resultados con dependencias mínimas.

In [ ]:
# =======================================================================
# FASE 6: GENERACIÓN DE PLS CON MODELOS FUNDACIONALES (CON REINTENTOS)
# =======================================================================
#
# Este script carga el texto técnico de origen y utiliza los modelos
# fundacionales (Gemini 1.5 Flash y Llama 3.1 8B Instruct) para
# generar nuevos "Plain Language Summaries" (PLS).
#
# =======================================================================
# NOVEDAD (v2):
# Se han modificado las funciones `generate_pls_with_gemini` y
# `generate_pls_with_llama` para incluir un bucle de reintentos
# automático (hasta 3 intentos) con espera (backoff) en caso de
# cualquier error de API (timeout, 500, etc.) o error de validación.
# Esto asegura una mayor robustez y reduce la necesidad de
# intervenciones manuales.
# =======================================================================

# --- Paso 1: Instalación y Configuración ---

# Instalar bibliotecas de cliente
!pip install -q google-generativeai huggingface_hub

print("Instalando e importando librerías...")
import google.generativeai as genai
from huggingface_hub import HfApi, InferenceClient, login
from google.colab import userdata
import pandas as pd
import os
import json
import time
from tqdm.auto import tqdm

# Aplicar tqdm a las operaciones de pandas
tqdm.pandas(desc="Procesando filas")

Instalando e importando librerías...

In [ ]:
# --- Configuración de API Key de Google (Gemini) ---
print("Configurando la API Key de Gemini...")
try:
    API_KEY_GOOGLE = userdata.get('GOOGLE_API_KEY')
    genai.configure(api_key=API_KEY_GOOGLE)
    print("API Key de Google (Gemini) configurada exitosamente.")
except Exception as e:
    print(f"Error al configurar la API Key de Google: {e}")
    print("Asegúrate de que 'GOOGLE_API_KEY' esté guardada en los 'Secrets'.")
    raise

# --- Configuración de API Key de Hugging Face (Llama) ---
print("Configurando la API Key de HuggingFace...")
try:
    API_KEY_HF = userdata.get('HUGGING_API_KEY')
    login(token=API_KEY_HF)
    print("API Key de HuggingFace (Llama) configurada exitosamente.")
except Exception as e:
    print(f"Error al configurar la API Key de Hugging Face: {e}")
    print("Asegúrate de que 'HUGGING_API_KEY' esté guardada en los 'Secrets'.")
    raise

Configurando la API Key de Gemini...
API Key de Google (Gemini) configurada exitosamente.
Configurando la API Key de HuggingFace...
API Key de HuggingFace (Llama) configurada exitosamente.

In [ ]:
# Celda 4: Montar Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# --- Paso 2: Definiciones de Rutas y Carga de Datos ---

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# IMPORTANTE: Asegúrate de que la variable BASE_PROJECT_DIR esté definida
# en una celda anterior.
# Ejemplo:
# BASE_PROJECT_DIR = '/content/drive/MyDrive/TuProyecto'
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

BASE_PROJECT_DIR = "/content/drive/MyDrive/NLP_Project_MedGemma"

if 'BASE_PROJECT_DIR' not in locals():
    print("ADVERTENCIA: La variable 'BASE_PROJECT_DIR' no está definida.")
    print("Definiéndola como '/content/' por defecto. Edita esto si es necesario.")
    BASE_PROJECT_DIR = '/content/'

# Ruta al archivo CSV de entrada (el mismo de la Fase 5)
csv_path_input = os.path.join(BASE_PROJECT_DIR, 'v8_debug_audit_summaries.csv')

# Ruta para el NUEVO archivo CSV de salida
csv_path_output = os.path.join(BASE_PROJECT_DIR, 'v8_foundation_model_pls_results.csv')

print(f"Cargando datos desde: {csv_path_input}")
try:
    df = pd.read_csv(csv_path_input)
except FileNotFoundError:
    print(f"ERROR: No se encontró el archivo en la ruta: {csv_path_input}")
    raise

# Limpieza: Solo necesitamos textos técnicos que no estén vacíos
df.dropna(subset=['technical_text', 'reference_summary'], inplace=True)
df = df[df['technical_text'].str.strip() != '']

# Tomamos solo las columnas que nos interesan para el nuevo archivo
df = df[['technical_text', 'reference_summary', 'generated_summary']].drop_duplicates().reset_index(drop=True)

print(f"Cargados {len(df)} textos técnicos únicos para generar PLS.")

Cargando datos desde: /content/drive/MyDrive/NLP_Project_MedGemma/v8_debug_audit_summaries.csv
Cargados 100 textos técnicos únicos para generar PLS.

In [ ]:
# --- Paso 3: Definición del Prompt de Generación ---

SYSTEM_PROMPT = (
        "You are a Health Literacy Expert."
        "Your expertise is in rewriting complex, technical medical texts into clear, simple, and accurate language for a general audience, following established health communication guidelines."
)

INSTRUCTION_TEMPLATE = """**[PRIMARY GOAL]**
        Your main purpose is to rewrite the provided medical text into a Plain Language Summary (PLS).
        This summary must be easy to understand for someone with an 8th-grade reading comprehension level typical of a general middle-school student,
        consistent with plain-language standards used by CDC and NIH, meaning it should use simple vocabulary, short sentences,
        and concepts that can be understood by someone with basic middle-school literacy,
        while remaining completely faithful to the source's essential information, for intance, conclusions.

        **[TASK INSTRUCTION]**
        Rewrite the following technical medical text into a Plain Language Summary (PLS).
        The output **MUST BE ONLY** the plain language summary without special symbols and stop tokens.

        **--- STRICT OUTPUT RULES ---**

        1.  **ACCURACY AND COMPLETENESS:**
        *   The summary MUST retain all key findings, main outcomes, important safety information, conclusions,and any significant numerical results from the original text.
        *   Do NOT add any information, opinions, or recommendations that are not present in the source document. The summary must be based ONLY on the provided text.

        2.  **CLARITY AND READABILITY:**
        *   Write the summary at an **8th-grade reading comprehension level typical of a general middle-school student**.
        *   Use short, clear, and natural-sounding sentences.
        *   Use the active voice whenever possible (e.g., "Scientists tested the drug" instead of "The drug was tested by scientists").
        *   Avoid long, complex words when a simpler alternative exists.

        3.  **TERMINOLOGY (JARGON):**
        *   Avoid medical jargon.
        *   If a technical term is absolutely essential and cannot be replaced, you MUST explain it simply in parentheses the first time it appears. (Example: "The trial used immunotherapy (a treatment that helps the body's immune system fight cancer).")

        4.  **FORMATTING AND LANGUAGE:**
        *   The output **MUST BE ONLY** the plain language summary without special symbols and stop tokens, **only the summary**.
        *   The output must be written **ONLY in English**.
        *   Structure the summary as a set of concise paragraphs. Use as many sentences as needed to include all essential information, up to a maximum length of about 500 words, however, **make sure ALL sentences are complete, which means ALL ideas are finished.**
        *   Do NOT include headings, bullet points, lists, citations, or URLs.

        **--- SOURCE TECHNICAL TEXT ---**
        <document>
        {technical_text}
        </document>

        **--- PLAIN LANGUAGE SUMMARY (PLS) ---**
      """

print("Prompts de generación definidos.")

Prompts de generación definidos.

In [ ]:
# --- Paso 4: Inicialización de Modelos y Funciones de Generación ---

# --- Modelo 1: Gemini ---
print("Inicializando modelo Gemini...")
try:
    gemini_model = genai.GenerativeModel(
        'gemini-2.5-flash-lite',
        system_instruction=SYSTEM_PROMPT
    )
    print("Modelo Gemini (gemini-2.5-flash-lite) inicializado con System Prompt.")
except Exception as e:
    print(f"Error al inicializar Gemini: {e}")
    raise

# --- Modelo 2: Llama 3.1 ---
print("Inicializando cliente de inferencia para Llama...")
LLAMA_MODEL_ID = "meta-llama/Llama-3.1-8B-Instruct"
llama_client = InferenceClient(model=LLAMA_MODEL_ID)

# --- Funciones de Generación (CON REINTENTOS) ---

def generate_pls_with_gemini(technical_text, max_retries=3, base_delay=3):
    """
    Genera un PLS usando el modelo de Gemini, con reintentos.
    """
    for attempt in range(max_retries):
        try:
            # Formateamos la instrucción del usuario
            prompt_content = INSTRUCTION_TEMPLATE.format(technical_text=technical_text)

            # Generamos el contenido (el system_prompt ya está configurado)
            response = gemini_model.generate_content(prompt_content)

            # Validación: si la respuesta está vacía, forzar reintento
            response_text = response.text.strip()
            if not response_text:
                raise ValueError("Respuesta de Gemini vacía.")

            return response_text # Éxito, salir de la función

        except Exception as e:
            print(f"Error en Gemini (Intento {attempt + 1}/{max_retries}): {str(e)}")
            if attempt < max_retries - 1:
                # Espera exponencial: 3s, 6s
                wait_time = base_delay * (attempt + 1)
                print(f"Reintentando en {wait_time} segundos...")
                time.sleep(wait_time)
            else:
                print("Fallaron todos los reintentos para Gemini.")
                return f"ERROR_GEMINI_FINAL: {str(e)}"

def generate_pls_with_llama(technical_text, max_retries=3, base_delay=3):
    """
    Genera un PLS usando Llama 3.1, con reintentos.
    """
    for attempt in range(max_retries):
        try:
            # Formateamos la instrucción del usuario
            prompt_user = INSTRUCTION_TEMPLATE.format(technical_text=technical_text)

            # Creamos la lista de mensajes (Sistema + Usuario)
            messages = [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": prompt_user}
            ]

            # Llamamos a la API de Inferencia
            response = llama_client.chat.completions.create(
                messages=messages,
                model=LLAMA_MODEL_ID,
                max_tokens=1024,
                temperature=0.2,
            )

            response_text = response.choices[0].message.content.strip()

            # Validación: si la respuesta está vacía, forzar reintento
            if not response_text:
                 raise ValueError("Respuesta de Llama vacía.")

            return response_text # Éxito, salir de la función

        except Exception as e:
            print(f"Error en Llama (Intento {attempt + 1}/{max_retries}): {str(e)}")
            if attempt < max_retries - 1:
                # Espera exponencial: 3s, 6s
                wait_time = base_delay * (attempt + 1)
                print(f"Reintentando en {wait_time} segundos...")
                time.sleep(wait_time)
            else:
                print("Fallaron todos los reintentos para Llama.")
                return f"ERROR_LLAMA_FINAL: {str(e)}"

Inicializando modelo Gemini...
Modelo Gemini (gemini-2.5-flash-lite) inicializado con System Prompt.
Inicializando cliente de inferencia para Llama...

In [ ]:
# --- Paso 5: Ejecución del Bucle de Generación ---

print("\n" + "="*80)
print(f"Iniciando la generación de PLS para {len(df)} textos...")

# 1. Definir límites de frecuencia (estos son delays *entre* filas exitosas)
GEMINI_API_DELAY = 4.1 # 15 RPM
LLAMA_API_DELAY = 1.0  # Delay genérico para la API de HF

print(f"Retardo (entre filas) para Gemini: {GEMINI_API_DELAY}s")
print(f"Retardo (entre filas) para Llama: {LLAMA_API_DELAY}s")

tiempo_por_fila = GEMINI_API_DELAY + LLAMA_API_DELAY
tiempo_estimado_min = (len(df) * tiempo_por_fila) / 60
print(f"Tiempo total estimado (mínimo): ~{tiempo_estimado_min:.1f} minutos.")
print("(El tiempo real puede ser mayor si ocurren reintentos)")
print("="*80)

# 2. Crear listas para guardar los nuevos resúmenes
gemini_pls_list = []
llama_pls_list = []

# 3. Iterar sobre el DataFrame
for index, row in tqdm(df.iterrows(), total=df.shape[0], desc="Generando PLS"):

    current_technical_text = row['technical_text']
    print(f"\n--- Procesando Fila {index} ---")

    # --- A: Generar con Gemini (con reintentos internos) ---
    print(f"Fila {index}: Generando con Gemini...")
    pls_gemini = generate_pls_with_gemini(current_technical_text)
    gemini_pls_list.append(pls_gemini)

    # Esperar *después* de que la función termine (éxito o fallo final)
    time.sleep(GEMINI_API_DELAY)

    # --- B: Generar con Llama (con reintentos internos) ---
    print(f"Fila {index}: Generando con Llama...")
    pls_llama = generate_pls_with_llama(current_technical_text)
    llama_pls_list.append(pls_llama)

    # Esperar *después* de que la función termine (éxito o fallo final)
    time.sleep(LLAMA_API_DELAY)

print("\nGeneración completada. Consolidando resultados...")

================================================================================
Iniciando la generación de PLS para 100 textos...
Retardo (entre filas) para Gemini: 4.1s
Retardo (entre filas) para Llama: 1.0s
Tiempo total estimado (mínimo): ~8.5 minutos.
(El tiempo real puede ser mayor si ocurren reintentos)
================================================================================

Generando PLS:   0%|          | 0/100 [00:00<?, ?it/s]

--- Procesando Fila 0 ---
Fila 0: Generando con Gemini...
Fila 0: Generando con Llama...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

--- Procesando Fila 1 ---
Fila 1: Generando con Gemini...
Fila 1: Generando con Llama...

--- Procesando Fila 2 ---
Fila 2: Generando con Gemini...
Fila 2: Generando con Llama...

--- Procesando Fila 3 ---
Fila 3: Generando con Gemini...
Fila 3: Generando con Llama...

--- Procesando Fila 4 ---
Fila 4: Generando con Gemini...
Fila 4: Generando con Llama...

--- Procesando Fila 5 ---
Fila 5: Generando con Gemini...
Fila 5: Generando con Llama...

--- Procesando Fila 6 ---
Fila 6: Generando con Gemini...
Fila 6: Generando con Llama...

--- Procesando Fila 7 ---
Fila 7: Generando con Gemini...
Fila 7: Generando con Llama...

--- Procesando Fila 8 ---
Fila 8: Generando con Gemini...
Fila 8: Generando con Llama...

--- Procesando Fila 9 ---
Fila 9: Generando con Gemini...
Fila 9: Generando con Llama...

--- Procesando Fila 10 ---
Fila 10: Generando con Gemini...
Fila 10: Generando con Llama...

--- Procesando Fila 11 ---
Fila 11: Generando con Gemini...
Fila 11: Generando con Llama...

--- Procesando Fila 12 ---
Fila 12: Generando con Gemini...
Fila 12: Generando con Llama...

--- Procesando Fila 13 ---
Fila 13: Generando con Gemini...
Fila 13: Generando con Llama...

--- Procesando Fila 14 ---
Fila 14: Generando con Gemini...
Fila 14: Generando con Llama...

--- Procesando Fila 15 ---
Fila 15: Generando con Gemini...
Fila 15: Generando con Llama...

--- Procesando Fila 16 ---
Fila 16: Generando con Gemini...
Fila 16: Generando con Llama...

--- Procesando Fila 17 ---
Fila 17: Generando con Gemini...
Fila 17: Generando con Llama...

--- Procesando Fila 18 ---
Fila 18: Generando con Gemini...
Fila 18: Generando con Llama...

--- Procesando Fila 19 ---
Fila 19: Generando con Gemini...
Fila 19: Generando con Llama...

--- Procesando Fila 20 ---
Fila 20: Generando con Gemini...
Fila 20: Generando con Llama...

--- Procesando Fila 21 ---
Fila 21: Generando con Gemini...
Fila 21: Generando con Llama...

--- Procesando Fila 22 ---
Fila 22: Generando con Gemini...
Fila 22: Generando con Llama...

--- Procesando Fila 23 ---
Fila 23: Generando con Gemini...
Fila 23: Generando con Llama...

--- Procesando Fila 24 ---
Fila 24: Generando con Gemini...
Fila 24: Generando con Llama...

--- Procesando Fila 25 ---
Fila 25: Generando con Gemini...
Fila 25: Generando con Llama...

--- Procesando Fila 26 ---
Fila 26: Generando con Gemini...
Fila 26: Generando con Llama...

--- Procesando Fila 27 ---
Fila 27: Generando con Gemini...
Fila 27: Generando con Llama...

--- Procesando Fila 28 ---
Fila 28: Generando con Gemini...
Fila 28: Generando con Llama...

--- Procesando Fila 29 ---
Fila 29: Generando con Gemini...
Fila 29: Generando con Llama...

--- Procesando Fila 30 ---
Fila 30: Generando con Gemini...
Fila 30: Generando con Llama...

--- Procesando Fila 31 ---
Fila 31: Generando con Gemini...
Fila 31: Generando con Llama...

--- Procesando Fila 32 ---
Fila 32: Generando con Gemini...
Fila 32: Generando con Llama...

--- Procesando Fila 33 ---
Fila 33: Generando con Gemini...
Fila 33: Generando con Llama...

--- Procesando Fila 34 ---
Fila 34: Generando con Gemini...
Fila 34: Generando con Llama...

--- Procesando Fila 35 ---
Fila 35: Generando con Gemini...
Fila 35: Generando con Llama...

--- Procesando Fila 36 ---
Fila 36: Generando con Gemini...
Fila 36: Generando con Llama...

--- Procesando Fila 37 ---
Fila 37: Generando con Gemini...
Fila 37: Generando con Llama...

--- Procesando Fila 38 ---
Fila 38: Generando con Gemini...
Fila 38: Generando con Llama...

--- Procesando Fila 39 ---
Fila 39: Generando con Gemini...
Fila 39: Generando con Llama...

--- Procesando Fila 40 ---
Fila 40: Generando con Gemini...
Fila 40: Generando con Llama...

--- Procesando Fila 41 ---
Fila 41: Generando con Gemini...
Fila 41: Generando con Llama...

--- Procesando Fila 42 ---
Fila 42: Generando con Gemini...
Fila 42: Generando con Llama...

--- Procesando Fila 43 ---
Fila 43: Generando con Gemini...
Fila 43: Generando con Llama...

--- Procesando Fila 44 ---
Fila 44: Generando con Gemini...
Fila 44: Generando con Llama...

--- Procesando Fila 45 ---
Fila 45: Generando con Gemini...
Fila 45: Generando con Llama...

--- Procesando Fila 46 ---
Fila 46: Generando con Gemini...
Fila 46: Generando con Llama...

--- Procesando Fila 47 ---
Fila 47: Generando con Gemini...
Fila 47: Generando con Llama...

--- Procesando Fila 48 ---
Fila 48: Generando con Gemini...
Fila 48: Generando con Llama...

--- Procesando Fila 49 ---
Fila 49: Generando con Gemini...
Fila 49: Generando con Llama...

--- Procesando Fila 50 ---
Fila 50: Generando con Gemini...
Fila 50: Generando con Llama...

--- Procesando Fila 51 ---
Fila 51: Generando con Gemini...
Fila 51: Generando con Llama...

--- Procesando Fila 52 ---
Fila 52: Generando con Gemini...
Fila 52: Generando con Llama...

--- Procesando Fila 53 ---
Fila 53: Generando con Gemini...
Fila 53: Generando con Llama...

--- Procesando Fila 54 ---
Fila 54: Generando con Gemini...
Fila 54: Generando con Llama...

--- Procesando Fila 55 ---
Fila 55: Generando con Gemini...
Fila 55: Generando con Llama...

--- Procesando Fila 56 ---
Fila 56: Generando con Gemini...
Fila 56: Generando con Llama...

--- Procesando Fila 57 ---
Fila 57: Generando con Gemini...
Fila 57: Generando con Llama...

--- Procesando Fila 58 ---
Fila 58: Generando con Gemini...
Fila 58: Generando con Llama...

--- Procesando Fila 59 ---
Fila 59: Generando con Gemini...
Fila 59: Generando con Llama...

--- Procesando Fila 60 ---
Fila 60: Generando con Gemini...
Fila 60: Generando con Llama...

--- Procesando Fila 61 ---
Fila 61: Generando con Gemini...
Fila 61: Generando con Llama...

--- Procesando Fila 62 ---
Fila 62: Generando con Gemini...
Fila 62: Generando con Llama...

--- Procesando Fila 63 ---
Fila 63: Generando con Gemini...
Fila 63: Generando con Llama...

--- Procesando Fila 64 ---
Fila 64: Generando con Gemini...
Fila 64: Generando con Llama...

--- Procesando Fila 65 ---
Fila 65: Generando con Gemini...
Fila 65: Generando con Llama...

--- Procesando Fila 66 ---
Fila 66: Generando con Gemini...
Fila 66: Generando con Llama...

--- Procesando Fila 67 ---
Fila 67: Generando con Gemini...
Fila 67: Generando con Llama...

--- Procesando Fila 68 ---
Fila 68: Generando con Gemini...
Fila 68: Generando con Llama...

--- Procesando Fila 69 ---
Fila 69: Generando con Gemini...
Fila 69: Generando con Llama...

--- Procesando Fila 70 ---
Fila 70: Generando con Gemini...
Fila 70: Generando con Llama...

--- Procesando Fila 71 ---
Fila 71: Generando con Gemini...
Fila 71: Generando con Llama...

--- Procesando Fila 72 ---
Fila 72: Generando con Gemini...
Fila 72: Generando con Llama...

--- Procesando Fila 73 ---
Fila 73: Generando con Gemini...
Fila 73: Generando con Llama...

--- Procesando Fila 74 ---
Fila 74: Generando con Gemini...
Fila 74: Generando con Llama...

--- Procesando Fila 75 ---
Fila 75: Generando con Gemini...
Fila 75: Generando con Llama...

--- Procesando Fila 76 ---
Fila 76: Generando con Gemini...
Fila 76: Generando con Llama...

--- Procesando Fila 77 ---
Fila 77: Generando con Gemini...
Fila 77: Generando con Llama...

--- Procesando Fila 78 ---
Fila 78: Generando con Gemini...
Fila 78: Generando con Llama...

--- Procesando Fila 79 ---
Fila 79: Generando con Gemini...
Fila 79: Generando con Llama...

--- Procesando Fila 80 ---
Fila 80: Generando con Gemini...
Fila 80: Generando con Llama...

--- Procesando Fila 81 ---
Fila 81: Generando con Gemini...
Fila 81: Generando con Llama...

--- Procesando Fila 82 ---
Fila 82: Generando con Gemini...
Fila 82: Generando con Llama...

--- Procesando Fila 83 ---
Fila 83: Generando con Gemini...
Fila 83: Generando con Llama...

--- Procesando Fila 84 ---
Fila 84: Generando con Gemini...
Fila 84: Generando con Llama...

--- Procesando Fila 85 ---
Fila 85: Generando con Gemini...
Fila 85: Generando con Llama...

--- Procesando Fila 86 ---
Fila 86: Generando con Gemini...
Fila 86: Generando con Llama...

--- Procesando Fila 87 ---
Fila 87: Generando con Gemini...
Fila 87: Generando con Llama...

--- Procesando Fila 88 ---
Fila 88: Generando con Gemini...
Fila 88: Generando con Llama...

--- Procesando Fila 89 ---
Fila 89: Generando con Gemini...
Fila 89: Generando con Llama...

--- Procesando Fila 90 ---
Fila 90: Generando con Gemini...
Fila 90: Generando con Llama...

--- Procesando Fila 91 ---
Fila 91: Generando con Gemini...
Fila 91: Generando con Llama...

--- Procesando Fila 92 ---
Fila 92: Generando con Gemini...
Fila 92: Generando con Llama...

--- Procesando Fila 93 ---
Fila 93: Generando con Gemini...
Fila 93: Generando con Llama...

--- Procesando Fila 94 ---
Fila 94: Generando con Gemini...
Fila 94: Generando con Llama...

--- Procesando Fila 95 ---
Fila 95: Generando con Gemini...
Fila 95: Generando con Llama...

--- Procesando Fila 96 ---
Fila 96: Generando con Gemini...
Fila 96: Generando con Llama...

--- Procesando Fila 97 ---
Fila 97: Generando con Gemini...
Fila 97: Generando con Llama...

--- Procesando Fila 98 ---
Fila 98: Generando con Gemini...
Fila 98: Generando con Llama...

--- Procesando Fila 99 ---
Fila 99: Generando con Gemini...
Fila 99: Generando con Llama...

Generación completada. Consolidando resultados...

In [ ]:
# --- Paso 6: Consolidación y Guardado de Resultados ---
try:
    # 1. Crear un DataFrame con los resultados
    df_results = pd.DataFrame({
        'gemini_pls': gemini_pls_list,
        'llama_pls': llama_pls_list
    }, index=df.index)

    # 2. Unir con el DataFrame original (que tiene technical_text y reference_summary)
    df_final = pd.concat([df, df_results], axis=1)

    # 3. Guardar el DataFrame final en el nuevo CSV
    df_final.to_csv(csv_path_output, index=False, encoding='utf-8-sig')

    # Cambiar el nombre de la columna generated_summary por MedGemma_pls
    df_final.rename(columns={'generated_summary': 'medgemma_pls'}, inplace=True)

    print("\n" + "="*80)
    print("¡Éxito! La generación de PLS ha finalizado.")
    print(f"Resultados guardados en: {csv_path_output}")
    print("Este archivo contiene las columnas 'technical_text', 'reference_summary', 'medgemma_pls', 'gemini_pls' y 'llama_pls'.")
    print("="*80)

    # 4. Mostrar un resumen de los resultados
    print("\nVista previa de los resultados (primeras 5 filas):")
    print(df_final.head())

    # 5. Comprobar si hubo errores finales
    errores_gemini = df_final[df_final['gemini_pls'].str.startswith("ERROR_GEMINI_FINAL")]
    errores_llama = df_final[df_final['llama_pls'].str.startswith("ERROR_LLAMA_FINAL")]

    if not errores_gemini.empty or not errores_llama.empty:
        print("\n" + "!"*80)
        print("ADVERTENCIA: Se detectaron errores finales después de 3 reintentos.")
        print(f"Total de errores finales en Gemini: {len(errores_gemini)}")
        print(f"Total de errores finales en Llama: {len(errores_llama)}")
        print("Estos necesitarán ser revisados o ejecutados manualmente.")
        print("!"*80)
    else:
        print("\nComprobación de integridad: No se detectaron errores finales. ¡Todo se generó exitosamente!")

except Exception as e:
    print(f"\nError al consolidar o guardar el DataFrame: {e}")
    print("Los resultados de la generación están en 'gemini_pls_list' y 'llama_pls_list'.")

================================================================================
¡Éxito! La generación de PLS ha finalizado.
Resultados guardados en: /content/drive/MyDrive/NLP_Project_MedGemma/v8_foundation_model_pls_results.csv
Este archivo contiene las columnas 'technical_text', 'reference_summary', 'medgemma_pls', 'gemini_pls' y 'llama_pls'.
================================================================================

Vista previa de los resultados (primeras 5 filas):
                                      technical_text  \
0  Background\nLumbar spinal stenosis with neurog...
1  Background\nOlder patients with multiple healt...
2  Background\nBeta‐blockers are an essential par...
3  Background\nThalassaemia is a genetic disorder...
4  Background\nApproximately 600 million children...

                                   reference_summary  \
0  Non‐surgical treatment for spinal stenosis wit...
1  Interventions for involving older patients wit...
2  Beta‐blockers for children with congestive hea...
3  Removal of the spleen in people with thalassae...
4  One, two or three times a week iron supplement...

                                        medgemma_pls  \
0  Lumbar spinal stenosis is a common condition, ...
1  Older adults with many health problems (multi-...
2  Beta-blockers are medications used to treat ad...
3  Thalassaemia is a genetic blood disorder where...
4  Iron deficiency is a big problem for children,...

                                          gemini_pls  \
0  Doctors often see older people with a common c...
1  Older adults who have many health problems oft...
2  Beta-blockers are drugs commonly used to treat...
3  Thalassaemia is a blood disorder that affects ...
4  Millions of young children around the world ha...

                                           llama_pls
0  Lumbar spinal stenosis is a common condition t...
1  Older adults with multiple health problems wan...
2  **Understanding Beta-Blockers in Children with...
3  Thalassemia is a genetic disorder that affects...
4  Iron deficiency is a big problem for many chil...

Comprobación de integridad: No se detectaron errores finales. ¡Todo se generó exitosamente!

In [ ]:
# --- Celda 1.1: Instalación de Dependencias (Sin AlignScore) ---

# Instalar librerías estándar desde PyPI
!pip install -q pandas torch transformers evaluate bert_score textstat spacy accelerate sentencepiece protobuf

# Descargar el modelo de lenguaje de spaCy
!python -m spacy download en_core_web_sm

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 7.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.4/176.4 kB 17.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 100.3 MB/s eta 0:00:00
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 150.9 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

## 8. Evaluación modular sin AlignScore
Prepara dependencias ligeras, carga modelos y evaluadores, ejecuta la lógica de evaluación y persiste métricas intermedias.

In [ ]:
# --- Celda 1.2: Importaciones y Configuración Inicial ---
import os
import pandas as pd
import numpy as np
import torch
import spacy
import textstat
import evaluate
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline
from tqdm.auto import tqdm
import warnings
# limpia ram y vram
import gc
# Ignorar advertencias
warnings.filterwarnings("ignore")

In [ ]:
# Conectarse a Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# --- Configuración Global ---
BASE_PROJECT_DIR = "/content/drive/MyDrive/NLP_Project_MedGemma"
CSV_RESULTS_PATH = os.path.join(BASE_PROJECT_DIR, 'v8_foundation_model_pls_results.csv')
INTERMEDIATE_CSV_PATH = os.path.join(BASE_PROJECT_DIR, 'v8_intermediate_metrics.csv') # Archivo de salida

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Usando dispositivo: {DEVICE}")

Usando dispositivo: cuda

In [ ]:
# --- Celda 1.3: Carga de Modelos y Evaluadores (Sin AlignScore) ---

print("Cargando modelo de Spacy...")
nlp = spacy.load("en_core_web_sm")

print("Cargando métrica BERTScore...")
bertscore_metric = evaluate.load("bertscore")

print("Inicializando modelo NLI para Factualidad...")
nli_model_id = "facebook/bart-large-mnli"
nli_tokenizer = AutoTokenizer.from_pretrained(nli_model_id)
nli_model = AutoModelForSequenceClassification.from_pretrained(nli_model_id).to(DEVICE)
nli_model.eval()

print("Inicializando pipelines de QA para Factualidad...")
question_generator = pipeline("text2text-generation", model="valhalla/t5-base-qg-hl", device=DEVICE)
question_answerer = pipeline("question-answering", model="distilbert-base-cased-distilled-squad", device=DEVICE)

print("\nModelos y evaluadores listos.")

Cargando modelo de Spacy...
Cargando métrica BERTScore...

Downloading builder script: 0.00B [00:00, ?B/s]

Inicializando modelo NLI para Factualidad...

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

Inicializando pipelines de QA para Factualidad...

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/892M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/129 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/15.0 [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Device set to use cuda

config.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/261M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

Device set to use cuda

Modelos y evaluadores listos.

In [ ]:
# --- Celda 1.4: Lógica de Evaluación Modular (Corregida y Robusta) ---

# Asegurarse de que el tokenizer tenga pad_token (BART a veces no lo trae por defecto en ciertas versiones)
if nli_tokenizer.pad_token is None:
    nli_tokenizer.pad_token = nli_tokenizer.eos_token
    print("Token de relleno (pad_token) asignado manualmente.")

# --- Función para BERTScore (Sin cambios) ---
def calculate_bertscore(predictions, references):
    if not predictions or not references:
        return 0.0
    print("Calculando BERTScore...")
    try:
        results = bertscore_metric.compute(predictions=predictions, references=references, lang="en", verbose=False)
        return np.mean(results['f1'])
    except Exception as e:
        print(f"Error en BERTScore: {e}")
        return 0.0

# --- Función para Factualidad (NLI) - CORREGIDA Y SEGURA ---
def calculate_nli_factuality(sources, predictions, batch_size=16):
    print("Calculando Factualidad (NLI) con procesamiento por lotes robusto...")

    # Listas separadas para premisas (texto fuente) e hipótesis (oración resumen)
    all_premises = []
    all_hypotheses = []
    doc_indices = [] # Para reconstruir a qué resumen pertenece cada par

    print("Tokenizando oraciones con Spacy...")
    # batch_size en nlp.pipe ayuda a gestionar memoria CPU
    docs = list(nlp.pipe(predictions, disable=["ner", "tagger", "lemmatizer"], batch_size=100))

    for i, (source, doc) in enumerate(zip(sources, docs)):
        # Validación extra: si source es vacío, lo saltamos para evitar errores del modelo
        if not isinstance(source, str) or not source.strip():
            continue

        summary_sentences = [sent.text for sent in doc.sents if sent.text.strip()]

        if not summary_sentences:
            continue

        for sent in summary_sentences:
            all_premises.append(source)
            all_hypotheses.append(sent)
            doc_indices.append(i)

    if not all_premises:
        return 0.0

    print(f"Ejecutando inferencia NLI en {len(all_premises)} pares...")
    probs_list = []

    # Procesamiento por lotes
    for i in tqdm(range(0, len(all_premises), batch_size), desc="NLI Batches"):
        batch_prem = all_premises[i : i + batch_size]
        batch_hypo = all_hypotheses[i : i + batch_size]

        # Tokenización: Pasamos (texto, par_texto) por separado
        inputs = nli_tokenizer(
            batch_prem,           # Premisa (Source)
            batch_hypo,           # Hipótesis (Summary sentence)
            return_tensors='pt',
            padding=True,         # Padding dinámico al más largo del batch
            truncation="only_first", # CRÍTICO: Solo recortar la fuente (premisa), nunca el resumen
            max_length=1024       # BART soporta hasta 1024. Si tienes poca VRAM, baja a 512
        ).to(DEVICE)

        with torch.no_grad():
            outputs = nli_model(**inputs)
            probs = torch.softmax(outputs.logits, dim=1)

            # BART-Large-MNLI labels: 0: contradiction, 1: neutral, 2: entailment
            # Obtenemos probabilidad de contradicción (índice 0)
            contradiction_probs = probs[:, 0].cpu().numpy()
            probs_list.extend(contradiction_probs)

    # Reconstrucción de Scores
    summary_scores = {i: [] for i in range(len(predictions))}

    for idx, prob in zip(doc_indices, probs_list):
        # Umbral estricto
        is_contradiction = 1 if prob > 0.7 else 0
        summary_scores[idx].append(is_contradiction)

    final_scores = []
    for i in range(len(predictions)):
        sentences_contradictions = summary_scores[i]
        if not sentences_contradictions:
            final_scores.append(0.0)
        else:
            # Score = 1 - (% de oraciones que son mentira)
            score = 1.0 - (sum(sentences_contradictions) / len(sentences_contradictions))
            final_scores.append(score)
    # LIMPIEZA CRITICAL AL FINAL DE NLI
    del all_premises, all_hypotheses, doc_indices, probs_list, summary_scores
    gc.collect()
    torch.cuda.empty_cache()
    # Forzamos al recolector de basura de Python
    gc.collect()
    # Vaciamos la caché de PyTorch para liberar la VRAM
    torch.cuda.empty_cache()

    print("Memoria VRAM liberada tras QA.")

    return np.mean(final_scores)

# --- Función para Factualidad (QA Answerability) - VERSIÓN CON TQDM Y GESTIÓN DE VRAM ---
def calculate_qa_factuality(sources, predictions):
    print("Calculando Factualidad (QA Answerability) con procesamiento por lotes...")

    all_sentences = []
    contexts_for_sentences = []
    sentence_counts_per_summary = []

    # Uso de nlp.pipe para consistencia y velocidad
    docs = list(nlp.pipe(predictions, disable=["ner", "tagger"]))

    for source_doc, doc in zip(sources, docs):
        if not source_doc or not doc.text.strip():
            sentence_counts_per_summary.append(0)
            continue

        summary_sentences = [sent.text for sent in doc.sents if sent.text.strip()]

        if not summary_sentences:
            sentence_counts_per_summary.append(0)
            continue

        all_sentences.extend(summary_sentences)
        contexts_for_sentences.extend([source_doc] * len(summary_sentences))
        sentence_counts_per_summary.append(len(summary_sentences))

    if not all_sentences:
        print("No se encontraron oraciones válidas para procesar.")
        return 0.0

    print(f"Generando preguntas para {len(all_sentences)} oraciones en total...")
    # Generación de preguntas
    generated_q_dicts = question_generator(
        all_sentences,
        max_new_tokens=32,
        num_beams=4,
        batch_size=128, # Aumenté un poco el batch si la memoria lo permite
        truncation=True
    )
    questions = [q['generated_text'] for q in generated_q_dicts]

    print(f"Respondiendo a {len(questions)} preguntas...")
    answers = question_answerer(
        question=questions,
        context=contexts_for_sentences,
        batch_size=128
    )

    final_scores = []
    current_answer_idx = 0
    for num_sentences in tqdm(sentence_counts_per_summary, desc="Agregando scores"):
        if num_sentences == 0:
            final_scores.append(0)
            continue

        summary_answers = answers[current_answer_idx : current_answer_idx + num_sentences]
        answered_questions = sum(1 for ans in summary_answers if ans['score'] > 0.3) # Umbral de confianza
        score = answered_questions / num_sentences
        final_scores.append(score)
        current_answer_idx += num_sentences

    # --- 5. LIMPIEZA FINAL CRÍTICA ---
    # Borramos las variables grandes que ocupan memoria
    del all_sentences, contexts_for_sentences, questions, answers, docs
    # Forzamos al recolector de basura de Python
    gc.collect()
    # Vaciamos la caché de PyTorch para liberar la VRAM
    torch.cuda.empty_cache()

    print("Memoria VRAM liberada tras QA.")
    return np.mean(final_scores)

# --- Función para Métricas de Legibilidad (Sin cambios mayores, solo limpieza) ---
def calculate_readability(texts):
    print("Calculando Métricas de Legibilidad...")
    metrics = {'fkgl': [], 'fre': [], 'fog': [], 'smog': [], 'cl': []}
    for text in tqdm(texts, desc="Readability"):
         if not isinstance(text, str) or not text.strip():
            metrics['fkgl'].append(12.0); metrics['fre'].append(30.0); metrics['fog'].append(12.0); metrics['smog'].append(8.0); metrics['cl'].append(8.0)
            continue
         metrics['fkgl'].append(textstat.flesch_kincaid_grade(text))
         metrics['fre'].append(textstat.flesch_reading_ease(text))
         metrics['fog'].append(textstat.gunning_fog(text))
         metrics['smog'].append(textstat.smog_index(text))
         metrics['cl'].append(textstat.coleman_liau_index(text))

    return {key: np.mean(val) for key, val in metrics.items()}

In [ ]:
gc.collect()
torch.cuda.empty_cache()
## Forzamos al recolector de basura de Python
#gc.collect()
## Vaciamos la caché de PyTorch para liberar la VRAM
#torch.cuda.empty_cache()

In [ ]:
# --- Celda 1.5: Ejecución y Almacenamiento de Resultados Intermedios ---

# Cargar datos
print(f"Cargando datos desde: {CSV_RESULTS_PATH}")
df_results = pd.read_csv(CSV_RESULTS_PATH)
df_results.dropna(subset=['technical_text', 'reference_summary'], inplace=True)

# For testing: Filtrar solo 10 textos
#df_results = df_results.head(10)

if 'generated_summary' in df_results.columns:
    df_results.rename(columns={'generated_summary': 'medgemma_pls'}, inplace=True)

# Limpieza inicial general para asegurar que references/sources sean válidos
df_results = df_results[df_results['reference_summary'].str.strip() != '']
df_results = df_results[df_results['technical_text'].str.strip() != '']

model_columns = [col for col in df_results.columns if '_pls' in col]
results_list = []

Cargando datos desde: /content/drive/MyDrive/NLP_Project_MedGemma/v8_foundation_model_pls_results.csv

In [ ]:
%%time
# ---------------------------------------------------------
# NUEVO BLOQUE: Evaluación del Reference Summary (Baseline)
# ---------------------------------------------------------
print(f"\n{'='*25}\n--- Evaluando Referencia: reference_summary ---\n{'='*25}")

ref_sources = df_results['technical_text'].tolist()
ref_texts = df_results['reference_summary'].tolist()

# 1. Readability (Referencia)
ref_readability = calculate_readability(ref_texts)
for key, value in ref_readability.items():
    results_list.append({'model': 'reference_summary', 'metric': f'readability_{key}', 'score': value})

# 2. BERTScore (Referencia vs Referencia es siempre 1.0)
# Lo agregamos hardcodeado para que aparezca en las gráficas comparativas
results_list.append({'model': 'reference_summary', 'metric': 'bertscore_f1', 'score': 1.0})

# 3. Factualidad NLI (Referencia vs Source)
# Esto nos dice si el humano fue fiel al texto fuente
ref_nli_score = calculate_nli_factuality(ref_sources, ref_texts)
results_list.append({'model': 'reference_summary', 'metric': 'nli_factuality', 'score': ref_nli_score})

# 4. Factualidad QA (Referencia vs Source)
ref_qa_score = calculate_qa_factuality(ref_sources, ref_texts)
results_list.append({'model': 'reference_summary', 'metric': 'qa_factuality', 'score': ref_qa_score})

# ---------------------------------------------------------
# Evaluación de Modelos
# ---------------------------------------------------------
for model_name in model_columns:
    print(f"\n{'='*25}\n--- Evaluando Modelo: {model_name} ---\n{'='*25}")

    # Filtrar filas donde este modelo específico tenga predicciones nulas
    temp_df = df_results[['technical_text', 'reference_summary', model_name]].copy()
    temp_df.dropna(subset=[model_name], inplace=True)
    temp_df = temp_df[temp_df[model_name].str.strip() != '']

    if temp_df.empty:
        print(f"No hay resúmenes válidos para {model_name}. Saltando.")
        continue

    sources = temp_df['technical_text'].tolist()
    references = temp_df['reference_summary'].tolist()
    predictions = temp_df[model_name].tolist()

    # Calcular métricas
    # BERTScore
    results_list.append({'model': model_name, 'metric': 'bertscore_f1', 'score': calculate_bertscore(predictions, references)})

    # Factualidad (NLI & QA)
    results_list.append({'model': model_name, 'metric': 'nli_factuality', 'score': calculate_nli_factuality(sources, predictions)})
    results_list.append({'model': model_name, 'metric': 'qa_factuality', 'score': calculate_qa_factuality(sources, predictions)})

    # Readability
    readability_scores = calculate_readability(predictions)
    for key, value in readability_scores.items():
        results_list.append({'model': model_name, 'metric': f'readability_{key}', 'score': value})

    # --- AGREGAR ESTO AL FINAL DEL BUCLE FOR ---
    print(f"Limpiando memoria tras evaluar {model_name}...")
    del sources, references, predictions, temp_df
    gc.collect()
    torch.cuda.empty_cache()
    print("-" * 30)

# Convertir y guardar
intermediate_df = pd.DataFrame(results_list)
intermediate_df.to_csv(INTERMEDIATE_CSV_PATH, index=False)

print("\n\n" + "="*80)
print("¡Éxito! Las métricas (incluyendo baseline de referencia) han sido calculadas.")
print(f" --> {INTERMEDIATE_CSV_PATH}")
print("="*80)
print(intermediate_df.head(10))

=========================
--- Evaluando Referencia: reference_summary ---
=========================
Calculando Métricas de Legibilidad...

Readability:   0%|          | 0/100 [00:00<?, ?it/s]

Calculando Factualidad (NLI) con procesamiento por lotes robusto...
Tokenizando oraciones con Spacy...
Ejecutando inferencia NLI en 2083 pares...

NLI Batches:   0%|          | 0/131 [00:00<?, ?it/s]

Memoria VRAM liberada tras QA.
Calculando Factualidad (QA Answerability) con procesamiento por lotes...
Generando preguntas para 2083 oraciones en total...
Respondiendo a 2083 preguntas...

Agregando scores:   0%|          | 0/100 [00:00<?, ?it/s]

Memoria VRAM liberada tras QA.

=========================
--- Evaluando Modelo: medgemma_pls ---
=========================
Calculando BERTScore...

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Calculando Factualidad (NLI) con procesamiento por lotes robusto...
Tokenizando oraciones con Spacy...
Ejecutando inferencia NLI en 1405 pares...

NLI Batches:   0%|          | 0/88 [00:00<?, ?it/s]

Memoria VRAM liberada tras QA.
Calculando Factualidad (QA Answerability) con procesamiento por lotes...
Generando preguntas para 1405 oraciones en total...
Respondiendo a 1405 preguntas...

Agregando scores:   0%|          | 0/100 [00:00<?, ?it/s]

Memoria VRAM liberada tras QA.
Calculando Métricas de Legibilidad...

Readability:   0%|          | 0/100 [00:00<?, ?it/s]

Limpiando memoria tras evaluar medgemma_pls...
------------------------------

=========================
--- Evaluando Modelo: qwen_pls ---
=========================
Calculando BERTScore...
Calculando Factualidad (NLI) con procesamiento por lotes robusto...
Tokenizando oraciones con Spacy...
Ejecutando inferencia NLI en 2394 pares...

NLI Batches:   0%|          | 0/150 [00:00<?, ?it/s]

Memoria VRAM liberada tras QA.
Calculando Factualidad (QA Answerability) con procesamiento por lotes...
Generando preguntas para 2394 oraciones en total...
Respondiendo a 2394 preguntas...

Agregando scores:   0%|          | 0/100 [00:00<?, ?it/s]

Memoria VRAM liberada tras QA.
Calculando Métricas de Legibilidad...

Readability:   0%|          | 0/100 [00:00<?, ?it/s]

Limpiando memoria tras evaluar qwen_pls...
------------------------------

=========================
--- Evaluando Modelo: gemini_pls ---
=========================
Calculando BERTScore...
Calculando Factualidad (NLI) con procesamiento por lotes robusto...
Tokenizando oraciones con Spacy...
Ejecutando inferencia NLI en 2022 pares...

NLI Batches:   0%|          | 0/127 [00:00<?, ?it/s]

Memoria VRAM liberada tras QA.
Calculando Factualidad (QA Answerability) con procesamiento por lotes...
Generando preguntas para 2022 oraciones en total...
Respondiendo a 2022 preguntas...

Agregando scores:   0%|          | 0/100 [00:00<?, ?it/s]

Memoria VRAM liberada tras QA.
Calculando Métricas de Legibilidad...

Readability:   0%|          | 0/100 [00:00<?, ?it/s]

Limpiando memoria tras evaluar gemini_pls...
------------------------------

=========================
--- Evaluando Modelo: llama_pls ---
=========================
Calculando BERTScore...
Calculando Factualidad (NLI) con procesamiento por lotes robusto...
Tokenizando oraciones con Spacy...
Ejecutando inferencia NLI en 1594 pares...

NLI Batches:   0%|          | 0/100 [00:00<?, ?it/s]

Memoria VRAM liberada tras QA.
Calculando Factualidad (QA Answerability) con procesamiento por lotes...
Generando preguntas para 1594 oraciones en total...
Respondiendo a 1594 preguntas...

Agregando scores:   0%|          | 0/100 [00:00<?, ?it/s]

Memoria VRAM liberada tras QA.
Calculando Métricas de Legibilidad...

Readability:   0%|          | 0/100 [00:00<?, ?it/s]

Limpiando memoria tras evaluar llama_pls...
------------------------------


================================================================================
¡Éxito! Las métricas (incluyendo baseline de referencia) han sido calculadas.
 --> /content/drive/MyDrive/NLP_Project_MedGemma/v8_intermediate_metrics.csv
================================================================================
               model            metric      score
0  reference_summary  readability_fkgl  13.963180
1  reference_summary   readability_fre  34.247340
2  reference_summary   readability_fog  16.915162
3  reference_summary  readability_smog  15.456659
4  reference_summary    readability_cl  14.118936
5  reference_summary      bertscore_f1   1.000000
6  reference_summary    nli_factuality   0.945061
7  reference_summary     qa_factuality   0.163167
8       medgemma_pls      bertscore_f1   0.852164
9       medgemma_pls    nli_factuality   0.976970
CPU times: user 14min 41s, sys: 9.87 s, total: 14min 51s
Wall time: 14min 18s

## 9. Flujo AlignScore en entorno aislado
Instala Python 3.10 en un entorno virtual, agrega AlignScore y spaCy, escribe el script de puntuación y lo ejecuta para obtener el reporte final.

In [ ]:
# --- Celda 2.1: Instalar Python 3.10 ---
# Añadimos el repositorio PPA 'deadsnakes' que contiene versiones antiguas de Python
!sudo add-apt-repository -y ppa:deadsnakes/ppa
!sudo apt-get update -y

# Instalamos Python 3.10 y su módulo venv
!sudo apt-get install -qq python3.10 python3.10-venv -y

# Verificamos que se instaló correctamente
!python3.10 --version

Repository: 'deb https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu/ jammy main'
Description:
This PPA contains more recent Python versions packaged for Ubuntu.

Disclaimer: there's no guarantee of timely updates in case of security problems or other issues. If you want to use them in a security-or-otherwise-critical environment (say, on a production server), you do so at your own risk.

Update Note
===========
Please use this repository instead of ppa:fkrull/deadsnakes.

Reporting Issues
================

Issues can be reported in the master issue tracker at:
https://github.com/deadsnakes/issues/issues

Supported Ubuntu and Python Versions
====================================

- Ubuntu 22.04 (jammy) Python3.7 - Python3.9, Python3.11 - Python3.13
- Ubuntu 24.04 (noble) Python3.7 - Python3.11, Python3.13
- Note: Python 3.10 (jammy), Python3.12 (noble) are not provided by deadsnakes as upstream ubuntu provides those packages.

Why some packages aren't built:
- Note: for jammy and noble, older python versions requre libssl<3 so they are not currently built
- If you need these, reach out to asottile to set up a private ppa

The packages may also work on other versions of Ubuntu or Debian, but that is not tested or supported.

Packages
========

The packages provided here are loosely based on the debian upstream packages with some modifications to make them more usable as non-default pythons and on ubuntu.  As such, the packages follow debian's patterns and often do not include a full python distribution with just `apt install python#.#`.  Here is a list of packages that may be useful along with the default install:

- `python#.#-dev`: includes development headers for building C extensions
- `python#.#-venv`: provides the standard library `venv` module
- `python#.#-distutils`: provides the standard library `distutils` module
- `python#.#-lib2to3`: provides the `2to3-#.#` utility as well as the standard library `lib2to3` module
- `python#.#-gdbm`: provides the standard library `dbm.gnu` module
- `python#.#-tk`: provides the standard library `tkinter` module

Third-Party Python Modules
==========================

Python modules in the official Ubuntu repositories are packaged to work with the Python interpreters from the official repositories. Accordingly, they generally won't work with the Python interpreters from this PPA. As an exception, pure-Python modules for Python 3 will work, but any compiled extension modules won't.

To install 3rd-party Python modules, you should use the common Python packaging tools.  For an introduction into the Python packaging ecosystem and its tools, refer to the Python Packaging User Guide:
https://packaging.python.org/installing/

Sources
=======
The package sources are available at:
https://github.com/deadsnakes/

Nightly Builds
==============

For nightly builds, see ppa:deadsnakes/nightly https://launchpad.net/~deadsnakes/+archive/ubuntu/nightly
More info: https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa
Adding repository.
Found existing deb entry in /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list
Adding deb entry to /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list
Found existing deb-src entry in /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list
Adding key to /etc/apt/trusted.gpg.d/deadsnakes-ubuntu-ppa.gpg with fingerprint F23C5A6CF475977595C89F51BA6932366A755776
Get:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:3 https://cli.github.com/packages stable InRelease [3,917 B]
Get:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [2,149 kB]
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:9 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Get:11 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,470 kB]
Hit:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:13 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:14 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [38.8 kB]
Get:15 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,290 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,595 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [3,865 kB]
Get:18 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,532 kB]
Get:19 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [5,988 kB]
Get:20 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,830 kB]
Fetched 31.2 MB in 4s (7,406 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Get:3 https://cli.github.com/packages stable InRelease [3,917 B]
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:10 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 3,917 B in 1s (3,424 B/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 3.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package python3-pip-whl.
(Reading database ... 121713 files and directories currently installed.)
Preparing to unpack .../python3-pip-whl_22.0.2+dfsg-1ubuntu0.7_all.deb ...
Unpacking python3-pip-whl (22.0.2+dfsg-1ubuntu0.7) ...
Selecting previously unselected package python3-setuptools-whl.
Preparing to unpack .../python3-setuptools-whl_68.1.2-2~jammy3_all.deb ...
Unpacking python3-setuptools-whl (68.1.2-2~jammy3) ...
Selecting previously unselected package python3.10-venv.
Preparing to unpack .../python3.10-venv_3.10.12-1~22.04.11_amd64.deb ...
Unpacking python3.10-venv (3.10.12-1~22.04.11) ...
Setting up python3-setuptools-whl (68.1.2-2~jammy3) ...
Setting up python3-pip-whl (22.0.2+dfsg-1ubuntu0.7) ...
Setting up python3.10-venv (3.10.12-1~22.04.11) ...
Python 3.10.12

In [ ]:
# --- Celda 2.2: Crear y Preparar el Entorno Virtual (VERSIÓN FINAL CORREGIDA) ---

# 1. Creamos un entorno virtual (esto no cambia)
!python3.10 -m venv /content/align_env

# 2. Instalamos PyTorch (esto no cambia)
!/content/align_env/bin/pip install -q torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117

# 3. ¡EL COMANDO CLAVE Y ÚNICO!
#    Instalamos AlignScore Y TODAS sus dependencias con las versiones correctas en un solo paso.
#    - transformers==4.33.2 (para el import AdamW)
#    - tokenizers==0.13.3 (compatible con transformers 4.33.2)
#    - pytorch-lightning==1.9.5 (la versión que AlignScore espera)
!/content/align_env/bin/pip install -q \
    pandas \
    transformers==4.33.2 \
    tokenizers==0.13.3 \
    pytorch-lightning==1.9.5 \
    "git+https://github.com/yuh-zha/AlignScore.git"

# --- Verificación ---
print("\n--- Verificando el entorno virtual ---")
!/content/align_env/bin/python --version
!/content/align_env/bin/python -c "import torch; print(f'PyTorch version: {torch.__version__}'); import transformers; print(f'Transformers version: {transformers.__version__}'); import alignscore; print('¡ÉXITO! AlignScore y sus dependencias se importaron correctamente.')"

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 GB 888.3 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.3/24.3 MB 80.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 KB 7.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 104.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 KB 9.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 116.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.8/129.8 KB 20.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.6/153.6 KB 24.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 159.4/159.4 KB 25.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 KB 11.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 116.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 129.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 149.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 829.5/829.5 KB 78.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 770.3/770.3 KB 62.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.1/566.1 KB 63.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 791.7/791.7 KB 71.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.2/507.2 KB 58.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 KB 12.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.0/201.0 KB 31.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.2/983.2 KB 85.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 509.2/509.2 KB 53.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 KB 35.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 347.8/347.8 KB 46.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.7/37.7 MB 50.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 92.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 137.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.0/31.0 MB 61.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 98.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 97.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.3/527.3 KB 59.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 133.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 109.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.2/193.2 KB 29.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.9/134.9 KB 21.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 39.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.6/177.6 KB 28.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 KB 22.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 130.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.3/108.3 KB 17.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 308.4/308.4 KB 44.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 780.3/780.3 KB 75.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.9/134.9 KB 21.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.7/229.7 KB 35.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 126.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.1/47.1 KB 8.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 89.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.6/122.6 KB 19.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 463.4/463.4 KB 55.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.8/50.8 KB 8.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 137.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.8/135.8 KB 21.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 136.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.7/107.7 KB 19.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 KB 32.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.0/983.0 KB 83.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.9/981.9 KB 87.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 963.5/963.5 KB 78.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 962.6/962.6 KB 83.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 962.5/962.5 KB 77.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 961.5/961.5 KB 83.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 960.9/960.9 KB 84.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 931.7/931.7 KB 84.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 931.6/931.6 KB 58.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 927.3/927.3 KB 80.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 926.4/926.4 KB 24.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 891.4/891.4 KB 79.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.9/196.9 KB 38.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 241.7/241.7 KB 34.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 219.5/219.5 KB 34.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 347.0/347.0 KB 45.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.6/67.6 KB 11.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 90.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 143.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 10.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.9/63.9 KB 10.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 KB 23.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 KB 21.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 113.7/113.7 KB 18.7 MB/s eta 0:00:00
  Building wheel for alignscore (pyproject.toml) ... done

--- Verificando el entorno virtual ---
Python 3.10.12
PyTorch version: 1.13.1+cu117
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]
Transformers version: 4.33.2
¡ÉXITO! AlignScore y sus dependencias se importaron correctamente.

In [ ]:
# --- Celda 2.3: Instalar AlignScore y Descargar el Modelo ---

# Usamos el pip que está DENTRO de nuestro entorno conda para instalar AlignScore
!/usr/local/envs/alignscore_env/bin/pip install -q pandas git+https://github.com/yuh-zha/AlignScore.git

# Clonar el repositorio para tener una estructura de carpetas predecible
!git clone https://github.com/yuh-zha/AlignScore.git

# Descargar el checkpoint del modelo en el directorio clonado
!cd /content/AlignScore/ && wget https://huggingface.co/yzha/AlignScore/resolve/main/AlignScore-base.ckpt

# Verificar que el archivo se descargó
!echo -e "\n--- Verificación de Archivos ---"
!ls -lh /content/AlignScore/

/bin/bash: line 1: /usr/local/envs/alignscore_env/bin/pip: No such file or directory
Cloning into 'AlignScore'...
remote: Enumerating objects: 202, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 202 (delta 36), reused 12 (delta 12), pack-reused 153 (from 1)
Receiving objects: 100% (202/202), 523.86 KiB | 14.55 MiB/s, done.
Resolving deltas: 100% (113/113), done.
--2025-11-20 17:51:08--  https://huggingface.co/yzha/AlignScore/resolve/main/AlignScore-base.ckpt
Resolving huggingface.co (huggingface.co)... 13.35.202.34, 13.35.202.121, 13.35.202.40, ...
Connecting to huggingface.co (huggingface.co)|13.35.202.34|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://us.gcp.cdn.hf.co/xet-bridge-us/647835e2159a889d001bebb4/a1ae41aa60f0f09954a2e05d43602df4f5edd951c2d85092bfc0002bc9a3f8c8?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27AlignScore-base.ckpt%3B+filename%3D%22AlignScore-base.ckpt%22%3B&Expires=1763664668&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiRXBvY2hUaW1lIjoxNzYzNjY0NjY4fX0sIlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjQ3ODM1ZTIxNTlhODg5ZDAwMWJlYmI0L2ExYWU0MWFhNjBmMGYwOTk1NGEyZTA1ZDQzNjAyZGY0ZjVlZGQ5NTFjMmQ4NTA5MmJmYzAwMDJiYzlhM2Y4YzhcXD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=a8bt1EYJv5A%7EgLiMffsnngxGhw2Y3FefQkpDT9Rmemtr2vwoV7A5RpUo5hAW46doSZ2xtXrQsjhSCx8BySRIgAw080ItkU7Gp1aklxkMlarh5vZQ8pfV5ASQAioo-NMNgnob9C82klMajH3%7EtYp2627E0SAdSMC6OrcaeWboFER3D2NpOxL7BddMRZqxySm2qWHljihCU5yrQzqn21jqItrQl30DCPmkFa0EyXDb3dh02nYClG%7Euumu-%7EmstCYKPUgAP1LR4H0dfIkfPuLJk15FPW2HNSYXLjRb10glwoyH%7E5WbBhW%7EDbTOVuxZO3EdUp8N2yDM6FsBcnj7PV%7ElGUg__&Key-Pair-Id=KJLH8B0YWU4Y8M [following]
--2025-11-20 17:51:08--  https://us.gcp.cdn.hf.co/xet-bridge-us/647835e2159a889d001bebb4/a1ae41aa60f0f09954a2e05d43602df4f5edd951c2d85092bfc0002bc9a3f8c8?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27AlignScore-base.ckpt%3B+filename%3D%22AlignScore-base.ckpt%22%3B&Expires=1763664668&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiRXBvY2hUaW1lIjoxNzYzNjY0NjY4fX0sIlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjQ3ODM1ZTIxNTlhODg5ZDAwMWJlYmI0L2ExYWU0MWFhNjBmMGYwOTk1NGEyZTA1ZDQzNjAyZGY0ZjVlZGQ5NTFjMmQ4NTA5MmJmYzAwMDJiYzlhM2Y4YzhcXD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=a8bt1EYJv5A%7EgLiMffsnngxGhw2Y3FefQkpDT9Rmemtr2vwoV7A5RpUo5hAW46doSZ2xtXrQsjhSCx8BySRIgAw080ItkU7Gp1aklxkMlarh5vZQ8pfV5ASQAioo-NMNgnob9C82klMajH3%7EtYp2627E0SAdSMC6OrcaeWboFER3D2NpOxL7BddMRZqxySm2qWHljihCU5yrQzqn21jqItrQl30DCPmkFa0EyXDb3dh02nYClG%7Euumu-%7EmstCYKPUgAP1LR4H0dfIkfPuLJk15FPW2HNSYXLjRb10glwoyH%7E5WbBhW%7EDbTOVuxZO3EdUp8N2yDM6FsBcnj7PV%7ElGUg__&Key-Pair-Id=KJLH8B0YWU4Y8M
Resolving us.gcp.cdn.hf.co (us.gcp.cdn.hf.co)... 34.120.165.110
Connecting to us.gcp.cdn.hf.co (us.gcp.cdn.hf.co)|34.120.165.110|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1966965771 (1.8G) [application/octet-stream]
Saving to: ‘AlignScore-base.ckpt’

AlignScore-base.ckp  13%[=>                  ] 255.87M  9.17MB/s    in 35s

2025-11-20 17:51:44 (7.21 MB/s) - Connection closed at byte 268298141. Retrying.

--2025-11-20 17:51:45--  (try: 2)  https://us.gcp.cdn.hf.co/xet-bridge-us/647835e2159a889d001bebb4/a1ae41aa60f0f09954a2e05d43602df4f5edd951c2d85092bfc0002bc9a3f8c8?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27AlignScore-base.ckpt%3B+filename%3D%22AlignScore-base.ckpt%22%3B&Expires=1763664668&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiRXBvY2hUaW1lIjoxNzYzNjY0NjY4fX0sIlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjQ3ODM1ZTIxNTlhODg5ZDAwMWJlYmI0L2ExYWU0MWFhNjBmMGYwOTk1NGEyZTA1ZDQzNjAyZGY0ZjVlZGQ5NTFjMmQ4NTA5MmJmYzAwMDJiYzlhM2Y4YzhcXD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=a8bt1EYJv5A%7EgLiMffsnngxGhw2Y3FefQkpDT9Rmemtr2vwoV7A5RpUo5hAW46doSZ2xtXrQsjhSCx8BySRIgAw080ItkU7Gp1aklxkMlarh5vZQ8pfV5ASQAioo-NMNgnob9C82klMajH3%7EtYp2627E0SAdSMC6OrcaeWboFER3D2NpOxL7BddMRZqxySm2qWHljihCU5yrQzqn21jqItrQl30DCPmkFa0EyXDb3dh02nYClG%7Euumu-%7EmstCYKPUgAP1LR4H0dfIkfPuLJk15FPW2HNSYXLjRb10glwoyH%7E5WbBhW%7EDbTOVuxZO3EdUp8N2yDM6FsBcnj7PV%7ElGUg__&Key-Pair-Id=KJLH8B0YWU4Y8M
Connecting to us.gcp.cdn.hf.co (us.gcp.cdn.hf.co)|34.120.165.110|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 1966965771 (1.8G), 1698667630 (1.6G) remaining [application/octet-stream]
Saving to: ‘AlignScore-base.ckpt’

AlignScore-base.ckp  13%[++                  ] 255.87M  --.-KB/s    in 29s

2025-11-20 17:52:15 (0.00 B/s) - Connection closed at byte 268298141. Retrying.

--2025-11-20 17:52:17--  (try: 3)  https://us.gcp.cdn.hf.co/xet-bridge-us/647835e2159a889d001bebb4/a1ae41aa60f0f09954a2e05d43602df4f5edd951c2d85092bfc0002bc9a3f8c8?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27AlignScore-base.ckpt%3B+filename%3D%22AlignScore-base.ckpt%22%3B&Expires=1763664668&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiRXBvY2hUaW1lIjoxNzYzNjY0NjY4fX0sIlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjQ3ODM1ZTIxNTlhODg5ZDAwMWJlYmI0L2ExYWU0MWFhNjBmMGYwOTk1NGEyZTA1ZDQzNjAyZGY0ZjVlZGQ5NTFjMmQ4NTA5MmJmYzAwMDJiYzlhM2Y4YzhcXD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=a8bt1EYJv5A%7EgLiMffsnngxGhw2Y3FefQkpDT9Rmemtr2vwoV7A5RpUo5hAW46doSZ2xtXrQsjhSCx8BySRIgAw080ItkU7Gp1aklxkMlarh5vZQ8pfV5ASQAioo-NMNgnob9C82klMajH3%7EtYp2627E0SAdSMC6OrcaeWboFER3D2NpOxL7BddMRZqxySm2qWHljihCU5yrQzqn21jqItrQl30DCPmkFa0EyXDb3dh02nYClG%7Euumu-%7EmstCYKPUgAP1LR4H0dfIkfPuLJk15FPW2HNSYXLjRb10glwoyH%7E5WbBhW%7EDbTOVuxZO3EdUp8N2yDM6FsBcnj7PV%7ElGUg__&Key-Pair-Id=KJLH8B0YWU4Y8M
Connecting to us.gcp.cdn.hf.co (us.gcp.cdn.hf.co)|34.120.165.110|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 1966965771 (1.8G), 1698667630 (1.6G) remaining [application/octet-stream]
Saving to: ‘AlignScore-base.ckpt’

AlignScore-base.ckp  13%[++                  ] 255.87M  --.-KB/s    in 29s

2025-11-20 17:52:47 (0.00 B/s) - Connection closed at byte 268298141. Retrying.

--2025-11-20 17:52:50--  (try: 4)  https://us.gcp.cdn.hf.co/xet-bridge-us/647835e2159a889d001bebb4/a1ae41aa60f0f09954a2e05d43602df4f5edd951c2d85092bfc0002bc9a3f8c8?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27AlignScore-base.ckpt%3B+filename%3D%22AlignScore-base.ckpt%22%3B&Expires=1763664668&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiRXBvY2hUaW1lIjoxNzYzNjY0NjY4fX0sIlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjQ3ODM1ZTIxNTlhODg5ZDAwMWJlYmI0L2ExYWU0MWFhNjBmMGYwOTk1NGEyZTA1ZDQzNjAyZGY0ZjVlZGQ5NTFjMmQ4NTA5MmJmYzAwMDJiYzlhM2Y4YzhcXD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=a8bt1EYJv5A%7EgLiMffsnngxGhw2Y3FefQkpDT9Rmemtr2vwoV7A5RpUo5hAW46doSZ2xtXrQsjhSCx8BySRIgAw080ItkU7Gp1aklxkMlarh5vZQ8pfV5ASQAioo-NMNgnob9C82klMajH3%7EtYp2627E0SAdSMC6OrcaeWboFER3D2NpOxL7BddMRZqxySm2qWHljihCU5yrQzqn21jqItrQl30DCPmkFa0EyXDb3dh02nYClG%7Euumu-%7EmstCYKPUgAP1LR4H0dfIkfPuLJk15FPW2HNSYXLjRb10glwoyH%7E5WbBhW%7EDbTOVuxZO3EdUp8N2yDM6FsBcnj7PV%7ElGUg__&Key-Pair-Id=KJLH8B0YWU4Y8M
Connecting to us.gcp.cdn.hf.co (us.gcp.cdn.hf.co)|34.120.165.110|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 1966965771 (1.8G), 1698667630 (1.6G) remaining [application/octet-stream]
Saving to: ‘AlignScore-base.ckpt’

AlignScore-base.ckp  30%[++===>              ] 575.69M  11.1MB/s    in 38s

2025-11-20 17:53:28 (8.47 MB/s) - Connection closed at byte 603654568. Retrying.

--2025-11-20 17:53:32--  (try: 5)  https://us.gcp.cdn.hf.co/xet-bridge-us/647835e2159a889d001bebb4/a1ae41aa60f0f09954a2e05d43602df4f5edd951c2d85092bfc0002bc9a3f8c8?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27AlignScore-base.ckpt%3B+filename%3D%22AlignScore-base.ckpt%22%3B&Expires=1763664668&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiRXBvY2hUaW1lIjoxNzYzNjY0NjY4fX0sIlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjQ3ODM1ZTIxNTlhODg5ZDAwMWJlYmI0L2ExYWU0MWFhNjBmMGYwOTk1NGEyZTA1ZDQzNjAyZGY0ZjVlZGQ5NTFjMmQ4NTA5MmJmYzAwMDJiYzlhM2Y4YzhcXD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=a8bt1EYJv5A%7EgLiMffsnngxGhw2Y3FefQkpDT9Rmemtr2vwoV7A5RpUo5hAW46doSZ2xtXrQsjhSCx8BySRIgAw080ItkU7Gp1aklxkMlarh5vZQ8pfV5ASQAioo-NMNgnob9C82klMajH3%7EtYp2627E0SAdSMC6OrcaeWboFER3D2NpOxL7BddMRZqxySm2qWHljihCU5yrQzqn21jqItrQl30DCPmkFa0EyXDb3dh02nYClG%7Euumu-%7EmstCYKPUgAP1LR4H0dfIkfPuLJk15FPW2HNSYXLjRb10glwoyH%7E5WbBhW%7EDbTOVuxZO3EdUp8N2yDM6FsBcnj7PV%7ElGUg__&Key-Pair-Id=KJLH8B0YWU4Y8M
Connecting to us.gcp.cdn.hf.co (us.gcp.cdn.hf.co)|34.120.165.110|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 1966965771 (1.8G), 1363311203 (1.3G) remaining [application/octet-stream]
Saving to: ‘AlignScore-base.ckpt’

AlignScore-base.ckp  30%[++++++              ] 575.69M  --.-KB/s    in 29s

2025-11-20 17:54:02 (0.00 B/s) - Connection closed at byte 603654568. Retrying.

--2025-11-20 17:54:07--  (try: 6)  https://us.gcp.cdn.hf.co/xet-bridge-us/647835e2159a889d001bebb4/a1ae41aa60f0f09954a2e05d43602df4f5edd951c2d85092bfc0002bc9a3f8c8?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27AlignScore-base.ckpt%3B+filename%3D%22AlignScore-base.ckpt%22%3B&Expires=1763664668&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiRXBvY2hUaW1lIjoxNzYzNjY0NjY4fX0sIlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjQ3ODM1ZTIxNTlhODg5ZDAwMWJlYmI0L2ExYWU0MWFhNjBmMGYwOTk1NGEyZTA1ZDQzNjAyZGY0ZjVlZGQ5NTFjMmQ4NTA5MmJmYzAwMDJiYzlhM2Y4YzhcXD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=a8bt1EYJv5A%7EgLiMffsnngxGhw2Y3FefQkpDT9Rmemtr2vwoV7A5RpUo5hAW46doSZ2xtXrQsjhSCx8BySRIgAw080ItkU7Gp1aklxkMlarh5vZQ8pfV5ASQAioo-NMNgnob9C82klMajH3%7EtYp2627E0SAdSMC6OrcaeWboFER3D2NpOxL7BddMRZqxySm2qWHljihCU5yrQzqn21jqItrQl30DCPmkFa0EyXDb3dh02nYClG%7Euumu-%7EmstCYKPUgAP1LR4H0dfIkfPuLJk15FPW2HNSYXLjRb10glwoyH%7E5WbBhW%7EDbTOVuxZO3EdUp8N2yDM6FsBcnj7PV%7ElGUg__&Key-Pair-Id=KJLH8B0YWU4Y8M
Connecting to us.gcp.cdn.hf.co (us.gcp.cdn.hf.co)|34.120.165.110|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 1966965771 (1.8G), 1363311203 (1.3G) remaining [application/octet-stream]
Saving to: ‘AlignScore-base.ckpt’

AlignScore-base.ckp  30%[++++++              ] 575.69M  --.-KB/s    in 29s

2025-11-20 17:54:38 (0.00 B/s) - Connection closed at byte 603654568. Retrying.

--2025-11-20 17:54:44--  (try: 7)  https://us.gcp.cdn.hf.co/xet-bridge-us/647835e2159a889d001bebb4/a1ae41aa60f0f09954a2e05d43602df4f5edd951c2d85092bfc0002bc9a3f8c8?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27AlignScore-base.ckpt%3B+filename%3D%22AlignScore-base.ckpt%22%3B&Expires=1763664668&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiRXBvY2hUaW1lIjoxNzYzNjY0NjY4fX0sIlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjQ3ODM1ZTIxNTlhODg5ZDAwMWJlYmI0L2ExYWU0MWFhNjBmMGYwOTk1NGEyZTA1ZDQzNjAyZGY0ZjVlZGQ5NTFjMmQ4NTA5MmJmYzAwMDJiYzlhM2Y4YzhcXD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=a8bt1EYJv5A%7EgLiMffsnngxGhw2Y3FefQkpDT9Rmemtr2vwoV7A5RpUo5hAW46doSZ2xtXrQsjhSCx8BySRIgAw080ItkU7Gp1aklxkMlarh5vZQ8pfV5ASQAioo-NMNgnob9C82klMajH3%7EtYp2627E0SAdSMC6OrcaeWboFER3D2NpOxL7BddMRZqxySm2qWHljihCU5yrQzqn21jqItrQl30DCPmkFa0EyXDb3dh02nYClG%7Euumu-%7EmstCYKPUgAP1LR4H0dfIkfPuLJk15FPW2HNSYXLjRb10glwoyH%7E5WbBhW%7EDbTOVuxZO3EdUp8N2yDM6FsBcnj7PV%7ElGUg__&Key-Pair-Id=KJLH8B0YWU4Y8M
Connecting to us.gcp.cdn.hf.co (us.gcp.cdn.hf.co)|34.120.165.110|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 1966965771 (1.8G), 1363311203 (1.3G) remaining [application/octet-stream]
Saving to: ‘AlignScore-base.ckpt’

AlignScore-base.ckp  47%[++++++==>           ] 895.48M  12.6MB/s    in 36s

2025-11-20 17:55:21 (8.81 MB/s) - Connection closed at byte 938976830. Retrying.

--2025-11-20 17:55:28--  (try: 8)  https://us.gcp.cdn.hf.co/xet-bridge-us/647835e2159a889d001bebb4/a1ae41aa60f0f09954a2e05d43602df4f5edd951c2d85092bfc0002bc9a3f8c8?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27AlignScore-base.ckpt%3B+filename%3D%22AlignScore-base.ckpt%22%3B&Expires=1763664668&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiRXBvY2hUaW1lIjoxNzYzNjY0NjY4fX0sIlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjQ3ODM1ZTIxNTlhODg5ZDAwMWJlYmI0L2ExYWU0MWFhNjBmMGYwOTk1NGEyZTA1ZDQzNjAyZGY0ZjVlZGQ5NTFjMmQ4NTA5MmJmYzAwMDJiYzlhM2Y4YzhcXD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=a8bt1EYJv5A%7EgLiMffsnngxGhw2Y3FefQkpDT9Rmemtr2vwoV7A5RpUo5hAW46doSZ2xtXrQsjhSCx8BySRIgAw080ItkU7Gp1aklxkMlarh5vZQ8pfV5ASQAioo-NMNgnob9C82klMajH3%7EtYp2627E0SAdSMC6OrcaeWboFER3D2NpOxL7BddMRZqxySm2qWHljihCU5yrQzqn21jqItrQl30DCPmkFa0EyXDb3dh02nYClG%7Euumu-%7EmstCYKPUgAP1LR4H0dfIkfPuLJk15FPW2HNSYXLjRb10glwoyH%7E5WbBhW%7EDbTOVuxZO3EdUp8N2yDM6FsBcnj7PV%7ElGUg__&Key-Pair-Id=KJLH8B0YWU4Y8M
Connecting to us.gcp.cdn.hf.co (us.gcp.cdn.hf.co)|34.120.165.110|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 1966965771 (1.8G), 1027988941 (980M) remaining [application/octet-stream]
Saving to: ‘AlignScore-base.ckpt’

AlignScore-base.ckp  47%[+++++++++           ] 895.48M  --.-KB/s    in 29s

2025-11-20 17:55:59 (0.00 B/s) - Connection closed at byte 938976830. Retrying.

--2025-11-20 17:56:07--  (try: 9)  https://us.gcp.cdn.hf.co/xet-bridge-us/647835e2159a889d001bebb4/a1ae41aa60f0f09954a2e05d43602df4f5edd951c2d85092bfc0002bc9a3f8c8?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27AlignScore-base.ckpt%3B+filename%3D%22AlignScore-base.ckpt%22%3B&Expires=1763664668&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiRXBvY2hUaW1lIjoxNzYzNjY0NjY4fX0sIlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjQ3ODM1ZTIxNTlhODg5ZDAwMWJlYmI0L2ExYWU0MWFhNjBmMGYwOTk1NGEyZTA1ZDQzNjAyZGY0ZjVlZGQ5NTFjMmQ4NTA5MmJmYzAwMDJiYzlhM2Y4YzhcXD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=a8bt1EYJv5A%7EgLiMffsnngxGhw2Y3FefQkpDT9Rmemtr2vwoV7A5RpUo5hAW46doSZ2xtXrQsjhSCx8BySRIgAw080ItkU7Gp1aklxkMlarh5vZQ8pfV5ASQAioo-NMNgnob9C82klMajH3%7EtYp2627E0SAdSMC6OrcaeWboFER3D2NpOxL7BddMRZqxySm2qWHljihCU5yrQzqn21jqItrQl30DCPmkFa0EyXDb3dh02nYClG%7Euumu-%7EmstCYKPUgAP1LR4H0dfIkfPuLJk15FPW2HNSYXLjRb10glwoyH%7E5WbBhW%7EDbTOVuxZO3EdUp8N2yDM6FsBcnj7PV%7ElGUg__&Key-Pair-Id=KJLH8B0YWU4Y8M
Connecting to us.gcp.cdn.hf.co (us.gcp.cdn.hf.co)|34.120.165.110|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 1966965771 (1.8G), 1027988941 (980M) remaining [application/octet-stream]
Saving to: ‘AlignScore-base.ckpt’

AlignScore-base.ckp  47%[+++++++++           ] 895.48M  --.-KB/s    in 29s

2025-11-20 17:56:37 (0.00 B/s) - Connection closed at byte 938976830. Retrying.

--2025-11-20 17:56:46--  (try:10)  https://us.gcp.cdn.hf.co/xet-bridge-us/647835e2159a889d001bebb4/a1ae41aa60f0f09954a2e05d43602df4f5edd951c2d85092bfc0002bc9a3f8c8?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27AlignScore-base.ckpt%3B+filename%3D%22AlignScore-base.ckpt%22%3B&Expires=1763664668&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiRXBvY2hUaW1lIjoxNzYzNjY0NjY4fX0sIlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjQ3ODM1ZTIxNTlhODg5ZDAwMWJlYmI0L2ExYWU0MWFhNjBmMGYwOTk1NGEyZTA1ZDQzNjAyZGY0ZjVlZGQ5NTFjMmQ4NTA5MmJmYzAwMDJiYzlhM2Y4YzhcXD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=a8bt1EYJv5A%7EgLiMffsnngxGhw2Y3FefQkpDT9Rmemtr2vwoV7A5RpUo5hAW46doSZ2xtXrQsjhSCx8BySRIgAw080ItkU7Gp1aklxkMlarh5vZQ8pfV5ASQAioo-NMNgnob9C82klMajH3%7EtYp2627E0SAdSMC6OrcaeWboFER3D2NpOxL7BddMRZqxySm2qWHljihCU5yrQzqn21jqItrQl30DCPmkFa0EyXDb3dh02nYClG%7Euumu-%7EmstCYKPUgAP1LR4H0dfIkfPuLJk15FPW2HNSYXLjRb10glwoyH%7E5WbBhW%7EDbTOVuxZO3EdUp8N2yDM6FsBcnj7PV%7ElGUg__&Key-Pair-Id=KJLH8B0YWU4Y8M
Connecting to us.gcp.cdn.hf.co (us.gcp.cdn.hf.co)|34.120.165.110|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 1966965771 (1.8G), 1027988941 (980M) remaining [application/octet-stream]
Saving to: ‘AlignScore-base.ckpt’

AlignScore-base.ckp  64%[+++++++++==>        ]   1.19G  13.4MB/s    in 38s

2025-11-20 17:57:24 (8.36 MB/s) - Connection closed at byte 1274136339. Retrying.

--2025-11-20 17:57:34--  (try:11)  https://us.gcp.cdn.hf.co/xet-bridge-us/647835e2159a889d001bebb4/a1ae41aa60f0f09954a2e05d43602df4f5edd951c2d85092bfc0002bc9a3f8c8?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27AlignScore-base.ckpt%3B+filename%3D%22AlignScore-base.ckpt%22%3B&Expires=1763664668&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiRXBvY2hUaW1lIjoxNzYzNjY0NjY4fX0sIlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjQ3ODM1ZTIxNTlhODg5ZDAwMWJlYmI0L2ExYWU0MWFhNjBmMGYwOTk1NGEyZTA1ZDQzNjAyZGY0ZjVlZGQ5NTFjMmQ4NTA5MmJmYzAwMDJiYzlhM2Y4YzhcXD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=a8bt1EYJv5A%7EgLiMffsnngxGhw2Y3FefQkpDT9Rmemtr2vwoV7A5RpUo5hAW46doSZ2xtXrQsjhSCx8BySRIgAw080ItkU7Gp1aklxkMlarh5vZQ8pfV5ASQAioo-NMNgnob9C82klMajH3%7EtYp2627E0SAdSMC6OrcaeWboFER3D2NpOxL7BddMRZqxySm2qWHljihCU5yrQzqn21jqItrQl30DCPmkFa0EyXDb3dh02nYClG%7Euumu-%7EmstCYKPUgAP1LR4H0dfIkfPuLJk15FPW2HNSYXLjRb10glwoyH%7E5WbBhW%7EDbTOVuxZO3EdUp8N2yDM6FsBcnj7PV%7ElGUg__&Key-Pair-Id=KJLH8B0YWU4Y8M
Connecting to us.gcp.cdn.hf.co (us.gcp.cdn.hf.co)|34.120.165.110|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 1966965771 (1.8G), 692829432 (661M) remaining [application/octet-stream]
Saving to: ‘AlignScore-base.ckpt’

AlignScore-base.ckp  64%[++++++++++++        ]   1.19G  --.-KB/s    in 29s

2025-11-20 17:58:04 (0.00 B/s) - Connection closed at byte 1274136339. Retrying.

--2025-11-20 17:58:14--  (try:12)  https://us.gcp.cdn.hf.co/xet-bridge-us/647835e2159a889d001bebb4/a1ae41aa60f0f09954a2e05d43602df4f5edd951c2d85092bfc0002bc9a3f8c8?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27AlignScore-base.ckpt%3B+filename%3D%22AlignScore-base.ckpt%22%3B&Expires=1763664668&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiRXBvY2hUaW1lIjoxNzYzNjY0NjY4fX0sIlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjQ3ODM1ZTIxNTlhODg5ZDAwMWJlYmI0L2ExYWU0MWFhNjBmMGYwOTk1NGEyZTA1ZDQzNjAyZGY0ZjVlZGQ5NTFjMmQ4NTA5MmJmYzAwMDJiYzlhM2Y4YzhcXD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=a8bt1EYJv5A%7EgLiMffsnngxGhw2Y3FefQkpDT9Rmemtr2vwoV7A5RpUo5hAW46doSZ2xtXrQsjhSCx8BySRIgAw080ItkU7Gp1aklxkMlarh5vZQ8pfV5ASQAioo-NMNgnob9C82klMajH3%7EtYp2627E0SAdSMC6OrcaeWboFER3D2NpOxL7BddMRZqxySm2qWHljihCU5yrQzqn21jqItrQl30DCPmkFa0EyXDb3dh02nYClG%7Euumu-%7EmstCYKPUgAP1LR4H0dfIkfPuLJk15FPW2HNSYXLjRb10glwoyH%7E5WbBhW%7EDbTOVuxZO3EdUp8N2yDM6FsBcnj7PV%7ElGUg__&Key-Pair-Id=KJLH8B0YWU4Y8M
Connecting to us.gcp.cdn.hf.co (us.gcp.cdn.hf.co)|34.120.165.110|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 1966965771 (1.8G), 692829432 (661M) remaining [application/octet-stream]
Saving to: ‘AlignScore-base.ckpt’

AlignScore-base.ckp  64%[++++++++++++        ]   1.19G  --.-KB/s    in 29s

2025-11-20 17:58:44 (0.00 B/s) - Connection closed at byte 1274136339. Retrying.


In [ ]:
# 4. ¡NUEVO PASO! Descargamos el modelo de spaCy USANDO el python del entorno virtual.
#    Esto asegura que el modelo sea visible para el script.
!/content/align_env/bin/python -m spacy download en_core_web_sm

# --- Verificación ---
print("\n--- Verificando el entorno virtual ---")
!/content/align_env/bin/python --version
# La verificación ahora también comprueba que spacy puede cargar el modelo.
!/content/align_env/bin/python -c "import torch; print(f'PyTorch version: {torch.__version__}'); import transformers; print(f'Transformers version: {transformers.__version__}'); import alignscore; import spacy; nlp=spacy.load('en_core_web_sm'); print('¡ÉXITO! Todas las dependencias, incluyendo spaCy, se importaron y cargaron correctamente.')"

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 106.1 MB/s eta 0:00:00
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

--- Verificando el entorno virtual ---
Python 3.10.12
PyTorch version: 1.13.1+cu117
Transformers version: 4.33.2
¡ÉXITO! Todas las dependencias, incluyendo spaCy, se importaron y cargaron correctamente.

In [ ]:
# --- Celda 2.4: Escribir el Script de Ejecución (VERSIÓN OPTIMIZADA) ---

# 2. Escribir todo nuestro código de Python en un archivo para ejecutarlo con el venv.
%%writefile run_alignscore_evaluation.py

# Se importan todas las librerías necesarias DENTRO del script
import os
import pandas as pd
import numpy as np
import torch
from tqdm.auto import tqdm
from alignscore import AlignScore
import nltk
nltk.download('punkt_tab')

print("--- Script de evaluación optimizado iniciado ---")

# --- Configuración Global ---
BASE_PROJECT_DIR = "/content/drive/MyDrive/NLP_Project_MedGemma"
BASE_ALIGNSCORE_DIR = "/content/AlignScore"

CSV_RESULTS_PATH = os.path.join(BASE_PROJECT_DIR, 'v8_foundation_model_pls_results.csv')
INTERMEDIATE_CSV_PATH = os.path.join(BASE_PROJECT_DIR, 'v8_intermediate_metrics.csv')
FINAL_CSV_PATH = os.path.join(BASE_PROJECT_DIR, 'v8_final_combined_metrics.csv')
ALIGN_SCORE_CKPT_PATH = os.path.join(BASE_ALIGNSCORE_DIR, 'AlignScore-base.ckpt')

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Usando dispositivo: {DEVICE}")
print(f"Versión de PyTorch detectada: {torch.__version__}")

# --- Cargar AlignScore ---
print("\nInicializando AlignScore...")
# Aumenta el batch_size si tienes una GPU potente como la A100 (ej. 32 o 64)
alignscore_evaluator = AlignScore(
    model='roberta-large', batch_size=64, device=DEVICE,
    ckpt_path=ALIGN_SCORE_CKPT_PATH, evaluation_mode='nli_sp'
)
print("AlignScore cargado exitosamente.")

# --- Lógica de Cálculo Optimizada ---
try:
    df_original = pd.read_csv(CSV_RESULTS_PATH)
    df_original.dropna(subset=['technical_text', 'reference_summary'], inplace=True)

    # Renombrar generated_summary por medgemma_pls
    if 'generated_summary' in df_original.columns:
      df_original.rename(columns={'generated_summary': 'medgemma_pls'}, inplace=True)

    model_columns = [col for col in df_original.columns if '_pls' in col]
    df_intermediate = pd.read_csv(INTERMEDIATE_CSV_PATH)

    # Renombrar generated_summary por medgemma_pls
    if 'generated_summary' in df_intermediate.columns:
        df_intermediate.rename(columns={'generated_summary': 'medgemma_pls'}, inplace=True)

    print(f"\nModelos a procesar: {model_columns}")

    # --- 1. Preparación: Recolectar TODOS los datos de TODOS los modelos ---
    print("\nPreparando datos de todos los modelos para un único procesamiento...")
    all_sources = []
    all_predictions = []
    prediction_counts_per_model = {} # Para reconstruir los scores

    for model_name in tqdm(model_columns, desc="Recolectando predicciones"):
        temp_df = df_original[['technical_text', model_name]].copy()
        temp_df.dropna(subset=[model_name], inplace=True)
        temp_df = temp_df[temp_df[model_name].str.strip() != '']

        if temp_df.empty:
            prediction_counts_per_model[model_name] = 0
            continue

        sources = temp_df['technical_text'].tolist()
        predictions = temp_df[model_name].tolist()

        all_sources.extend(sources)
        all_predictions.extend(predictions)
        prediction_counts_per_model[model_name] = len(predictions)

    # --- 2. Ejecución: Calcular TODOS los scores en una única llamada masiva ---
    if not all_predictions:
        print("No se encontraron predicciones válidas en ningún modelo.")
        all_scores = []
    else:
        print(f"\nCalculando AlignScore para {len(all_predictions)} pares (fuente, predicción) en total...")
        # La librería AlignScore se encarga internamente del batching de esta gran lista
        all_scores = alignscore_evaluator.score(contexts=all_sources, claims=all_predictions)

    # --- 3. Re-agregación: Distribuir los scores de vuelta a cada modelo ---
    print("\nAgregando y asignando scores a sus respectivos modelos...")
    alignscore_results = []
    current_score_idx = 0
    for model_name in model_columns:
        count = prediction_counts_per_model.get(model_name, 0)

        if count == 0:
            # Asignar un score de 0 si el modelo no tuvo predicciones válidas
            score = 0.0
        else:
            model_scores = all_scores[current_score_idx : current_score_idx + count]
            score = np.mean(model_scores)
            current_score_idx += count # Mover el puntero

        alignscore_results.append({'model': model_name, 'metric': 'alignscore', 'score': score})
        print(f"Score final para {model_name}: {score:.4f}")

    # --- 4. Combinar y Guardar Resultados ---
    df_alignscore = pd.DataFrame(alignscore_results)
    df_final_metrics = pd.concat([df_intermediate, df_alignscore], ignore_index=True)

    df_final_metrics.to_csv(FINAL_CSV_PATH, index=False)
    print(f"\n¡Éxito! Resultados combinados guardados en: {FINAL_CSV_PATH}")

except FileNotFoundError as e:
    print(f"\nERROR: No se pudo encontrar un archivo necesario: {e}")
except Exception as e:
    print(f"\nOcurrió un error inesperado durante la ejecución: {e}")
finally:
    print("--- Script de evaluación finalizado ---")

Overwriting run_alignscore_evaluation.py

In [ ]:
# --- Celda 2.5: Ejecutar el Script y Generar el Reporte Final ---

# 1. Ejecutar el script completo usando el intérprete de Python de nuestro entorno virtual.
#    Toda la lógica que depende de AlignScore ocurre aquí.
print("="*80)
print("Iniciando la ejecución del script de evaluación en el entorno virtual...")
print("="*80)
!/content/align_env/bin/python run_alignscore_evaluation.py
print("="*80)
print("...Ejecución del script finalizada.")
print("="*80)


# 2. Ahora, de vuelta en el kernel de Colab, cargamos el archivo de resultados
#    que el script acaba de crear.
FINAL_CSV_PATH = "/content/drive/MyDrive/NLP_Project_MedGemma/v8_final_combined_metrics.csv"
try:
    final_pivot = pd.read_csv(FINAL_CSV_PATH).pivot(index='metric', columns='model', values='score')

    # 3. Generar la tabla de reporte final (esto se ejecuta en el kernel de Colab)
    metric_map = {
        'bertscore_f1': 'BERTScore - F1', 'alignscore': 'AlignScore (NLI_SP)',
        'nli_factuality': 'Factualidad (1 - Contradiction Ratio)', 'qa_factuality': 'Factualidad (QA Answerability)',
        'readability_fkgl': 'Flesch-Kincaid Grade', 'readability_fre': 'Flesch Reading Ease',
        'readability_fog': 'Gunning Fog Index', 'readability_smog': 'SMOG Index',
        'readability_cl': 'Coleman-Liau Index',
    }
    metric_order = [
        'bertscore_f1', 'alignscore', 'nli_factuality', 'qa_factuality', '---',
        'readability_fkgl', 'readability_fre', 'readability_fog', 'readability_smog', 'readability_cl'
    ]
    targets = ['≥ 0.86', '≥ 0.80', '≥ 0.90', '≥ 0.80', '', '≤ 8.0', '≥ 60', '≤ 12.0', '≤ 8.0', '≤ 8.0']

    report_df = pd.DataFrame({'Métrica': [metric_map.get(m, '---') for m in metric_order], 'Meta / Objetivo': targets})
    def get_score(metric, model):
        try: return final_pivot.loc[metric, model]
        except KeyError: return 'N/A'

    report_df['PLS Reales (Referencia)'] = [
        'N/A', 'N/A', 'N/A', 'N/A', '',
        f"{get_score('readability_fkgl', 'reference_summary'):.2f}", f"{get_score('readability_fre', 'reference_summary'):.2f}",
        f"{get_score('readability_fog', 'reference_summary'):.2f}", f"{get_score('readability_smog', 'reference_summary'):.2f}",
        f"{get_score('readability_cl', 'reference_summary'):.2f}",
    ]
    model_columns = sorted([col for col in final_pivot.columns if col != 'reference_summary'])
    for model_name in model_columns:
        report_df[model_name] = [
            f"{get_score('bertscore_f1', model_name):.4f}", f"{get_score('alignscore', model_name):.4f}",
            f"{get_score('nli_factuality', model_name):.4f}", f"{get_score('qa_factuality', model_name):.4f}", '',
            f"{get_score('readability_fkgl', model_name):.2f}", f"{get_score('readability_fre', model_name):.2f}",
            f"{get_score('readability_fog', model_name):.2f}", f"{get_score('readability_smog', model_name):.2f}",
            f"{get_score('readability_cl', model_name):.2f}",
        ]

    # --- Mostrar la Tabla Final ---
    print("\n\n" + "="*100)
    print("--- Tabla Comparativa Final de Resultados de Evaluación (Combinada) ---")
    print("="*100)
    print(report_df.to_string(index=False))
    print("="*100)

except FileNotFoundError:
    print(f"\nERROR CRÍTICO: No se encontró el archivo de salida en {FINAL_CSV_PATH}.")
    print("Revisa la salida del script anterior para ver si hubo errores durante su ejecución.")

================================================================================
Iniciando la ejecución del script de evaluación en el entorno virtual...
================================================================================
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
--- Script de evaluación optimizado iniciado ---
Usando dispositivo: cuda
Versión de PyTorch detectada: 1.13.1+cu117

Inicializando AlignScore...
/content/align_env/lib/python3.10/site-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Lightning automatically upgraded your loaded checkpoint from v1.7.7 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file AlignScore/AlignScore-base.ckpt`
Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/content/align_env/lib/python3.10/site-packages/pytorch_lightning/core/saving.py:255: UserWarning: Found keys that are not in the model state dict but in the checkpoint: ['base_model.embeddings.position_ids']
  rank_zero_warn(
AlignScore cargado exitosamente.

Modelos a procesar: ['medgemma_pls', 'qwen_pls', 'gemini_pls', 'llama_pls']

Preparando datos de todos los modelos para un único procesamiento...
Recolectando predicciones: 100% 4/4 [00:00<00:00, 456.54it/s]

Calculando AlignScore para 400 pares (fuente, predicción) en total...
Evaluating:   6% 22/400 [00:11<03:03,  2.06it/s]WARNING:root:text_b too long...
Evaluating: 100% 400/400 [03:44<00:00,  1.78it/s]

Agregando y asignando scores a sus respectivos modelos...
Score final para medgemma_pls: 0.6023
Score final para qwen_pls: 0.2733
Score final para gemini_pls: 0.5911
Score final para llama_pls: 0.5538

¡Éxito! Resultados combinados guardados en: /content/drive/MyDrive/NLP_Project_MedGemma/v8_final_combined_metrics.csv
--- Script de evaluación finalizado ---
================================================================================
...Ejecución del script finalizada.
================================================================================


====================================================================================================
--- Tabla Comparativa Final de Resultados de Evaluación (Combinada) ---
====================================================================================================
                              Métrica Meta / Objetivo PLS Reales (Referencia) gemini_pls llama_pls medgemma_pls qwen_pls
                       BERTScore - F1          ≥ 0.86                     N/A     0.8584    0.8566       0.8522   0.8288
                  AlignScore (NLI_SP)          ≥ 0.80                     N/A     0.5911    0.5538       0.6023   0.2733
Factualidad (1 - Contradiction Ratio)          ≥ 0.90                     N/A     0.9525    0.9732       0.9770   0.9397
       Factualidad (QA Answerability)          ≥ 0.80                     N/A     0.2085    0.1806       0.1602   0.0838
                                  ---
                 Flesch-Kincaid Grade           ≤ 8.0                   13.96      10.33     11.03        11.39    12.80
                  Flesch Reading Ease            ≥ 60                   34.25      52.20     49.23        46.29    31.08
                    Gunning Fog Index          ≤ 12.0                   16.92      12.37     13.37        13.68    15.59
                           SMOG Index           ≤ 8.0                   15.46      12.33     13.07        13.13    14.23
                   Coleman-Liau Index           ≤ 8.0                   14.12      12.08     12.27        12.68    15.62
====================================================================================================